### ISSUE TITLE
Toggling Full Screen Mode is Broken on macOS

### ISSUE THREAD

**Issue by Mrwerdo** [SFTtech/openage#1028]
Just what the title says, toggling full screen mode is broken. Clicking on the green full screen button makes the window enter full screen:
<img width="298" alt="image" src="https://user-images.githubusercontent.com/6337878/41498036-4372896e-71a6-11e8-9c7c-da0cb70f5d1f.png">
But while in full screen mode, clicking on the green button doesn't exit full screen: <img width="260" alt="image" src="https://user-images.githubusercontent.com/6337878/41498037-50b2ba2c-71a6-11e8-93ff-ec9361cc162c.png">

**Comment by teldosas** [comment]
I'm on macos high sierra (10.13) and I cannot reproduce that

**Comment by simonsan** [comment]
@Mrwerdo Do you still have this problem with a recent version of openage?

**Comment by Mrwerdo** [comment]
I haven’t looked at it for a while.
