### ISSUE TITLE
Dependency libraries fail to install

### ISSUE THREAD

**Issue by w1lford** [SFTtech/openage#1030]
When I try to install the dependencies for openage on Linux Mint 18.3, all of them install successfully except for `libsdl2-dev` `libsdl2-image-dev`, and `qtdeclarative5-dev` and I get the following error when I try to install them:

```
The following packages have unmet dependencies:
 libsdl2-dev : Depends: libegl1-mesa-dev but it is not going to be installed
               Depends: libgles2-mesa-dev but it is not going to be installed
               Depends: libmirclient-dev but it is not going to be installed
               Depends: libwayland-dev but it is not going to be installed
               Depends: libxkbcommon-dev but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

I have a hunch it has something to do with the Nvidia proprietary graphics drivers but I don't know what to do to fix the issue.

**Comment by heinezen** [comment]
It could be this?

https://askubuntu.com/questions/887770/broken-packages-on-16-10-yakkety-trying-to-install-libsdl2-dev

Try the solution presented there. Maybe that helps.

**Comment by TheJJ** [comment]
Were you able to solve your problem? If not, I can recommend consulting the community forum of Linux Mint, they might be able to help you. If you need further assistance from us, please call back :)
