### ISSUE TITLE
[question] How to install keybinds.oac into $(PREFIX)/etc/openage ?

### ISSUE THREAD

**Issue by yurivict** [SFTtech/openage#1033]
By default it installs into /etc/openage/keybinds.oac.
How to change this?

**Comment by TheJJ** [comment]
You can change the `/etc/openage` part with `ccmake` by changing the `GLOBAL_CONFIG_DIR`. The default is set up here:
https://github.com/SFTtech/openage/blob/6a21d90dbd22324104cc20d252bc1e21f1dcda82/CMakeLists.txt#L86-L93

**Comment by yurivict** [comment]
This works, thanks!
