### ISSUE TITLE
Q: Why not use the python unittest module?

### ISSUE THREAD

**Issue by haydenhughes** [SFTtech/openage#1041]
Hi. I'm sure there's a reasonable answer but I noticed that you created your own `assert_value` and `assert_raises` which is the same as `assertEqual` and `assertRaises` from the built in python [unittest module](https://docs.python.org/3.5/library/unittest.html).

**Comment by TheJJ** [comment]
I can't tell for sure but i think we just didn't know about that function and we just wanted to create a "unified testing experience" for Python and C++ (through the py-cpp interface).

There is much room for improvements, especially for testing our code, feel free to contribute.
I must confess testing has not been the priority for this project and there are many other places that need to be worked on :smile:
