### ISSUE TITLE
Flatpak build

### ISSUE THREAD

**Issue by LeandroStanger** [SFTtech/openage#1050]
Please, consider supporting [Flatpak](http://docs.flatpak.org/en/latest/introduction.html#reasons-to-use-flatpak) and publishing Openage on [Flathub](https://github.com/flathub/flathub/wiki/App-Submission).

**Comment by TheJJ** [comment]
as the tag says, just do it! :)

**Comment by TheJJ** [comment]
http://flatkill.org/

**Comment by LeandroStanger** [comment]
@TheJJ https://github.com/flathub/flathub/issues/670

**Comment by simonsan** [comment]
Regarding flatpak packages: 

A libre replacement for Steam uses flatpak packages to organise games as steam does with it's library. 
https://gitlab.com/librebob/athenaeum

**Comment by okias** [comment]
I originally created #1322 , but since it's Debian/Ubuntu and clones related, doing Flatpak would have much bigger reach for Linux distributions...

So, if there is here anyone not yet convinced with flatpak skills, please consider creating flatpak build. Also I'm willing tip $ 10 for continuous & release flatpak build.

**Comment by okias** [comment]
@TheJJ appid should be still `lol.sfttech.openage` or `mx.sft.openage`?

**Comment by TheJJ** [comment]
good idea, i'd prefer the lol domain since it can do dnssec and is funnier. heh.

**Comment by okias** [comment]
Ok, I'll use `lol.sfttech.openage`. If you have control over the domain, would be nice if you can make `https://openage.sfttech.lol` redirect to `openage.sft.mx` :+1:

**Comment by rugk** [comment]
Hmm there is flatpak support, but I could not find it on flathub?

https://flathub.org/apps/search?q=open%20age
https://flathub.org/apps/search?q=openage

It would be nice if you could publish this as a [flatpak](https://flatpak.org/) on [flathub](https://flathub.org/) e.g.

Flatpaks are a new software distribution mechanism for Linux distros, can thus installed on any distro and are easy to update. They are easy to install _and_ update and work on all Linux distros.
Also, if you publish it on _FlatHub_ you may grow your user base given many distros include that and it is a common software source, so your app can be discovered more easily. 

Here is [how to get started](http://docs.flatpak.org/en/latest/getting-started.html).

**Comment by TheJJ** [comment]
we removed flatpak support since it was left unmaintained in e3fa81e90044a2f1c96bebe10d56a45b354f72c5.
we'll reconsider our distribution ways once the game is actually more playable and a growing user seems useful.

**Comment by rugk** [comment]
So maybe reopen this issue?

**Comment by rugk** [comment]
So maybe reopen this issue?

**Comment by okias** [comment]
Hmm, 4 years ago, it brings memories...

**Comment by heinezen** [comment]
I'll reopen and we think about it when there's more to show.
