### ISSUE TITLE
std::unary_function removed in C++17

### ISSUE THREAD

**Issue by Fish201809** [SFTtech/openage#1051]
I tried to compile the source code in vs2017, But something went wrong.
The error is as follows. Why did this error occur?

“unary_function”: not the member of “std”

**Comment by heinezen** [comment]
This is a function removed in C++17.

https://en.cppreference.com/w/cpp/utility/functional/unary_function

Seems like `gcc` and `clang` haven't removed it yet, but VS2017 did. That's why it slipped under our radar.

**Comment by liuping1997** [comment]
Maybe u need this patch code?
```
#if _MSC_VER >= 1910
namespace std{
template <class Arg, class Result>
struct unary_function
{
    typedef Arg argument_type;
    typedef Result result_type;
};

template <class Arg1, class Arg2, class Result>
struct binary_function
{
    typedef Arg1 first_argument_type;
    typedef Arg2 second_argument_type;
    typedef Result result_type;
};
};
#endif
```

**Comment by mic-e** [comment]
No. MSVC is right, we should not work around it. openage is a C++17 project, so it should not use `unary_function`.

Instead, we need to change `eventqueue.h` to use the more modern `std::function` instead of `std::unary_function`.
