### ISSUE TITLE
Add support for OpenGL uniform buffers

### ISSUE THREAD

**Issue by Vtec234** [SFTtech/openage#1053]
### Contributing to the new renderer:
The renderer interface is defined in headers, with the main class in `libopenage/renderer/renderer.h`.
A good place to start looking is `libopenage/renderer/tests.cpp`, which presents a sample usage of the renderer. To run the test, after compiling Openage do `./run test -vd renderer.tests.renderer_demo 0`.

### Required knowledge:
You need to know how [uniform buffers](https://www.khronos.org/opengl/wiki/Uniform_Buffer_Object) work in OpenGL and [how to use them](https://learnopengl.com/Advanced-OpenGL/Advanced-GLSL).

### What to modify:
1. The GLSL parser in `libopenage/renderer/opengl/shader_program.cpp` should support uniform blocks and arrays.
2. A class should exist in `libopenage/renderer/opengl` to create uniform buffers. `buffer.h` could probably support this without much modification.
3. The shader program interface in `libopenage/renderer/shader_program.h` should support setting block/array inputs. This will also require support in `libopenage/renderer/opengl/uniform_input.h`.
4. Documentation should be added to every new header and existing documentation updated to reflect changes.

**Comment by heinezen** [comment]
Uniform buffers were added in https://github.com/SFTtech/openage/pull/1513
