### ISSUE TITLE
Implement a parser for the new sprite format

### ISSUE THREAD

**Issue by Vtec234** [SFTtech/openage#1055]
### Contributing to the new renderer:
The renderer interface is defined in headers, with the main class in `libopenage/renderer/renderer.h`.
A good place to start looking is `libopenage/renderer/tests.cpp`, which presents a sample usage of the renderer. To run the test, after compiling Openage do `./run test -vd renderer.tests.renderer_demo 0`.

### Required knowledge:
* Reading a file and parsing a regular language
* You need to be familiar with how animations can be drawn from texture atlases.

### What to modify:
1. The new sprite format is defined in [this doc](https://github.com/SFTtech/openage/blob/master/doc/media/openage/sprite_format_spec.md). A parser for it should be implemented in `libopenage/renderer/resources`, using the existing `Texture2d..` classes to store the actual data. The sprite could be stored in a class such as `Sprite2dAnimated`.
2. A test for drawing animations with these sprites should be added to `libopenage/renderer/tests.cpp`, e.g. as test number `1`. The animation timing logic should not be added to the renderer itself, but rather implemented on top of it.
3. Documentation should be added to every new header and existing documentation updated to reflect changes.

**Comment by Montx** [comment]
I would like to do this contribution.

**Comment by Vtec234** [comment]
@Montx feel free to ask on IRC/Matrix about anything you might need.

**Comment by TheJJ** [comment]
Please include the [documentation draft](https://pad.stusta.de/p/openage-sprite-format) in the pull request so it becomes official (as `doc/media/sprites.md`).

**Comment by Montx** [comment]
Sorry guys I taught I could pick this one up but I am on a mac and I can't updated it to Mojave yet. So there are some function on the game that are not supported by High Sierra. Currently I don't have my windows setup, and I can't mess with this mac, since it's not mine :/

**Comment by Firearrow5235** [comment]
I think I can handle this one. I've implemented SpriteSheet parsing and animation in MonoGame before. Just need to smash through those Windows build errors. 😝

**Comment by simonsan** [comment]
@Firearrow5235 I attached a yaml-File for appveyor that should help you setting up your own pipeline. You still need to change the file extension and change some stuff inside. But openage should be building fine with this on windows. So you don't need to smash through those build errors. ;-)

[appveyor_vcpkg.yml.txt](https://github.com/SFTtech/openage/files/3641790/appveyor_vcpkg.yml.txt)

**Comment by Aakash10-Coder** [comment]
How can I contribute to this project ? please let me know.

**Comment by simonsan** [comment]
@Aakash10-Coder You could read a bit through our [contribution guide](https://github.com/SFTtech/openage/blob/master/doc/contributing.md). Also I would recommend to pass by in the [developers chat](https://riot.im/app/#/room/#sfttech:matrix.org) to figure out with the other people what can be done. :-)

**Comment by abowassm** [comment]
> ### المساهمة في العارض الجديد:
> يتم تعريف واجهة العارض في الرؤوس ، مع الفئة الرئيسية في `libopenage/renderer/renderer.h`.
> مكان جيد للبدء في البحث هو `libopenage/renderer/tests.cpp`، والذي يقدم عينة من استخدام العارض. لتشغيل الاختبار ، بعد تجميع Openage القيام به `./run test -vd renderer.tests.renderer_demo 0`.
> 
> ### المعرفة المطلوبة:
> * قراءة ملف وتحليل لغة عادية
> * عليك أن تكون على دراية بكيفية رسم الرسوم المتحركة من أطلسات النسيج.
> 
> ### ما الذي يجب تعديله:
> 1. يتم تعريف تنسيق العفريت الجديد في [# 965](https://github.com/SFTtech/openage/issues/965) . يجب تنفيذ محلل له `libopenage/renderer/resources`، وذلك باستخدام `Texture2d..`الفئات الموجودة لتخزين البيانات الفعلية. يمكن تخزين العفريت في فصل مثل `Sprite2dAnimated`.
> 2. A test for drawing animations with these sprites should be added to `libopenage/renderer/tests.cpp`, e.g. as test number `1`. The animation timing logic should not be added to the renderer itself, but rather implemented on top of it.
> 3. Documentation should be added to every new header and existing documentation updated to reflect changes.

What a creativity
