### ISSUE TITLE
#include <unistd.h> can not work in windows

### ISSUE THREAD

**Issue by Fish201809** [SFTtech/openage#1057]
cannot open source file "unistd.h"	
E0020	identifier "usleep" is undefined

**Comment by TheJJ** [comment]
Can you tell us from which file that error comes from, i.e. where we included it?

**Comment by Fish201809** [comment]
> Can you tell us from which file that error comes from, i.e. where we included it?

The file path is as follows
    g:\gitsrc\openage\libopenage\event\demo\main.cpp(6): fatal error C1083: Cannot open include file: 'unistd.h': No such file or directory

**Comment by Fish201809** [comment]
> Can you tell us from which file that error comes from, i.e. where we included it?

>The file directory is as follows
g:\gitsrc\openage\libopenage\event\demo\main.cpp(6): fatal error C1083: Cannot open include file: 'unistd.h': No such file or directory

**Comment by heinezen** [comment]
`unistd.h` is unique to POSIX platforms. https://en.wikipedia.org/wiki/Unistd.h

Workaround: https://stackoverflow.com/questions/341817/is-there-a-replacement-for-unistd-h-for-windows-visual-c

**Comment by TheJJ** [comment]
I don't think that file needs `unistd.h` at all. And if it does, we should try to find a crossplattform alternative, e.g. use the c++stdlib.
