### ISSUE TITLE
buildsystem builds unchanged things when touching unrelated files

### ISSUE THREAD

**Issue by TheJJ** [SFTtech/openage#1075]
Our buildsystem has some bug where some files are recompiled even though no changes were made to them (and no header changed etc).

(In order to speed up debugging this, you can configure openage with `ccache` support: `./configure --ccache`).

Steps to reproduce:
* have an up-to-date fully-build openage project folder
* verify this by running `make` and observing that nothing is built
* `touch libopenage/log/CMakeLists.txt`
* `make`
* observe that for example `libopenage/CMakeFiles/libopenage.dir/pathfinding/a_star.cpp.o` is built even though that should definitely be unaffected and not rebuilt just because the `CMakeLists` of `log` was touched

**Comment by Vtec234** [comment]
Given that `a_star.cpp` uses logging, isn't it legitimate for it to be rebuilt when the logging module might have changed (as per `log/CMakeLists.txt`)?

**Comment by tusharpm** [comment]
An incremental build shouldn't involve compiling the sources unless the dependencies or build flags are touched.
I use `ninja` instead of `make` and it does "the right thing", i.e. no compile and no link. I'll investigate the behaviour of the latter.
