### ISSUE TITLE
windows cmake build error - python module

### ISSUE THREAD

**Issue by schmidtnicholas** [SFTtech/openage#1079]
Running `cmake -DCMAKE_TOOLCHAIN_FILE=<vcpkg directory>/scripts/buildsystems/vcpkg.cmake ..` on Windows gives the following error:

> cython module
>         run                                                 [embedded interpreter] [noinstall]
>         openage.cabextract.lzxd
>         openage.cabextract.cabchecksum                      [standalone]
>         openage.convert.slp
>         openage.convert.interface.visgrep
>         openage.convert.opus.opusenc
>         openage.cppinterface.exctranslate
>         openage.cppinterface.exctranslate_tests
>         openage.cppinterface.pyobject
>         openage.cppinterface.setup_checker
>         openage.cvar.cvar
>         openage.event.demo
>         openage.game.main_cpp
>         openage.log.log_cpp
>         openage.util.filelike.cpp
>         openage.util.fslike.cpp
>         openage.renderer.renderer_cpp
>         openage.renderer.tests
>         openage.testing.cpp_testing
>         openage.testing.misc_cpp

> file was not listed via add_py_module: __init__.py
> file was not listed via add_py_module: __main__.py
> file was not listed via add_py_module: assets.py
> file was not listed via add_py_module: cabextract\__init__.py
> file was not listed via add_py_module: cabextract\cab.py
> file was not listed via add_py_module: cabextract\lzxdstream.py
> file was not listed via add_py_module: cabextract\test.py
> file was not listed via add_py_module: codegen\__init__.py
> file was not listed via add_py_module: codegen\codegen.py
> file was not listed via add_py_module: codegen\coord.py
> file was not listed via add_py_module: codegen\cpp_testlist.py
> file was not listed via add_py_module: codegen\gamespec_structs.py
> file was not listed via add_py_module: codegen\listing.py
> file was not listed via add_py_module: codegen\main.py
> file was not listed via add_py_module: convert\__init__.py
> file was not listed via add_py_module: convert\binpack.py
> file was not listed via add_py_module: convert\blendomatic.py
> file was not listed via add_py_module: convert\changelog.py
> file was not listed via add_py_module: convert\colortable.py
> file was not listed via add_py_module: convert\dataformat\__init__.py
> file was not listed via add_py_module: convert\dataformat\content_snippet.py
> file was not listed via add_py_module: convert\dataformat\data_definition.py
> file was not listed via add_py_module: convert\dataformat\data_formatter.py
> file was not listed via add_py_module: convert\dataformat\entry_parser.py
> file was not listed via add_py_module: convert\dataformat\exportable.py
> file was not listed via add_py_module: convert\dataformat\generated_file.py
> file was not listed via add_py_module: convert\dataformat\header_snippet.py
> file was not listed via add_py_module: convert\dataformat\member_access.py
> file was not listed via add_py_module: convert\dataformat\members.py
> file was not listed via add_py_module: convert\dataformat\multisubtype_base.py
> file was not listed via add_py_module: convert\dataformat\struct_definition.py
> file was not listed via add_py_module: convert\dataformat\struct_snippet.py
> file was not listed via add_py_module: convert\dataformat\util.py
> file was not listed via add_py_module: convert\driver.py
> file was not listed via add_py_module: convert\drs.py
> file was not listed via add_py_module: convert\fix_data.py
> file was not listed via add_py_module: convert\game_versions.py
> file was not listed via add_py_module: convert\gamedata\__init__.py
> file was not listed via add_py_module: convert\gamedata\civ.py
> file was not listed via add_py_module: convert\gamedata\empiresdat.py
> file was not listed via add_py_module: convert\gamedata\graphic.py
> file was not listed via add_py_module: convert\gamedata\maps.py
> file was not listed via add_py_module: convert\gamedata\playercolor.py
> file was not listed via add_py_module: convert\gamedata\research.py
> file was not listed via add_py_module: convert\gamedata\sound.py
> file was not listed via add_py_module: convert\gamedata\tech.py
> file was not listed via add_py_module: convert\gamedata\terrain.py
> file was not listed via add_py_module: convert\gamedata\unit.py
> file was not listed via add_py_module: convert\hardcoded\__init__.py
> file was not listed via add_py_module: convert\hardcoded\langcodes.py
> file was not listed via add_py_module: convert\hardcoded\langcodes_hd.py
> file was not listed via add_py_module: convert\hardcoded\termcolors.py
> file was not listed via add_py_module: convert\hardcoded\terrain_tile_size.py
> file was not listed via add_py_module: convert\hardcoded\texture.py
> file was not listed via add_py_module: convert\hdlanguagefile.py
> file was not listed via add_py_module: convert\interface\__init__.py
> file was not listed via add_py_module: convert\interface\cutter.py
> file was not listed via add_py_module: convert\interface\hardcoded.py
> file was not listed via add_py_module: convert\interface\rename.py
> file was not listed via add_py_module: convert\main.py
> file was not listed via add_py_module: convert\opus\__init__.py
> file was not listed via add_py_module: convert\opus\demo.py
> file was not listed via add_py_module: convert\pefile.py
> file was not listed via add_py_module: convert\peresource.py
> file was not listed via add_py_module: convert\singlefile.py
> file was not listed via add_py_module: convert\slp_converter_pool.py
> file was not listed via add_py_module: convert\stringresource.py
> file was not listed via add_py_module: convert\texture.py
> file was not listed via add_py_module: cppinterface\__init__.py
> file was not listed via add_py_module: cppinterface\setup.py
> file was not listed via add_py_module: cvar\__init__.py
> file was not listed via add_py_module: cvar\config_file.py
> file was not listed via add_py_module: cvar\location.py
> file was not listed via add_py_module: default_dirs.py
> file was not listed via add_py_module: devmode.py
> file was not listed via add_py_module: event\__init__.py
> file was not listed via add_py_module: game\__init__.py
> file was not listed via add_py_module: game\main.py
> file was not listed via add_py_module: log\__init__.py
> file was not listed via add_py_module: log\tests.py
> file was not listed via add_py_module: renderer\__init__.py
> file was not listed via add_py_module: testing\__init__.py
> file was not listed via add_py_module: testing\benchmark.py
> file was not listed via add_py_module: testing\doctest.py
> file was not listed via add_py_module: testing\list_processor.py
> file was not listed via add_py_module: testing\main.py
> file was not listed via add_py_module: testing\testing.py
> file was not listed via add_py_module: testing\testlist.py
> file was not listed via add_py_module: util\__init__.py
> file was not listed via add_py_module: util\bytequeue.py
> file was not listed via add_py_module: util\context.py
> file was not listed via add_py_module: util\decorators.py
> file was not listed via add_py_module: util\filelike\__init__.py
> file was not listed via add_py_module: util\filelike\abstract.py
> file was not listed via add_py_module: util\filelike\fifo.py
> file was not listed via add_py_module: util\filelike\readonly.py
> file was not listed via add_py_module: util\filelike\stream.py
> file was not listed via add_py_module: util\files.py
> file was not listed via add_py_module: util\fslike\__init__.py
> file was not listed via add_py_module: util\fslike\abstract.py
> file was not listed via add_py_module: util\fslike\directory.py
> file was not listed via add_py_module: util\fslike\filecollection.py
> file was not listed via add_py_module: util\fslike\path.py
> file was not listed via add_py_module: util\fslike\test.py
> file was not listed via add_py_module: util\fslike\union.py
> file was not listed via add_py_module: util\fslike\wrapper.py
> file was not listed via add_py_module: util\fsprinting.py
> file was not listed via add_py_module: util\iterators.py
> file was not listed via add_py_module: util\math.py
> file was not listed via add_py_module: util\profiler.py
> file was not listed via add_py_module: util\strings.py
> file was not listed via add_py_module: util\struct.py
> file was not listed via add_py_module: util\system.py
> file was not listed via add_py_module: util\threading.py
> CMake Error at buildsystem/python.cmake:504 (message):
>   .py file listing inconsistent
> Call Stack (most recent call first):
>   CMakeLists.txt:223 (python_finalize)
> 
> 
> -- Configuring incomplete, errors occurred!

Any tips on how to get past this error?

**Comment by TheJJ** [comment]
fixed in #1080
