### ISSUE TITLE
Define scaling factor for sprites

### ISSUE THREAD

**Issue by heinezen** [SFTtech/openage#1162]
The Definitive Editions come with unit sprites that have multiple scaling factors, usually one "normal-sized" sprite and one or two versions with higher resolutions. Obviously, the ingame sprites of the unit should still have the same size, albeit with more details when zooming in with higher resolution sprites. Thus, we would need a scaling factor that tells the renderer the ingame size of each sprite.

The easiest solution I could think of is the introduction of a new parameter in the sprite file that stores the pixel ratio. Something along the lines of:

```
scalefactor 1
```

This would tell the renderer that the sprite should be drawn with a 1:1 pixel ratio at the default zoom level. `scalefactor 2` is then a 2:1 ratio, or in other words, at 2x zoom the sprite is shown in full detail. `scalefactor 4` has a 4:1 ratio and is shown in full detail at 4x zoom and so on...

**Comment by brisvag** [comment]
Will need to keep this in mind in #1108.
