### ISSUE TITLE
Add .clang-format configuration file

### ISSUE THREAD

**Issue by simonsan** [SFTtech/openage#1166]
Referring to something mentioned in #313, `clang-format` does have a checking only mode, and is hence suitable for travis.
Again something that would help with #313 as well, `clang-format` can also enforce (and automatically convert) using spaces for indentation instead of tabs.

While you can keep defining regexes for specific cases like spaces around operators, `clang-format` can support a wide variety of such coding standards, and is a one-stop solution to most such problems.

The benefits of `clang-format` - 

1. Autofixing issues as well as detecting them.
2. One stop solution to all current and future code formatting and compliance issues.
3. Is an Extremely powerful formatting engine, so much so that so far I have yet to encounter cases it fails to handle acceptably, including enforcing a spaces-only mode (#313).
4. Not at all a big task to implement, all the formatting options reside in a simple config file.

On a side note, if people in this community want to use it and aren't familiar with this tool, I can implement the above.

_Originally posted by @akhilkedia in https://github.com/SFTtech/openage/issues/837#issuecomment-307636379_

[Clang-Format Homepage](https://clang.llvm.org/docs/ClangFormat.html)

**Comment by simonsan** [comment]
I think it would be really nice to translate our coding style into a configuration file we can use for clang-format for the use in an IDE.

**Comment by TheJJ** [comment]
Does clang-format support our indentation ruleset yet? if not, we should not enforce the style clang-format would prefer.
There's some people out there that specifically chose (or will chose) to contribute to openage because of our sane™ codestyle, so we should not leave that path.

If we really want to do a full compliance check, I'm sure the missing features and rules can be contributed to clang-format: this makes the world a better place for other projects and helps this project in particular.

**Comment by simonsan** [comment]
> Does clang-format support our indentation ruleset yet? if not, we should not enforce the style clang-format would prefer.

I read about that but I still have to figure out what it does and how. 

> If we really want to do a full compliance check, I'm sure the missing features and rules can be contributed to clang-format: this makes the world a better place for other projects and helps this project in particular.

That's a good idea, but as mentioned above I still need to figure out if it could be achieved already or not. We could do that some time together, first I need to play around a bit and find some fitting settings.

**Comment by heinezen** [comment]
This was added a while ago https://github.com/SFTtech/openage/blob/master/.clang-format
