### ISSUE TITLE
multiple Mod support

### ISSUE THREAD

**Issue by fekir** [SFTtech/openage#1189]
openage apparently officially supports the unofficial "Age of Empires 2: Forgotten Empires" mod.

Will openage support other mods?

Forgotten Empires presented itself as a second expansion pack, but there are other (and older) mods like

 * [Age of Chivalry](http://aok.heavengames.com/age-of-chivalry) (also https://ageofchivalrymod.wordpress.com/)
  * [Age of Vampires: Blood Reign in Transsylvania](http://aok.heavengames.com/features/blacksmith-features/age-of-vampires-blood-reign-in-transsylvania/)
 * [Tales of Middle-Earth](http://aok.heavengames.com/tales-of-middle-earth/)
  * [Rome at War](https://wildfiregames.com/raw/)

And probably many other that I'm not even aware of.

The advantage of wine and WINEPREFIX is that it is possible to install all of those independently one of another (see https://www.playonlinux.com/en/supported_apps-1-0.html).

AFAIK all those mods modify the assets used by the game (maybe tweak the AI too), so I would expect them to be supported like "Age of Empires 2: Forgotten Empires".

Even better, if the license permits it (if the sprites where written from scratch), as some mods replace nearly every unit, it might be possible to bundle openage with some mods installed by default.

**Comment by heinezen** [comment]
Yes, we will eventually support all of the older mods by converting them to formats that openage understands. #1151 will introduce the foundation for that. Everything that runs on openage will essentially be a mod, even Age of Empires 2, and can be combined with any other mod configuration :)

**Comment by TheJJ** [comment]
I think that should answer your question, @fekir. If not, pls tell us.

**Comment by fekir** [comment]
@TheJJ : yes, it does

I would not have been to able to understand it from #1151

Thank you
