### ISSUE TITLE
AoE II HD Asset conversion fails

### ISSUE THREAD

**Issue by stephen304** [SFTtech/openage#1217]
I have AoE 2 HD on Steam, so I gave openage the `steamapps/common/Age2HD` path but it gave me:

    WARN [py] You have installed incompatible game version(s):
    WARN [py]  * Age of Empires 2: HD + Rise of the Rajas (Version 5.x)
    WARN [py] You need at least one of:
    WARN [py]  * Age of Empires 2: The Conquerors
    WARN [py]  * Age of Empires 2: The Conquerors, Patch 1.0c
    WARN [py]  * Age of Empires 2: Forgotten Empires
    WARN [py]  * Age of Empires 2: HD Edition (Version 3.0+)
    WARN [py]  * Age of Empires 2: HD + Forgotten Empires (Version 4.0+)
    WARN [py]  * Age of Empires 2: HD + African Kingdoms (Version 4.7+)
     ERR [py] game asset conversion failed

Which is confusing since I don't own the Rise of the Rajas dlc - I tried to fix it by buying all 3 DLCs and making sure none of the DLCs are enabled / installed but I still get the same error. Is there some trick to get it to recognize just HD Edition?

**Comment by simonsan** [comment]
Hey @stephen304,
can you try out that part of our troubleshooting guide:
https://github.com/SFTtech/openage/blob/master/doc/troubleshooting.md#conversion-fails-when-converting-from-aoe-ii-hd-edition

@heinezen is working on a new implementation of the converter that will be able to convert the version 5.8 of HD, until then I'm afraid you will need to set it back to 4.3.

Cheers!

**Comment by stephen304** [comment]
@simonsan Ah thank you! I saw the part about downgrading and didn't check the betas tab and started to panic when I discovered that steam no longer allows using `download_depot` in either the steam console OR steamcmd.

**Comment by simonsan** [comment]
Hey, happy to help. ;-)

As I've got not so much time right now, would you mind proposing your changes as a PR. I think it would be better, because you were working through the docs and know where you needed exactly what information and where they weren't. Let me know if you need any help. Cheers.

**Comment by hhirsch** [comment]
Right click on HD in your library -> properties -> beta -> 4.3

Imho this ticket can be closed.

**Comment by heinezen** [comment]
Should be fixed by now.
