### ISSUE TITLE
dat file format comprehensive documentation?

### ISSUE THREAD

**Issue by Maxzor** [SFTtech/openage#1221]
Is there such a thing anywhere? After 20 years?
Sorry for polluting as this engine rewrite might not even use that file format.

**Comment by TheJJ** [comment]
We've talked in the chatroom about this, but for the afterworld we can retain this: openage can read the dat file and export it into whatever we think is useful. The conversion software resides in `openage/convert`, and you can probably hack in custom exporters in python that suit your needs :1st_place_medal:
