### ISSUE TITLE
AI/HUMAN/CLOSED parameter not defined properly

### ISSUE THREAD

**Issue by blint071** [SFTtech/openage#1226]
The parameter that tells the game if a player has choosen AI/HUMAN/CLOSED "x" slot can´t be found anywhere. In my opinion it should be in lobby subfolder. 
Can somebody tell me where it is? And why it isn´t where I said?

**Comment by simonsan** [comment]
I assume you're talking about the documentation. Could you state more clearly what your question is and about what game version you are talking about?

**Comment by TheJJ** [comment]
We don't have a lobby implementation yet, so this ai/human/closed dropdown menu doesn't exist. So we don't have a lobby subfolder yet. If you need anything else, please notify us.
