### ISSUE TITLE
Ubuntu build break: cmake cannot find Python3 interpreter when I have "alias python=python3"

### ISSUE THREAD

**Issue by duanqn** [SFTtech/openage#1258]
Error message after executing `./configure`:

> -- Could NOT find Python3 (missing: Python3_EXECUTABLE Interpreter) (found suitable version "3.6", minimum required is "3.6")
>     Reason given by package: 
>         Interpreter: Wrong version for the interpreter "/usr/local/bin/python"
> 
> CMake Error at /usr/share/cmake-3.17.2-Linux-x86_64/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:164 (message):
>   Could NOT find Python (missing: PYTHON) (Required is at least version
>   "3.6")
> Call Stack (most recent call first):
>   /usr/share/cmake-3.17.2-Linux-x86_64/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:445 (_FPHSA_FAILURE_MESSAGE)
>   buildsystem/modules/FindPython.cmake:69 (find_package_handle_standard_args)
>   buildsystem/HandlePythonOptions.cmake:6 (find_package)
>   CMakeLists.txt:167 (include)

I think this is an issue with CMake. I checked my system, I set `alias python=python3` in my `.bash_aliases` file.
`which python` evaluates to /usr/local/bin/python, which is a link to /usr/local/bin/python2, and that is what CMake found.
I think CMake then executed `python --version` and got 3.6 so it thinks this is the right interpreter, but it isn't. CMake should really be testing `$(which python) --version`.

=====System info=====
OS: Ubuntu 18.04
CMake: 3.17.2
Python: 2.7.16 / 3.6.9

**Comment by duanqn** [comment]
Does anyone have a workaround for this? Can I pass some command line arguments to `./configure` to set the `Python3_EXECUTABLE` variable in CMake?

**Comment by simonsan** [comment]
Looks like you don't have `python3-dev` installed, could that be true?

**Comment by duanqn** [comment]
I have python3-dev installed. Also I tried `unalias python` to remove the alias but I got the same problem. Maybe the alias is not the reason.

**Comment by duanqn** [comment]
I just confirmed that the -DPYTHON_DIR switch works.

**Comment by simonsan** [comment]
We changed the way Python is searched about last week. In most cases it should not give any problems. In some special cases it will. We need to take a look how far we will need to add support there though, as the newer implementation (the official one we use now) should be sufficient for most of the standard cases on all platforms. If your question is answered here, feel free to close. ;-) 

ref.: #1245, #1246

**Comment by duanqn** [comment]
I'm still confused by the CMake output 

> (found suitable version "3.6", minimum required is "3.6")

When I set -DPYTHON_DIR CMake reports 

> -- Found Python3: /usr/bin/python3.6 (found suitable version "3.6.9", minimum required is "3.6")

But it doesn't look like our problem.

**Comment by simonsan** [comment]
Renamed it for future searches. 👍

**Comment by TheJJ** [comment]
Maybe we need minimum version defined as `3.6.0` because it's confused by the third part? We should investigate.

**Comment by simonsan** [comment]
> Maybe we need minimum version defined as `3.6.0` because it's confused by the third part? We should investigate.

Not sure, I think it's not the version, but the `alias` and CMake caching, hence why the `unalias` didn't work. I think everything works as expected here = not working. At least I wouldn't have expected it to deal with this is the part `alias python=python3` != `/usr/local/bin/python` => `/usr/local/bin/python2`.
