### ISSUE TITLE
Question: How can I add a new unit test?

### ISSUE THREAD

**Issue by duanqn** [SFTtech/openage#1261]
Hi I rewrote libopenage/datastructure/concurrent_queue.h to make it support move-only elements (e.g. std::unique_ptr) #1260 . 

I also have written a simple unit test for it, but I don't know where I should put it. I'm not familiar with CMake. How can I add it as a new target for `make test`?

**Comment by heinezen** [comment]
Listing them in the Python function should do the trick:

https://github.com/SFTtech/openage/blob/b5d732f6637d6ac95619db87b0c155ad0c697561/openage/testing/testlist.py#L68-L99

**Comment by duanqn** [comment]
Got it. Thanks!
