### ISSUE TITLE
Assertions

### ISSUE THREAD

**Issue by duanqn** [SFTtech/openage#1269]
Hi, what's our choice on assertions? I can't find assert() in our codebase except for the Qt part.
I want a way to write assertions that only run in Debug mode.

Also, if an assertion fails, what should we do? Should we throw a openage::Error ?

**Comment by simonsan** [comment]
I think @TheJJ will be able to explain it much better, I'm just here to throw in some visualisation of the **Error** and **LogSink** classes.

![openage_logsink](https://user-images.githubusercontent.com/14062932/81487845-e7672100-9261-11ea-9bfb-31ce5b089df9.png)
![openage_error](https://user-images.githubusercontent.com/14062932/81487846-e930e480-9261-11ea-9147-afeee1082552.png)

**Comment by TheJJ** [comment]
We use the `ENSURE` macro, which basically is an assert that throws `openage::Errors`.
