### ISSUE TITLE
Cannot compile with gcc 10 on Ubuntu 18.04

### ISSUE THREAD

**Issue by duanqn** [SFTtech/openage#1272]
First issue: libopenage/util/hash.h should include `<cstdint>` for types like uint8_t
There are some issues in the nyan source code as well.

**Comment by simonsan** [comment]
I fixed it here:
https://github.com/SFTtech/openage/pull/1270/files#diff-f30302a8c23a15eecf4b8e34c724c246

**Comment by TheJJ** [comment]
I think we've fixed both of them now, in SFTtech/nyan@2d6fba801a34e67677ce212c8af7c0f991d2bbcd and 454a08557b4623829e322410180ebcd7ff776996.
