### ISSUE TITLE
Create manifest file for modpacks

### ISSUE THREAD

**Issue by heinezen** [SFTtech/openage#1287]
**Required skills**: Python

**Difficulty**: Easy

Modpacks should contain a manifest file which lists all files in the modpack and also stores the hashes of these files. Manifests can be used for an integrity check when the modpack loads. Additionally, manifest files can be signed cryptographically by us which will be used as an indication that a modpack is *safe* (= it doesn't contain malware).

The structure of the file should be very simple. One line (`hash $name`) defines what hash to use, all other lines contain a relative filepath and the hash value of that file, e.g.:

```
# openage autogenerated modpack integrity check
hash SHA3-256
bc821027ed1b666d8653760 relative/path/to/file
ea4e89ce46f0f8c4dad2344 another/file
...
```

SHA3-256 or SHA3-512 should suffice as hash algorithms.

It's important that the order of entries in the file is the same every time and for every platform, otherwise it will be difficult to distribute signatures for locally converted. Using something like breadth-first search should ensure this property.

**Comment by drs-11** [comment]
Hey I think I can work on this! Looks doable enough for me.
Some questions tho:
- Is this supposed to be like a CLI utility tool for creating a manifest file for a given modpack?
- Where would the code go for this in the code base?
- Does the manifest file need to be in plain text format? If not I think making it in json format would be good enough.

**Comment by heinezen** [comment]
@drs-11 Hey! :)

> Is this supposed to be like a CLI utility tool for creating a manifest file for a given modpack?

It is supposed to be integrated, not a CLI utility. The manifest should be created after the the converter exported all files in the modpack (see below).

> Where would the code go for this in the code base?

It should happen at the end of the `export()` function in here:

https://github.com/SFTtech/openage/blob/master/openage/convert/processor/export/modpack_exporter.py#L18-L73

This is the place where the converter exports all files. After that's finished, the manifest should be created. You can use the `ModpackInfo` class as a template for the format of the manifest file. 

https://github.com/SFTtech/openage/blob/master/openage/convert/entity_object/export/formats/modpack_info.py

> Does the manifest file need to be in plain text format? If not I think making it in json format would be good enough.

It doesn't have to be, but if you use a structured format, TOML is preferred (because we already use it as a dependency). `ModpackInfo` also creates an output for TOML.

**Comment by drs-11** [comment]
Okay got it. On it!
