### ISSUE TITLE
Age of Empires 2: HD Edition modpack support

### ISSUE THREAD

**Issue by heinezen** [SFTtech/openage#1289]
**Required skills**: Python

**Difficulty**: Medium

The converter should get support for creating modpacks based on the HD Edition of AoE2 (also called Age of Empires 2 (2013)). HD is basically the same as AoE2 + The Conqueror's (AoC), but it has new team tech effects and a few new civ flags introduced with the expansions. Therefore, the HD converter should be able to reuse most of the functionality of the existing AoC converter.

The asset formats used in HD are also mostly the same as in AoC, so the already existing media parsers can be used. HD's biggest change to the assets is that the release no longer uses DRS containers for media files and stores them in folders instead.

The HD Edition has 3 expansions which are optional in theory. However, we recommend that you treat HD and all its expansions as one game for simplicities sake, unless you are already familiar enough with the converter.

**Further reading**:

* [AoC converter code](https://github.com/SFTtech/openage/blob/master/openage/convert/processor/conversion/aoc/)
* [Converter architecture](https://github.com/SFTtech/openage/blob/master/doc/code/converter/architecture_overview.md)
* [Converter workflow](https://github.com/SFTtech/openage/blob/master/doc/code/converter/workflow.md)

**Comment by mmtj** [comment]
Could you point me to some docs describing AoE assets data formats and their differences? Even though I have an idea which code should be changed, I don't really have good understanding of assets data.

I only own AoE2: HD edition (apart from probably long lost CD of AoE2), so I can't try conversion of any other assets.

**Comment by heinezen** [comment]
[/doc/media](https://github.com/SFTtech/openage/tree/master/doc/media) has all info on the data formats. HD's terrain files and 32-Bit SLPs are the only major change compared to AoC I think.

**Comment by heinezen** [comment]
HD conversion works for a long time now.
