### ISSUE TITLE
Set PNG compression optimization level via CLI

### ISSUE THREAD

**Issue by heinezen** [SFTtech/openage#1290]
**Required skills**: Python, maybe Cython

**Difficulty**: Easy

Our converter PNG export module supports 3 built-in compression levels

* *none*
* *default* libpng compression
* *optimized* compression

However, this functionality is currently unused as the converter is hardcoded to always use the *default* compression setting. We should implement a way to set the desired compression level with a CLI flag. The CLI flag should be added to the main `convert` module creating the modpacks as well as the `convert-file` submodule that can convert standalone files.

**Further reading**:

* [Texture export code](https://github.com/SFTtech/openage/blob/3863e5e76e1c55b19ee49c65b14f97d318870423/openage/convert/entity_object/export/texture.py#L124)
* [Converter architecture](https://github.com/SFTtech/openage/blob/master/doc/code/converter/architecture_overview.md)
* [Converter workflow](https://github.com/SFTtech/openage/blob/master/doc/code/converter/workflow.md)

**Comment by dev-patel2104** [comment]
@heinezen can i work on these one ?

**Comment by TheJJ** [comment]
No need to ask for permission, just do it and submit a pull request :)

**Comment by heinezen** [comment]
@dev-patel2104 You can :)

The most relevant code snippets are here:

https://github.com/SFTtech/openage/blob/dc3980146f814ed42e6aa1c92bcba18621386c8b/openage/convert/service/export/png/png_create.pyx#L57



and here:

https://github.com/SFTtech/openage/blob/dc3980146f814ed42e6aa1c92bcba18621386c8b/openage/convert/entity_object/export/texture.py#L124

**Comment by janisozaur** [comment]
I would recommend you migrate to webp. I tested this recently on a few projects and there is pretty much 20% of bytes saved over lossless, fully optimized PNGs across the board.

**Comment by heinezen** [comment]
@janisozaur Interesting. Do you have more info about the decoding speed?

**Comment by janisozaur** [comment]
No, sorry. I haven't checked.

**Comment by janisozaur** [comment]
According to webp devs themselves, it's pretty much better across the board: https://developers.google.com/speed/webp/docs/webp_lossless_alpha_study (see table 3 for decoding)

**Comment by heinezen** [comment]
@janisozaur If it has better decoding speed that's a big plus :) Even better would be a GPU implementation, but I do not see anything about that yet.

I might implement experimental support for it in the converter. Should not be too hard to do.

**Comment by heinezen** [comment]
Closed via #1327
