### ISSUE TITLE
open_memstream() unsupported on Windows

### ISSUE THREAD

**Issue by heinezen** [SFTtech/openage#1306]
We currently rely on the POSIX function `open_memstream()` to get a file pointer for an in-memory buffer during PNG conversion. `libpng`'s standard output path asks for a `FILE *` stream, so we cannot just pass it a `char *`. Our reason for handling the PNG creation in-memory is that we want to

1. let Python handle the file writing and directory creation **and**
2. if PNG optimization is used, not have to write every optimization trial to the filesystem as that's slow

Unfortunately, Windows does not support `open_memstream()` and therefore we have to do something different. I think the easiest way to handle this would be to implement a custom PNG write function that writes to a buffer and pass it to `libpng` with `png_set_write_fn()` ([described here](https://refspecs.linuxbase.org/LSB_3.1.0/LSB-Desktop-generic/LSB-Desktop-generic/libpng12.png.set.write.fn.1.html)).

**Comment by duanqn** [comment]
Maybe this could help?
https://stackoverflow.com/questions/12249610/c-create-file-in-memory

**Comment by heinezen** [comment]
@duanqn Thx, I think I even considered this when initially wrote the png exporter. Though I would ideally not rely on "dirty" hacks, especially if they are only made for one platform. They tend to break a lot more often and in unexpected ways :D 

However, it's better than having this issue unresolved, so if anyone builds a solution around this, that's also OK.

**Comment by duanqn** [comment]
I may be able to create a `open_memstream()` C++ function that works on both Windows and Linux. But I don't know how you can import them like the current `posix.stdio` package. Can you write the glue code between C++ and Python?

**Comment by heinezen** [comment]
@duanqn Sounds great! Of course, I will assist you with the Cython importing. It's mostly an explicit import of functions from a C/C++ header file, as shown here:

https://github.com/SFTtech/openage/blob/afbb624518e360bb96835badfa2c37979ff2e7b8/openage/convert/service/export/png/libpng.pxd#L3-L8

Cython also [has a tutorial for that](https://cython.readthedocs.io/en/latest/src/userguide/external_C_code.html) if you want to try it yourself.

**Comment by duanqn** [comment]
@heinezen I'll start working on that then. Also, I read that Mac OS does not have `open_memstream()` either, but I don't have a Mac device to confirm that.

**Comment by heinezen** [comment]
macOS should have `open_memstream()` as it implements the POSIX standard (at least I would be surprised if it didn't).

**Comment by duanqn** [comment]
I can write a fake "open_memstream" following the SO guide, but you won't be able to call `free` on the returned pointer. Is it OK if I return a null pointer, and you perform the check before `free`ing it?

**Comment by heinezen** [comment]
Should be okay I think.

**Comment by Hywan** [comment]
macOS supports `open_memstream`. I'm reading this issue because Windows doesn't, but I use this function on macOS with no issue.
