### ISSUE TITLE
Convert sounds with singlefile converter

### ISSUE THREAD

**Issue by heinezen** [SFTtech/openage#1308]
**Required skills**: Python, maybe Cython

**Difficulty**: Easy

Our exporter for single media files can only be used for graphics files (SLP, SMP or SMX) currently. It would be great, if we could extend it to support outputting sounds as well. This functionality can reuse the internal opus conversion service that is already implemented.

**Further reading**:

* [Singlefile converter code](https://github.com/SFTtech/openage/blob/master/openage/convert/tool/singlefile.py)
* [Converter architecture](https://github.com/SFTtech/openage/blob/master/doc/code/converter/architecture_overview.md)
* [Converter workflow](https://github.com/SFTtech/openage/blob/master/doc/code/converter/workflow.md)

**Comment by drs-11** [comment]
On it!

**Comment by heinezen** [comment]
Nice!
