### ISSUE TITLE
Debian package

### ISSUE THREAD

**Issue by okias** [SFTtech/openage#1322]
Hello,

would be nice to have classic Debian package, is there someone with at least light experiences with [Salsa](https://salsa.debian.org/public), who could prepare something eventually included by Debian?

Thank you

Ref https://github.com/SFTtech/openage/issues/94

**Comment by TheJJ** [comment]
openage is a classic cmake-built package, and just has some dependencies. so it shouldn't be hard to create a debian package :)

**Comment by ChipmunkV** [comment]
Oh, I remember...

There was a Debian packaging script: https://github.com/SFTtech/openage-debian/pull/1

I think I used the "Debian Maintainers' Guide" (the scary one).

**Comment by okias** [comment]
Nice! If anyone will try to move it to salsa.debian.org/ setup CI and make lintian happy, I'm offering help with my all (thou beginner) knowledge to get it into best shape. :+1:

**Comment by CountOmega** [comment]
I created a debian build directory, but my rules files doesn't pass the configure options. rules file:

```
#!/usr/bin/make -f

export DEB_BUILD_MAINT_OPTIONS = hardening=+all



override_dh_auto_configure:
	dh_auto_configure -- \
		--prefix=/usr/local \
		--compiler=gcc \
		--mode=release
	
%:
	dh $@  
```
What am I missing here?

**Comment by TheJJ** [comment]
Hi! openage is actually a cmake project, the `configure` and `make` files are there only for convenience. You should thus build and package it like one does with cmake.

**Comment by TheJJ** [comment]
We can think about moving the debian folder to the main repo once we're satisfied enough with the procedure.

**Comment by CountOmega** [comment]
> We have a repo for debian-packaging already: https://github.com/SFTtech/openage-debian

ok, didn't know that.

**Comment by CountOmega** [comment]
> If you find improvements, please submit them there :)

Should I just send a MR? Also, should libopenage be a separate packageẞ

**Comment by TheJJ** [comment]
Yes, please send pull requests! I don't think it is important currently to split out libopenage since the api is definitely not stable, and it is tightly coupled with the rest of the codebase. But if it's easy and useful to do, why not :)
