### ISSUE TITLE
Can't unzip installer

### ISSUE THREAD

**Issue by TheNamesGregoryAndounuts** [SFTtech/openage#1335]
Hi, I just found this game and wanted to give it a try but when I download it from here (https://bintray.com/simonsan/openage-packages/openage-windows-nightly/0.4.0) an un-zip the installer I find that windows tells me that it can't open the file due to it being invalid. Is there any place I can get the game where I can successfully un-zip it?

**Comment by heinezen** [comment]
Unzipping works under Linux, so it's probably not the file making problems. I guess you can try another archive software like 7-zip (https://www.7-zip.org/) and see if that works.

**Comment by TheJJ** [comment]
If you need further help, please notify us (or join the chat).
