### ISSUE TITLE
Something that looks like a typo

### ISSUE THREAD

**Issue by duanqn** [SFTtech/openage#1337]
In openage/default_dirs.py, line 84 (of commit b303555ec90d4c)

Judging from the context, it seems that the variable `env_var` should be `env_vars`.

If anyone can confirm this I can fix it.

**Comment by heinezen** [comment]
I don't see the line in the commit you linked, but I think you are right when looking at the line in HEAD: 

https://github.com/SFTtech/openage/blob/master/openage/default_dirs.py#L84

So it looks like it needs fixing.
