### ISSUE TITLE
Request future releases is bin format too. 

### ISSUE THREAD

**Issue by yaaaaa** [SFTtech/openage#1354]

**Comment by TobiasFP** [comment]
Could you please elaborate?, i do not understand the request.

**Comment by yaaaaa** [comment]
I mean it would be nice to give interested people the ability to run releases without having to build them.

**Comment by TobiasFP** [comment]
Ok. Are you missing anything in particular in these packages?
https://openage.sft.mx/

**Comment by yaaaaa** [comment]
Oh, yes, closing it now.
