### ISSUE TITLE
The engine should allow arbitrary size textures and zoom levels

### ISSUE THREAD

**Issue by franciscod** [SFTtech/openage#136]
It won't be fun if we have 4k displays and all our assets are the same resolution as the original AoE

**Comment by TheJJ** [comment]
@rkreis should be careful for the #178 implementation :wink: 
i remember him being aware of the scaling problems though.

**Comment by franciscod** [comment]
this would be fixed by #287 by using 3d textures, right?

**Comment by TheJJ** [comment]
No, the 3d textures change nothing but the storage arrangement. My renderer will support arbitary zoom levels, the texture size is limited by hardware though.

**Comment by franciscod** [comment]
okay but if the AoE HD have 500x500px 3d textures and somebody wants to use a 2000x2000 texture it will work right? (assuming fits in RAM, VRAM, and hardware is fine)

**Comment by TheJJ** [comment]
Then I don't know what you mean by 3d-texture. But yes, it will work, at least in theory.

**Comment by franciscod** [comment]
i mean square textures that get morphed into rhombus, like the HD version does. closing this, then!
