### ISSUE TITLE
Speed up converter texture packing with Cython

### ISSUE THREAD

**Issue by heinezen** [SFTtech/openage#1371]
**Required skills:** Cython

**Difficulty:** Medium

Animation frames from AoE2 graphics files are packed into a texture atlas by the openage converter. We use [bin packing](https://en.wikipedia.org/wiki/Bin_packing_problem) to find the optimal arrangement (= smallest atlas dimensions) of the frames in the atlas. Bin packing becomes computationally intensive if a lot of frames are packed (looking at you Definitive Edition), so we want to optimize the algorithm as much as possible.

The goal of this issue is to speed up the bin packing implemented [here](https://github.com/SFTtech/openage/blob/master/openage/convert/service/export/png/binpack.pyx) using [Cython](http://docs.cython.org/en/latest/src/quickstart/overview.html). The most important methods to cythonize are `pack()` and `factor()`, since they are responsible for the packing logic. Ideally, these functions should contain as little Python overhead as possible.

Additional optimization might be possible such as:

- [ ] Currently `pack()` gets passed a list of frame objects, but technically only *width*, *height* and *index* of a frame are needed.
- [ ] Most of the games have a fixed number of frames per animation (e.g. 50 frames for a unit animation in AoC). These could be hardcoded as lookups into `factor()`
- [ ] [`texture_merge.pyx`](https://github.com/SFTtech/openage/blob/master/openage/convert/processor/export/texture_merge.pyx), the function initiating the binpacking, could also use optimization for merging the individual frames into the atlas using the packer settings.

You can test your changes with the [singlefile media converter](https://github.com/SFTtech/openage/blob/master/doc/convert/convert_single_file.md).

**Further Reading**

* [Binpack code](https://github.com/SFTtech/openage/blob/master/openage/convert/service/export/png/binpack.pyx)
* [Converter architecture](https://github.com/SFTtech/openage/blob/master/doc/code/converter/architecture_overview.md)
* [Converter workflow](https://github.com/SFTtech/openage/blob/master/doc/code/converter/workflow.md)

**Comment by fabiobarkoski** [comment]
Looking in the [`binpack.pyx`](https://github.com/SFTtech/openage/commits/master/openage/convert/service/export/png/binpack.pyx) history, seems that the converter already received some speed up improvement

**Comment by heinezen** [comment]
@fabiobarkoski It has been converted to Cython but none of the points in the ssue have been solved completely afaik.

**Comment by fabiobarkoski** [comment]
Can I try to work on it? But I'll need some guidance :)

**Comment by heinezen** [comment]
You absolutely can :) Although it might be a bit harder than *medium* difficulty if you don't know Cython. Just saying :D
