### ISSUE TITLE
Ubuntu 20.04 cloud build failure

### ISSUE THREAD

**Issue by duanqn** [SFTtech/openage#1399]
Hi folks,
Can someone help me diagnose this build failure? https://github.com/duanqn/openage/runs/3353050745?check_suite_focus=true
The CI workflow is here: https://github.com/duanqn/openage/actions/runs/1140126626/workflow

**Comment by duanqn** [comment]
Seems like the error is in Cython / C++ interaction part.

**Comment by TheJJ** [comment]
First error is
```
/mnt/openage/.bin/g++-release-Oauto-sanitize-none/openage/convert/processor/export/texture_merge.cpp:1469:62: error: expected identifier before '*' token
 1469 |   __pyx_ctuple_unsigned__space_int__and_unsigned__space_int (*pos)(struct __pyx_obj_7openage_7convert_7service_6export_3png_7binpack_Packer *, PyObject *);
      |                                                              ^
/mnt/openage/.bin/g++-release-Oauto-sanitize-none/openage/convert/processor/export/texture_merge.cpp:1469:154: error: ISO C++ forbids declaration of '__pyx_ctuple_unsigned__space_int__and_unsigned__space_int' with no type [-fpermissive]
 1469 |   __pyx_ctuple_unsigned__space_int__and_unsigned__space_int (*pos)(struct __pyx_obj_7openage_7convert_7service_6export_3png_7binpack_Packer *, PyObject *);
      |                                                                                                                                                          ^
/mnt/openage/.bin/g++-release-Oauto-sanitize-none/openage/convert/processor/export/texture_merge.cpp:1469:154: error: '__pyx_ctuple_unsigned__space_int__and_unsigned__space_int' declared as function returning a function
```

It used Cython `0.29.14`, which is quite old, but it looks like generated code that the cpp compiler doesn't like. My first attempt would be to update cython...

I've updated our kevin image to latest debian sid, which has cython `0.29.21`.

**Comment by heinezen** [comment]
I'll try tro handle it today. Looks like we need to bump some version numbers.

**Comment by duanqn** [comment]
@TheJJ  @heinezen  Thanks. I'll try upgrading the Cython version. I was borrowing the docker setup script from #1357 .

What are your opinions about this? Do you think a CI pipeline with GitHub Actions could solve the problem of setting up dev environments? People can push their code to GitHub and trigger a build on their branch, and the pipeline will publish the build artifacts, maybe a .deb package for Ubuntu. Then they can download it and use it on their computers.

I think GitHub Actions are free for public repos, and the content of the pipeline is directly maintained in the git repository so everyone can help maintain the build.

**Comment by duanqn** [comment]
https://github.com/duanqn/openage/runs/3353050745?check_suite_focus=true
I tried upgrading Cython to 0.29.24, but it didn't get better.
Also found the new nyan code breaks the build. Does it require C++ 20? Filed an issue at SFTTech/nyan#93 .

**Comment by duanqn** [comment]
Created a PR #1400 to address the pxdgen issue when I upgrade python package versions.

**Comment by heinezen** [comment]
PR is merged, so I assume it's fixed?

**Comment by duanqn** [comment]
Yeah the problem disappears in Ubuntu 21.04 and gcc 11. So I guess this can be closed.
