### ISSUE TITLE
Compilation issues (Ubuntu 20.04)

### ISSUE THREAD

**Issue by AvidDrawer** [SFTtech/openage#1413]
I'm seeing undefined type errors when I run make in bin/openage/convert/processor/export/texture_merge.cpp

The following symbol is undefined- **__pyx_ctuple_unsigned__space_int__and_unsigned__space_int**

I couldn't find an include file that has the definition but did find it in this source file- bin/openage/convert/service/export/png/binpack.cpp

However this file is not listed as a dependency in the Makefile when generating the object for texture_merge.cpp.

Am I missing something here?

**Comment by heinezen** [comment]
This file is generated by Cython. It's generated from the `texture_merge.pyx` file in the source folder.

What cython version did you use?

**Comment by AvidDrawer** [comment]
Cython version- 0.29.14

Will have a look at the python file later today and will update if I see something.

**Comment by TheJJ** [comment]
Please try to use a newer Cython, this looks like a pyx code generation issue.

**Comment by duanqn** [comment]
I saw this error before, but I solved it by upgrading to Ubuntu 21.04 and gcc-11.

**Comment by AvidDrawer** [comment]
@duanqn As you suggested, upgrading to 21.04 helped. I'm not sure if it was the upgrade alone that fixed it though. I removed the ./bin directory to run make on a clean tree. 

Sadly, I can't run steam on virtual box. Gotta get another hard drive before I can start toying around with the repo (the windows dependency installation is a terrible experience, even with vcpkg).

Thanks for the assistance.

**Comment by duanqn** [comment]
@AvidDrawer I'm working on some build pipelines with GitHub Actions. You might want to take a look at this successful build on Windows: https://github.com/duanqn/openage/actions/runs/1272716573.
For Ubuntu, I have some successful builds with gcc-10, e.g. https://github.com/duanqn/openage/actions/runs/1234090779. I'm still working on some build issues with gcc-11.
I exported the build artifacts. You can download them if you find them helpful.
