### ISSUE TITLE
Display conversion progress

### ISSUE THREAD

**Issue by heinezen** [SFTtech/openage#1423]
**Required skills:** Python

**Difficulty:** Easy

For the initial asset conversion, openage provides textual output to signal which stage of conversion has been reached. The output usually looks like this:

```
INFO [py] converting metadata
INFO [py] [0] palette
INFO [py] [1] empires.dat
INFO [py] Starting conversion...
INFO [py] Extracting Genie data...
INFO [py] Creating API-like objects...
INFO [py] Linking API-like objects...
INFO [py] Generating auxiliary objects...
INFO [py] Creating nyan objects...
INFO [py] Creating requests for media export...
INFO [py] Starting export...
INFO [py] Dumping info file...
INFO [py] Dumping data files...
INFO [py] Exporting media files...
INFO [py] Dumping metadata files...
INFO [py] [2] player color palette
INFO [py] [3] terminal color palette
INFO [py] [4] game specification files
INFO [py] asset conversion complete; asset version: 7
```

However, some of these stages can take a while to complete. For example, the whole `Exporting media files...` stage can take up to 20 minutes. For these stages, it would be nice to have more dynamic updates in form of a progress bar. This would also give much more feedback to users on what's being done at the moment.

The stages that would benefit the most from a progress bar are:

- [ ] `empires.dat` file parsing ([See code](https://github.com/SFTtech/openage/blob/master/openage/convert/entity_object/conversion/genie_structure.py#L61))
- [ ] `Creating nyan objects...` ([See code](https://github.com/SFTtech/openage/blob/master/openage/convert/processor/conversion/aoc/nyan_subprocessor.py#L71))
- [ ] `Exporting media files...`  ([See code](https://github.com/SFTtech/openage/blob/master/openage/convert/processor/export/media_exporter.py#L22))

We provide a formatter for the progress bar in our tools: https://github.com/SFTtech/openage/blob/master/openage/util/strings.py#L103

**Further reading**:

* [Converter architecture](https://github.com/SFTtech/openage/blob/master/doc/code/converter/architecture_overview.md)
* [Converter workflow](https://github.com/SFTtech/openage/blob/master/doc/code/converter/workflow.md)

**Comment by jochenrui** [comment]
hi there, can I try this for my first issue ? :)

**Comment by heinezen** [comment]
@jochenrui Sure, contribution is welcome :)

If you have any questions not answered by the issue, you can also come by in our chatroom (see the project readme for infos).

**Comment by jochenrui** [comment]
@heinezen have you seen this error before during configuration? I followed the instructions on https://github.com/SFTtech/openage/blob/master/doc/build_instructions/macos.md

```

CMake Warning at buildsystem/HandleCXXOptions.cmake:75 (message):
  GNU gold linker isn't available, using the default system linker.
Call Stack (most recent call first):
  buildsystem/HandleCXXOptions.cmake:107 (try_enable_gold_linker)
  CMakeLists.txt:172 (include)




The compiler doesn't support required C++20 features:
  * Concepts
  * Default comparisons
The following versions support these features:
  * clang++ >= 10
  * g++ >= 10
  * Microsoft Visual Studio 2019 >= 16.8
Please upgrade your compiler to build openage.


CMake Error at buildsystem/CheckCompilerFeatures.cmake:57 (message):
  aborting
Call Stack (most recent call first):
  CMakeLists.txt:173 (include)
```

**Comment by heinezen** [comment]
@jochenrui I think the macOS clang compiler doesn't support C++20 features yet. Can you try with gcc?

**Comment by jochenrui** [comment]
@heinezen sorry about that. I'll try to get it running on macos first, maybe this would make for a good addition to the build_instructions file for macos :D

**Comment by heinezen** [comment]
@jochenrui Well, that's fine by me then :)

**Comment by TobiasFP** [comment]
If you get stuck or need inspiration, there has been made a dockerfile that uses an Ubuntu image to build the system, which could be of use:
https://github.com/SFTtech/openage/pull/1357

**Comment by duanqn** [comment]
@jochenrui If you want to try Windows, I have a successful build here: https://github.com/SFTtech/openage/runs/3883281983.
You can look at [the YAML file](https://github.com/SFTtech/openage/blob/master/.github/workflows/windows-server-2019.yml) for the exact steps.

**Comment by maassen1** [comment]
Does this issue still need to be resolved?

**Comment by heinezen** [comment]
@maassen1 Yes, it's still not implemented.
