### ISSUE TITLE
[Windows 10] Cannot build the project, python installation not recognized

### ISSUE THREAD

**Issue by karakune** [SFTtech/openage#1455]
I'm trying to build OpenAge on Windows x64. I can't for the life of me manage to make the python finder work. I keep getting this error, even after reinstalling python multiple times.
![image](https://user-images.githubusercontent.com/20135188/147713092-f307415a-d734-4ae3-9723-cd3a392877fc.png)

So first I tried with Python3.7, since it was installed beforehand on my computer. When that didn't work, I downloaded Python 3.10 and uninstalled 3.7. Again, didn't work so I reinstalled 3.10 like twice, trying the same commands each time. Finally, I uninstalled every python version I ever had on my computer and did a clean install of 3.6, still didn't work.

The testing process each time was
->Install version
->open git bash at the root of python version
->pip install cython numpy lz4 toml pillow pygments pyreadline Jinja2 (I pasted that command from your openage/doc/build_instructions/windows_msvc.md)
->open a second git bash, this time at the root of the OpenAge project
->cd build
->cmake -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake .. -G "Visual Studio 16 2019" -A x64 -DDOWNLOAD_NYAN=YES -DFLEX_EXECUTABLE=C:/vcpkg/downloads/tools/winflexbison/0a14154bff-a8cf65db07 -DPYTHON_DIR="C:\vcpkg\downloads\tools\python\python-3.6.0-x64" (changing for the python version I had each time)

To install each python version, I downloaded the executable installer from https://www.python.org/downloads/release/python-360/

**Comment by duanqn** [comment]
1. Openage currently does not support Python 3.10. This is a known issue. #1438 
2. You can find the successful build commands here: https://github.com/SFTtech/openage/blob/master/.github/workflows/windows-server-2019.yml
3. From my experience, the most likely reason for your failure is that you didn't use `-DCMAKE_TRY_COMPILE_CONFIGURATION=Release`. Openage uses a `try_compile` to determine whether the python installation is "suitable". Without this option, it will try to link with debug libraries from Python, which never worked on my Windows computer :/ .


So I think you can lower Python version to 3.9 (this version has been tested) and supply `-DCMAKE_TRY_COMPILE_CONFIGURATION=Release` on the cmake command line. Good luck!

**Comment by heinezen** [comment]
This should work now as we fixed the Python 3.10 issues in https://github.com/SFTtech/openage/pull/1462

Can you retest?

**Comment by kangqiwang** [comment]
@heinezen Thanks for your updated. It work for me :smile:

**Comment by heinezen** [comment]
@kangqiwang Thanks for checking :)
