### ISSUE TITLE
Unable to build on Arch Linux (Manjaro KDE)

### ISSUE THREAD

**Issue by sebukoleth** [SFTtech/openage#1460]
Build fails:

```
-- Found Python3: /usr/bin/python3.10 (found suitable exact version "3.10.1") found components: Interpreter Development NumPy Development.Module Development.Embed 
CMake Warning at buildsystem/modules/FindPython.cmake:68 (message):
  !! No suitable Python interpreter was found !!

Call Stack (most recent call first):
  buildsystem/HandlePythonOptions.cmake:6 (find_package)
  CMakeLists.txt:175 (include)


CMake Warning at buildsystem/modules/FindPython.cmake:69 (message):
  We need a Python interpreter >= 3.10 that is shipped with libpython and
  header files.

Call Stack (most recent call first):
  buildsystem/HandlePythonOptions.cmake:6 (find_package)
  CMakeLists.txt:175 (include)


CMake Warning at buildsystem/modules/FindPython.cmake:70 (message):
  Specify the directory to your own with -DPYTHON_DIR=/dir/of/executable

  

  

Call Stack (most recent call first):
  buildsystem/HandlePythonOptions.cmake:6 (find_package)
  CMakeLists.txt:175 (include)


CMake Error at buildsystem/modules/FindPython.cmake:107 (message):
  failed:

   -c 'import cython; print(cython.__version__)'

Call Stack (most recent call first):
  buildsystem/modules/FindCython.cmake:14 (py_exec)
  buildsystem/HandlePythonOptions.cmake:7 (find_package)
  CMakeLists.txt:175 (include)


-- Configuring incomplete, errors occurred!
```

Is this related to dot version of Python?

Tried
- pip install cython
- pip3 install cython

Both report that cython is already installed.

**Comment by LinuxDonald** [comment]
Have you cpython installed?

**Comment by heinezen** [comment]
Probably related to this one: https://github.com/SFTtech/openage/issues/1438

**Comment by sebukoleth** [comment]
@heinezen , possible

@LinuxDonald Yes, cython is installed.

`which cython
/usr/bin/cython
`

**Comment by Yaraslaut** [comment]
I have the same issue.
The problem is that even though find_package was able to find Python, but further check of python linking does not see Python3_INCLUDE_DIR, one of the possible solution is to trust find_package in the case when try_compile failing and use variables given by find_package routine

**Comment by Yaraslaut** [comment]
@heinezen you are right, the issue is that minor version does not converted to hex.
I have not found an easy way to do it in cmake, but it can be done in FindPython_test.cpp

**Comment by sarcXD** [comment]
@heinezen welp, glad I'm not the only one coming across this. Luckily I found a relatively clean and arguably better and cleaner way of setting our ${PYTHON_MIN_VERSION_HEX} variable. I'll outline the relatively simple fix here.
Firstly, this is how cpython does it in their header library
```
#define PY_VERSION_HEX ((PY_MAJOR_VERSION << 24) | \
                        (PY_MINOR_VERSION << 16) | \
                        (PY_MICRO_VERSION <<  8) | \
                        (PY_RELEASE_LEVEL <<  4) | \
                        (PY_RELEASE_SERIAL << 0))
``` 
Now, All we need to do is shift the major version up by 24 bits, and minor version up by 16
Current method:
```
set(PYTHON_MIN_VERSION_HEX "0x0${Python3_VERSION_MAJOR}0${Python3_VERSION_MINOR}0000")
```
The fix I made (making, will send a PR after this)
```
math(EXPR BIT_SHIFT_HEX "${Python3_VERSION_MAJOR} << 24 | ${Python3_VERSION_MINOR} << 16" OUTPUT_FORMAT HEXADECIMAL)
set(PYTHON_MIN_VERSION_HEX "${BIT_SHIFT_HEX}")
```
see [cmath page for math that allows c like bit manipulation operations](https://cmake.org/cmake/help/latest/command/math.html)
That fixes it basically.
