### ISSUE TITLE
Converting assets from AOE2DE fails 

### ISSUE THREAD

**Issue by sservaes** [SFTtech/openage#1470]
The following exception occurs when converting assets from AOE2DE (installed through steamcmd):
`Exception: Media at path [Directory(/home/user/Steam/steamapps/AOE2DE)]:resources/_common/drs/gamedata_x1 could not be found`

When browsing to this specific folder, the folder that is present there is gamedata_x2.

OS: Ubuntu 21.10

**Comment by heinezen** [comment]
They probably changed few things for an upcoming DLC... I'll look into it.

Until then, you can try to change the filename used for data conversion in `cfg/converter/games/game_editions.toml` (by editing the AOE2DE entry in line 131) and see if that helps :)
