### ISSUE TITLE
build failing on Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by kangqiwang** [SFTtech/openage#1474]
## Bug Report

**Current Behaviour**

follow /[build_instructions](https://github.com/SFTtech/openage/tree/master/doc/build_instructions)/ubuntu.md , but failed.

due to unsuccessfully install libsdl2-dev. there nothing we can do at moment on Ubuntu 22.04

**Environment**
- Ubuntu version(s): [22.04 LTS]

**Possible Solution**
keep eye on the Ubuntu 22.04 LTS updating, it should be ubuntu issue, but it will certainly effect on our deployment 

**Additional context**
this [link](https://discourse.libsdl.org/t/ubuntu-22-04-libsdl2-dev-linked-against-wrong-libsndio/35547/3) may fix the issue.
this [situation](https://stackoverflow.com/questions/72131102/installing-libsdl2-dev-crashed-the-ubuntu-22-04-lts) is similar with mine

**Comment by kangqiwang** [comment]
## potential solution

following this [link](https://ubuntuforums.org/showthread.php?t=2465270), I knew this is Ubuntu 21.04, but it happened exactly what I have been through. I will update everything then install libsdl2-dev

**Comment by duanqn** [comment]
Is this resolved? We have a CI pipeline for 22.04 now.

**Comment by TheJJ** [comment]
i guess so. and it's up to ubuntu to push a fix for this in their repos :)

**Comment by kangqiwang** [comment]
Yes, It works for me now 😄
