### ISSUE TITLE
(Ubuntu 22.10) Configure script error on release 0.4.1

### ISSUE THREAD

**Issue by AndreasEike** [SFTtech/openage#1491]
I'm having an issue running the configure script on release 0.4.1. After running the command "./configure --mode=release --download-nyan --prefix=./../../../game", I get the following error:

```
CMake Error at buildsystem/modules/FindPython.cmake:94 (message):
  failed:

   -c 'import cython; print(cython.__version__)'

Call Stack (most recent call first):
  buildsystem/modules/FindCython.cmake:14 (py_exec)
  buildsystem/HandlePythonOptions.cmake:7 (find_package)
  CMakeLists.txt:169 (include)


-- Configuring incomplete, errors occurred!
```

Here is the full output from the file "CMakeOutput.log":
[CMakeOutput (copy).log](https://github.com/SFTtech/openage/files/10392515/CMakeOutput.copy.log)

**Comment by AndreasEike** [comment]
Hey, thanks for the quick reply! I understand, we are doing a reinforcement learning project with openage, are there any of the old versions that are working?

As for the cython version, I get the following output in my python console:

<img width="328" alt="image" src="https://user-images.githubusercontent.com/46325452/211816212-8a8554aa-c1a2-4b12-8ee1-c4c42b05caac.png">

**Comment by TheJJ** [comment]
ok, since that works we need to figure out why `buildsystem/modules/FindPython.cmake:94` fails doing the same thing.
the 0.4.1 would be your best bet then - but beware that there's basically zero API functionality for your RL project :)

and you need to fix the build in your repo manually since earlier versions probably won't work, too.

**Comment by TheJJ** [comment]
if you have further questions, feel free to contact us also in the chatroom
