### ISSUE TITLE
Fixed point math constants

### ISSUE THREAD

**Issue by heinezen** [SFTtech/openage#1544]
**Required Skills:** C++

**Difficulty**: Easy

It would be nice to have common math constants like `pi` defined using our fixed-point implementation, so that they can be used in fixed-point calculations with deterministic outcome. Floating point constants are already implemented [here](https://github.com/SFTtech/openage/blob/master/libopenage/util/math_constants.h).

Tasks:
- [ ] Define existing math constants also as fixed point

**Further Reading**

- [openage math constants](https://github.com/SFTtech/openage/blob/master/libopenage/util/math_constants.h)
- [fpm libary math constants](https://github.com/MikeLankamp/fpm/blob/22bab8ff3abe0acfb00bc20853ed6b74e9959fd7/include/fpm/fixed.hpp#L116)

**Comment by ArcXeon** [comment]
I am interested on working on this issue. Can you please assign it to me?

**Comment by AyiStar** [comment]
@heinezen I opened a WIP PR for adding two fixed point constants, and would be happy to discuss about the implementation and add more constants if everything is ok.

**Comment by heinezen** [comment]
@AyiStar I've looked at it yesterday and no complaints so far :)
