### ISSUE TITLE
CLI parameters for window settings

### ISSUE THREAD

**Issue by heinezen** [SFTtech/openage#1546]
**Required Skills:** Python, some C++

**Difficulty**: Easy

Several window parameters could be set via the CLI on startup. Examples for these parameters include:

- window size (height x width)
- vsync
- fullscreen/borderless/windowed

Most of the parameters are already supported by the `renderer::Window` class. All we have to do is pass them through from the Python CLI.

Tasks:
- [ ] Start parameters have to be defined in Python for start modes `main` and `game`
- [ ] Pass parameters to C++ invocation `main_arguments` struct
- [ ] in C++, pass relevant parameters to presenter/renderer subsystem

**Further Reading**

- [openage renderer documentation](https://github.com/SFTtech/openage/blob/master/doc/code/renderer/README.md)

**Comment by stoyanov-kaloyan** [comment]
Hi! I would like to work on this issue. Can you please assign it to me?

**Comment by heinezen** [comment]
@stoyanov-kaloyan Great :) I've assigned you just now.

**Comment by RaulGalvez288** [comment]
Hi, I want to contribute to this project and I figured this issue would be a great place to start. Can I be assigned to it?

**Comment by TheJJ** [comment]
done - but generally this is not needed to work on something :) usually, just submit the pull request
