### ISSUE TITLE
openage game: error: the following arguments are required: --modpacks

### ISSUE THREAD

**Issue by yangzhangstl** [SFTtech/openage#1571]
Hi guys：

Running the program reported an error with "openage game: error: the following arguments are required: --modpacks".  Actually, I have followed the official instructions and  converted the official source assets via python3 -m openage convert --force --source-dir /path/to/game/install command. 

Currently using ARM architecture Macbook M1 Pro chip, macOS Ventrua system. Can you please tell me the reason why the program is not starting? Currently the converted official asset data is saved in the OpenAge/Asset/Converted/de2_base folder. Thanks!

<img width="611" alt="2023-10-10 10 22 10" src="https://github.com/SFTtech/openage/assets/88226594/50329184-0474-4dfe-92af-93976b545b40">

**Comment by yangzhangstl** [comment]
This program built for i386-apple-darwin11.3.0
Report bugs to <bug-make@gnu.org>
<img width="671" alt="2023-10-10 11 10 42" src="https://github.com/SFTtech/openage/assets/88226594/6f0a71f5-b8d2-4117-a71e-2d4b7cd473ff">

**Comment by heinezen** [comment]
Thanks for reporting. `make run` looks broken right now, so I'm going to fix that soon.

As an alternative, you can use 

```bash
cd bin && ./run game --modpacks hd_base
```

for startup.

**Comment by yangzhangstl** [comment]
First of all thank you very much for your help, by entering the new command you suggested "cd bin && . /run game --modpacks hd_base", the terminal gave back the new error code as shown. Hope to get your guidance and help soon, much appreciated!
<img width="818" alt="2023-10-10 18 30 29" src="https://github.com/SFTtech/openage/assets/88226594/4fd25940-c09c-41e8-bba7-2562a28348ee">

**Comment by yangzhangstl** [comment]
<img width="655" alt="1" src="https://github.com/SFTtech/openage/assets/88226594/23309684-dd95-4368-a5c2-b298940bdd04">
<img width="657" alt="2" src="https://github.com/SFTtech/openage/assets/88226594/9b86e38c-cd76-44e9-8a41-99aed3fa0100">
