### ISSUE TITLE
Running Error on Mac osx 13.4(Macbook M1 Pro ARM architecture)

### ISSUE THREAD

**Issue by yangzhangstl** [SFTtech/openage#1572]
This program built for i386-apple-darwin11.3.0 Report bugs to <bug-make@gnu.org>

<img width="671" alt="2023-10-10 11 10 42" src="https://github.com/SFTtech/openage/assets/88226594/ad516409-cca8-4c27-a89a-4f013c01e8ac">

**Comment by yangzhangstl** [comment]
This program built for i386-apple-darwin11.3.0 Report bugs to <bug-make@gnu.org>

**Comment by heinezen** [comment]
Duplicate of https://github.com/SFTtech/openage/issues/1572
