### ISSUE TITLE
Slowly implement game_main mess as sane engine features

### ISSUE THREAD

**Issue by mic-e** [SFTtech/openage#159]
The `Game` object should be initialized directly from `int main()`, with `--no-video` and `--no-audio` arguments.
##

**Comment by franciscod** [comment]
refactoring, yummy!

**Comment by franciscod** [comment]
progress: https://github.com/franciscod/openage/tree/gamemain-engine-merge

**Comment by franciscod** [comment]
I'm bringing some comments from the now closed #246, which naively merged both classes:

>hm, having a look at it, it doesn't seem like a good idea merging the utterly broken GameMain with the hopefully clean Engine. The better way, as @mic-e hopefully meant in #159, is to migrate all the contents of gamemain to the engine class in a sane way.
>
>All features instanced and "tested" in GameMain should become sane engine features someday. Just merging the contents directly doesn't address the actual problem.
>
> *@TheJJ [said here](https://github.com/SFTtech/openage/pull/246#issuecomment-77269123)*

>Seperation does make some sense. Think of the game menus being rendered before a game is started. The engine is always running to handle any kind of rendering (including ui / menus) even without a game, allowing you to start one game quit back to the main menu and then start a new game.
>
> *@Jon0 [said here](https://github.com/SFTtech/openage/pull/246#issuecomment-77271370)*

**Comment by TheJJ** [comment]
This was long done!
