### ISSUE TITLE
Windows Build: Python Command Requiring --modpacks Argument

### ISSUE THREAD

**Issue by brett-hamilton** [SFTtech/openage#1623]
## System Info
- Windows 11
- Python version 3.12.2
---
Hello, I have been following the Windows build process from `doc/build_instructions/windows_msvc.md`. I have completed the steps down to the first Python command. When I run `py -m openage game` from the `<openage directory>\build\` path, I receive the following message:
```
usage: openage game [-h] [--verbose] [--quiet] [--trap-exceptions] [--devmode | --no-devmode] [--asset-dir ASSET_DIR]
                    [--cfg-dir CFG_DIR] [--gl-debug] [--headless] --modpacks MODPACKS [MODPACKS ...]
openage game: error: the following arguments are required: --modpacks
```
Does this message indicate I missed a step? Thank you for your help!

**Comment by brett-hamilton** [comment]
Follow-up: it seems like this argument `--modpacks` is being required in the file `<openage directory>\build\openage\game\main.py` lines 29-31. Thanks!

**Comment by heinezen** [comment]
Yes, it is required because `openage game` is used to immediaely jump into the game. You can use `openage main` for a more beginner-friendly workflow that lets you convert assets and then start a game.

**Comment by brett-hamilton** [comment]
@heinezen I see, I'll use `openage main` first then. Thank you!
