### ISSUE TITLE
Implement job aborting to allow execution cancelation

### ISSUE THREAD

**Issue by blucoat** [SFTtech/openage#163]
While gamedata is being loaded, it's impossible to close the window without resorting to SIGKILL.  This is caused by the job manager waiting for all jobs to finish when `JobManager::stop()` is called.  The gamedata loading job should periodically check whether `JobManager::is_running` is set, so it can return or throw an exception if it finds it has been stopped prematurely.

**Comment by fr3akout** [comment]
I am currently adding some features to the job manager and will consider aborting jobs.

**Comment by TheJJ** [comment]
this feature is now present: it was merged with #192.

**Comment by mic-e** [comment]
Note, however, that one of the loading jobs still must be updated to support aborting.
