### ISSUE TITLE
How to run in windows

### ISSUE THREAD

**Issue by moozen-cn** [SFTtech/openage#1669]
Compile:
```
cmake -DCMAKE_TOOLCHAIN_FILE="D:\Developer\vcpkg\scripts\buildsystems\vcpkg.cmake" -DDOWNLOAD_NYAN=YES -DFLEX_EXECUTABLE="D:\Developer\win_flex_bison-2.5.25\win_flex.exe" -DCMAKE_INSTALL_PREFIX="./install" -DWANT_OPENGL=YES -DWANT_VULKAN=NO -G "Visual Studio 17 2022" -A x64 ../
``` 
Run:
```
python -m openage --add-dll-search-path=D:\Git\openage\build\libopenage\RelWithDebInfo main
``` 

Cannot find qml library, but it is in that path
![image](https://github.com/user-attachments/assets/32237444-6f9a-4308-814c-5dbfc515f08e)
then, I fix import QtQuick 2.4 -> import QtQuick
![image](https://github.com/user-attachments/assets/df3f4155-2425-46d6-ac79-85737cc88848)

![image](https://github.com/user-attachments/assets/b7f707a8-ca22-41b1-bc34-aaa7e1bb906b)

the openage window like this:
![image](https://github.com/user-attachments/assets/248f5d28-08ac-4a54-a507-29e62e7695f0)

**Comment by TheJJ** [comment]
thanks.
so you needed to patch some things in the code in order for it to work? can you send this patch please, so we may integrate it for everyone?

did the build documentation work, or did you need adjustments there as well?

**Comment by TheJJ** [comment]
i'll close this for now :)
