### ISSUE TITLE
Implement pairing heap without `shared_ptr`

### ISSUE THREAD

**Issue by heinezen** [SFTtech/openage#1675]
**Required Skills:** C++

**Difficulty:** Hard

openage provides a [pairing heap implementation](https://github.com/SFTtech/openage/blob/master/libopenage/datastructure/pairing_heap.h) that is mostly used in the A\* algorithm of our pathfinder. Currently, nodes on the heap are connected using `shared_ptr`. However, we have noticed that the creation of `shared_ptr` objects when using the heap is very slow. A variant with raw pointers and without `shared_ptr` may offer better performance benefits.

A previous implementation already used raw pointers. You can see it in commit https://github.com/SFTtech/openage/commit/4ab602a6242448bb82eac5db9eafa96d758c7199

Tasks:

- [ ] Implement the pairing heap without using `shared_ptr` or `enable_shared_from_this`. You can use the implemenation in https://github.com/SFTtech/openage/commit/4ab602a6242448bb82eac5db9eafa96d758c7199 as a reference but be aware that other parts of the code may have changed since then.
- [ ] Use [callgrind](https://valgrind.org/info/tools.html) to compare the speed of the old implementation with your solution that uses precomputed graphs:

```
valgrind --tool=callgrind ./run test -d pathfinding.tests.path_demo 1
```

**Further Reading**

- [pairing heap code](https://github.com/SFTtech/openage/blob/master/libopenage/datastructure/pairing_heap.h)

**Comment by vijayabhaskar78** [comment]
Can I work on this issue

**Comment by heinezen** [comment]
@vijayabhaskar78 Yes, you can. Do you have knowledge of C++? It's not the easiest beginner task for someone new to C++.

**Comment by heinezen** [comment]
@jere8184 it is available and it would be a nice addition :)

**Comment by jere8184** [comment]
Great, should I keep the shared pointer implementation or replace it?

**Comment by heinezen** [comment]
I think we can just replace it.

**Comment by heinezen** [comment]
Resolved in https://github.com/SFTtech/openage/pull/1713
