### ISSUE TITLE
Optionally check if all uniform values have been set

### ISSUE THREAD

**Issue by heinezen** [SFTtech/openage#1681]
**Required Skills:** C++ (understanding OpenGL terminology is helpful too)

**Difficulty:** Easy

Whenever we want to change something in the shader for an object, we use a [`UniformInput`](https://github.com/SFTtech/openage/blob/d09adb0901b15deb1b02b257ff437a283f694771/libopenage/renderer/opengl/uniform_input.h#L25) object to store the values. When the object is rendered, the data from the uniform input is passed to the GPU, e.g. via OpenGL. The definitions of the uniform data rypes are stored in the [`ShaderProgram`](https://github.com/SFTtech/openage/blob/master/libopenage/renderer/opengl/shader_program.h) class.

During rendering, the GPU does not strictly require that *all* uniform values have to be set for rendering to happen. However, when a uniform value is not set, e.g. when someone forgets to set pass it to the uniform input, this often leads to rendering errors, or worse: nothing being rendered at all. This is often infuriating to debug as it not always clear from the start whether the value was just forgotten or another error produces the rendering problems. To mitigate these issues, we should add a way to check if all uniform values for a uniform input have been set.

To try out the renderer and see how setting uniform values work, check out renderer demo 4 by running the following command:

```
./run test -d renderer.tests.renderer_demo 4
```

Tasks:

- [ ] Implement an `is_complete(..)` method for [`GlUniformInput`](https://github.com/SFTtech/openage/blob/d09adb0901b15deb1b02b257ff437a283f694771/libopenage/renderer/opengl/uniform_input.h#L25) that checks if all uniform values have been set. You can accomplish this easily by iterating through the `update_offs` vector and testing if the `used` flag has been set.
- [ ] Add `is_complete(..)` checks to the renderer demos in https://github.com/SFTtech/openage/tree/master/libopenage/renderer/demo

**Further Reading**

- [Renderer documentation](https://github.com/SFTtech/openage/tree/master/doc/code/renderer)
- [Uniform input code](https://github.com/SFTtech/openage/blob/master/libopenage/renderer/opengl/uniform_input.h)

**Comment by AdamYChe** [comment]
Hey, I think I'll try this issue out.

**Comment by heinezen** [comment]
@AdamYChe Nice! If you have any problems, contact us in our [chatroom](https://matrix.to/#/#sfttech:matrix.org)

**Comment by yukirine** [comment]
Hey ! can i try this issue too ?

**Comment by heinezen** [comment]
@yukirine Yes, you can!

**Comment by ZzzhHe** [comment]
Hi, I’d love to contribute to this! I was wondering if it would be appropriate to call the `is_complete(..)` function within [`GlShaderProgram::update_uniforms(...)`](https://github.com/SFTtech/openage/blob/faec07da10f72f7f7f69b280fe0f6c65960ddffb/libopenage/renderer/opengl/shader_program.cpp#L342)? This way, the uniforms can be verified in each iteration of the loop before rendering. Would this approach make sense?

**Comment by heinezen** [comment]
@ZzzhHe We would probably want to avoid this (even in debug mode) because the render loop should be as fast as possible and adding sanity checks could slow it down substantially. I think the best place to call the function is in the code of the several demos that we have, see https://github.com/SFTtech/openage/tree/master/libopenage/renderer/demo

**Comment by ZzzhHe** [comment]
@heinezen Thanks! I get it. Working on it.

**Comment by ZzzhHe** [comment]
I’ve implemented an `is_complete()` function in GlUniformInput, but using it requires dynamic_pointer_cast since `new_uniform_input()` returns a UniformInput instead of GlUniformInput. Would it make sense to add `is_complete()` as a virtual method in UniformInput? This would allow calling is_complete() directly on UniformInput. Or, is there another approach you’d recommend?

**Comment by heinezen** [comment]
@ZzzhHe Yes, that would make sense!
