### ISSUE TITLE
Add frames per second limiter

### ISSUE THREAD

**Issue by TheJJ** [SFTtech/openage#170]
Currently, the fps are only capped by vsync.

On my machine, vsync is deactivated once the game windows is move to background (no longer visible), and the fps skyrocket and heat up my machine to 96°C.

There should be some capping which could be configurable through a command line option `--fps 60`. 

This is obviously enabled additionaly to vsync, so when vsync is active, the fps limit should not prevent frame skips (e.g. just use 70 as limit).

**Comment by franciscod** [comment]
```diff
diff --git a/cpp/engine.cpp b/cpp/engine.cpp
index d4f7509..0bc9f0f 100644
--- a/cpp/engine.cpp
+++ b/cpp/engine.cpp
@@ -223,6 +223,8 @@ bool Engine::draw_debug_overlay() {
                "%.1f fps", this->fpscounter.fps
        );
 
+       printf("%.1f fps\n", this->fpscounter.fps);
+
        // Draw version string in the lower left corner
        this->render_text(
                {5, 35}, 20,
```

on my pc, it never exceeds 60fps, even with the window minimized (i'm on xfce). maybe I have to disable vsync?

**Comment by TheJJ** [comment]
The think is that an inactive SDL window on my machine is no longer vsynced, as the xserver doesn't seem to fetch the framebuffer of the programm any more. This leads to openage running the main loop at any speed, which is why we need the fps limit :smile:

**Comment by TheJJ** [comment]
Done in #544
