### ISSUE TITLE
Issue building with Clang (git master)

### ISSUE THREAD

**Issue by FabioLolix** [SFTtech/openage#1727]
Hi, it is some time that the program no longer build with Clang, I don't build this every day but looking at my builded packages and build logs the last successful builded is `openage-git_clang-0.5.3.r226.g4abd237d5-1-x86_64.pkg.tar.zst` as for next `openage-git_clang-0.5.3.r440.gd09adb090-1-x86_64-build.log` and later have only the logs

Builded on Arch Linux with Clang 18.1.8

```
[ 87%] Building CXX object libopenage/CMakeFiles/libopenage.dir/versions/versions.cpp.o
[ 87%] Linking CXX shared library libopenage.so
CMakeFiles/libopenage.dir/main/demo/pong/gamestate.cpp.o:gamestate.cpp:function openage::main::tests::pong::PongState::PongState(std::shared_ptr<openage::event::EventLoop> const&, std::shared_ptr<openage::main::tests::pong::Gui> const&, std::shared_ptr<nyan::View> const&):(.text+0x10ab): error: undefined reference to '_ZNK4nyan6Object3getITkNS_9ValueLikeES0_EESt10shared_ptrIT_ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEm'
CMakeFiles/libopenage.dir/util/file.cpp.o:file.cpp:function openage::util::File::get_temp_file(bool):(.text+0x51d): warning: the use of `tmpnam' is dangerous, better use `mkstemp'
CMakeFiles/libopenage.dir/util/fslike/directory.cpp.o:directory.cpp:function openage::util::fslike::Directory::get_temp_directory():(.text+0x1f18): warning: the use of `tmpnam' is dangerous, better use `mkstemp'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libopenage/CMakeFiles/libopenage.dir/build.make:6311: libopenage/libopenage.so.0] Error 1
make[1]: *** [CMakeFiles/Makefile2:4652: libopenage/CMakeFiles/libopenage.dir/all] Error 2
make: *** [Makefile:166: all] Error 2
==> ERROR: A failure occurred in build().
```

**Comment by heinezen** [comment]
Hey, have you also build `nyan` with clang? I'm pretty sure that this is the issue. `clang` recently changed rules for name mangling which unfortunately means that the mangled names diverge from the ones produced by `gcc`

See https://github.com/llvm/llvm-project/issues/102443#issuecomment-2329726287

**Comment by FabioLolix** [comment]
> have you also build nyan with clang? I'm pretty sure that this is the issue

No is builded with `gcc` haven't made a variant of that, I'll try later today as I need to get AFK for a while

**Comment by FabioLolix** [comment]
Solved by doing as suggested

but I warn you that I have another compilers related issue incoming :)

> See https://github.com/llvm/llvm-project/issues/102443#issuecomment-2329726287

Thabks, nice to know
