### ISSUE TITLE
./configure simply opens the configure file in Visual Studio Code

### ISSUE THREAD

**Issue by dmwever** [SFTtech/openage#1728]
I am trying to run the ./configure command. All that happens is that the configure file opens up in Visual Studio Code.

**Comment by dmwever** [comment]
I think I figured this out... Configure is a python class and I am too dumb to use it properly

**Comment by heinezen** [comment]
You just need to run `./configure` in your terminal, just as described in the [Quickstart](https://github.com/SFTtech/openage/tree/master?tab=readme-ov-file#quickstart) section of the README:

```
./configure --download-nyan
make
```

**Comment by heinezen** [comment]
Closing as it is not really a bug.

**Comment by heinezen** [comment]
If you need help for setting up your environment, our development chat on Matrix might be a better place to discuss specifics.

https://matrix.to/#/#sfttech:matrix.org
