### ISSUE TITLE
Can not link shader program

### ISSUE THREAD

**Issue by behind1231** [SFTtech/openage#174]
archlinux X86_64 system

    behind@localhost:~/openage-master$ make run
    [  1%] Built target pymodules
    [  2%] Built target codegen
    [100%] Built target openage
    ./openage --data=assets
    MSG   data folder will be assets
    MSG   launching engine with data directory 'assets'
    Failed to create secure directory (/run/user/1000/pulse): Permission denied
    MSG   initialized SDL audio subsystems.
    MSG   Using audio device 'default' [freq=48000,format=32784,channels=2,samples=4096]
    DBG2  queried font: DejaVu Serif:style=Book
    DBG2  returning font file /usr/share/fonts/TTF/DejaVuSerif.ttf
    DBG2  queried font: DejaVu Serif:style=Book
    DBG2  returning font file /usr/share/fonts/TTF/DejaVuSerif.ttf
    MSG   initialized SDL video subsystems.
    DBG0  Maximum supported texture size: 4096
    DBG0  Maximum supported texture units: 20
    DBG2  queried font: DejaVu Sans Mono:style=Book
    DBG2  returning font file /usr/share/fonts/TTF/DejaVuSansMono.ttf
    DBG0  console font character size: 8x17
    MSG   Loading time [engine]: 0.484 s
    DBG1  Loaded texture from 'assets/missing.png'
    DBG1  Loaded texture from 'assets/gaben.png'
    DBG0  terrain prefs: 29 tiletypes, 9 blendmodes
    DBG1  Loaded texture from 'assets/converted/Data/terrain.drs/15001.slp.png'
    (...)
    DBG0  neighbor 7 not found.
    MSG   ERROR: Program linking failed
    Fragment info
    -------------
    0(65) : error C6013: Only arrays of texcoords may be indexed in this profile, and only with a loop index variable
    0(65) : error C6013: Only arrays of texcoords may be indexed in this profile, and only with a loop index variable
    0(65) : error C6013: Only arrays of texcoords may be indexed in this profile, and only with a loop index variable
    0(65) : error C6013: Only arrays of texcoords may be indexed in this profile, and only with a loop index variable
    0(65) : error C6013: Only arrays of texcoords may be indexed in this profile, and only with a loop index variable
    0(65) : error C6013: Only arrays of texcoords may be indexed in this profile, and only with a loop index variable
    0(65) : error C6013: Only arrays of texcoords may be indexed in this profile, and only with a loop index variable
    0(65) : error C6013: Only arrays of texcoords may be indexed in this profile, and only with a loop index variable
    FATAL Exception: Program linking failed
    Fragment info
    -------------
    0(65) : error C6013: Only arrays of texcoords may be indexed in this profile, and only with a loop index variable
    0(65) : error C6013: Only arrays of texcoords may be indexed in this profile, and only with a loop index variable
    0(65) : error C6013: Only arrays of texcoords may be indexed in this profile, and only with a loop index variable
    0(65) : error C6013: Only arrays of texcoords may be indexed in this profile, and only with a loop index variable
    0(65) : error C6013: Only arrays of texcoords may be indexed in this profile, and only with a loop index variable
    0(65) : error C6013: Only arrays of texcoords may be indexed in this profile, and only with a loop index variable
    0(65) : error C6013: Only arrays of texcoords may be indexed in this profile, and only with a loop index variable
    0(65) : error C6013: Only arrays of texcoords may be indexed in this profile, and only with a loop index variable
    Makefile:46: recipe for target 'run' failed
    make: *** [run] Error 1
    behind@localhost:~/openage-master$

**Comment by behind1231** [comment]
算了，我放弃了这游戏了，等了这么久还没支持我的显卡～！(Forget it, I gave up the game, haven't waited so long for support my graphics card ~!)

**Comment by behind1231** [comment]
就算游戏暂时还没开发好，起码也能启动游戏吧，但是连起动也起动不了，0ad这游戏也能运行啊！HON这游戏也能运行啊～！也能玩啊～！不是我的显卡是硬伤吧！(Even if the game didn't develop well, yet at least also can start the game, but not even starting starting, 0 AD this game can be run! HON this game also can run ah ~! Also can play ~! Is not my video card is indifference!)

**Comment by TheJJ** [comment]
As I'm understanding "Forget it, I gave up the game, haven't waited so long for support my graphics card", we can close this issue.
