### ISSUE TITLE
Create/use interactive GUI elements

### ISSUE THREAD

**Issue by TheJJ** [SFTtech/openage#178]
It is now inconvenient to access all the of features in the game via dirty shortcuts.

Sure, the `--test` invokations are used for developers, but users should get some kind of shiny buttons
to control and select the game features.

An implementation for GUI elements is needed.
- For the engine editor, we should go for GTK/Qt stuff.
- The in-game view probably needs custom GUI elements.

Things like shift-scrolling for the building selection is inconvenient as fuck and has to be replaced.

Stellarium has a [totally awesome GUI](https://bazaar.launchpad.net/~stellarium/stellarium/trunk/files/head:/src/gui/) based on Qt, licensed GPL2+ so we should maybe take it as a start.

**Comment by TheJJ** [comment]
For the record, @Ethon started working on this. He's probably hanging around in our IRC for questions.

**Comment by rkreis** [comment]
I'm working on it, see https://github.com/rkreis/openage

**Comment by TheJJ** [comment]
@rkreis has taken over and is working on it, he's also in the IRC.

**Comment by TheJJ** [comment]
For drawing fonts, this probably benefits from #181.

**Comment by ChipmunkV** [comment]
How about the Qt GUI for the ingame? QtQuick is pretty ready for that now.

**Comment by TheJJ** [comment]
Never heard of it. Is it some kind of tookit to be embedded in a renderer? Beware, we should plan for OpenGL, WebGL, Vulkan, DirectX, ... although currently only OpenGL is implemented.

**Comment by franciscod** [comment]
consider these:
https://github.com/ocornut/imgui
https://github.com/hugoam/kiui

**Comment by hadim** [comment]
QtQuick and Qt are really excellent to build GUI and modern OpenGL inside Qt application is supported.

**Comment by ChipmunkV** [comment]
When the Qt was bought by Nokia, they set a goal to develop the new GUI library to replace Qt Widgets. This library obviously was intended to be used for mobile devices. Dynamic customizable GUI with effects and animations.

So, from the start they have chosen that it'll be entirely rendered in OpenGL or OpenGL ES.

Which means that the integration into the game is the same as the integration of any other gaming UIs: just give the GL context. (like myGUI, CEGUI, etc. worked)

Now Qt is owned by Digia and QtQuick is presented as the main GUI toolkit.

The code of the application that uses QtQuick has two parts: C++ backend and QML frontend. The applicability to the game UI comes from the flexibility of the QML part: it allows to make components out of basic things like rectangles and images.

QtQuick can take a FBO  and use it as a texture (it's like a second type of integration). Shaders can be written in QML file to operate on the GUI element. There is a particle system within QtQuick, so the smoke can come out of the plain QML.

As you can see, this adds a language to the project. There is some learning curve because of battling with layouts, variable bindings and scopes in QML.

**Comment by TheJJ** [comment]
How would this play out with the rather custom look of the ingame UI, which has to look more or less like the original game? Also, does it support any raw memory buffer/fbo/etc so I can also pass it a buffer from e.g. Vulkan?

**Comment by ChipmunkV** [comment]
I've mentioned FBO.

 It's pretty good for custom looks. I believe that exact 1 to1 look is possible without C++ rendering code.

One component that needs C++ rendering code is the minimap. Of course, it can be done entirely in QML, but each dot would be a QObject which isn't fast. So, have to do a custom C++ implementation for the minimap QML component with just one VBO (or whatever how it's done).

**Comment by ChipmunkV** [comment]
Ok, it's kinda working.

Will have to dig through that long forgotten GLv1 (you've said that it's 2.1?) code to find out why the terrain is garbled.

Input/resize probably requires forwarding from SDL.

**Comment by TheJJ** [comment]
Nice! How'd you do it?

Currently it's OpenGL 2.1, but the new renderer will bring OpenGL 3.3 support. New backends like Vulkan will then be integrated.

**Comment by ChipmunkV** [comment]
It's like described in the docs of the QQuickRenderControl that takes a GL context of the application and gives it to QtQuick.

We have to make sure that we're ok with the implications. SDL and Qt know about all the platforms, but not about each other AFAIK. So, the transfer of the context goes through the platform-specific piece of code.

**Comment by TheJJ** [comment]
Hrrg, can't it just take raw buffers to render to? Because if it is context-pinned ("we're in opengl") then this is very bad for future planning and independency which the new renderer is created for (vulkan!)
I'm also not sure how well it'll work out to pass the SDL input to Qt, but that's probably a smaller problem.

I just researched a bit http://doc.qt.io/qt-5/qquickrendercontrol.html:

The QQuickRenderControl class provides a mechanism for rendering the Qt Quick scenegraph onto an offscreen render target in a fully application-controlled manner.

QQuickWindow and QQuickView and their associated internal render loops render the Qt Quick scene onto a native window. In some cases, for example when integrating with 3rd party OpenGL renderers, it might be beneficial to get the scene into a texture that can then be used in arbitrary ways by the external rendering engine. QQuickRenderControl makes this possible in a hardware accelerated manner, unlike the performance-wise limited alternative of using QQuickWindow::grabWindow()

So we can probably use http://doc.qt.io/qt-5/qquickwindow.html#setRenderTarget-1

But before we adopt this too quickly: Will it be possible to:

* Use all the interface graphics to recreate the original GUI and HUD?
* Make it scalable and any-resolution-capable for 4k displays and any window size?
* Still performant even if the GPU is pretty busy rendering thousands of units?
* Keep all Qt stuff away from the rest of the codebase without having to do data conversions?

**Comment by ChipmunkV** [comment]
It renders to the raw buffers. You can choose the window buffer or create an FBO (and use it with the QQuickWindow::setRenderTarget as you said).

But QQuickRenderControl needs a QOpenGLContext. That context can be either created or adopted via a native handle.

(sidenote: don't worry about Vulkan. Digia already has its current API draft while we still have glPopMatrix stuff in the code : D )

* according to me (a guy from the Internet), its possible to recreate original GUI and HUD
* it's scalable. That was a design goal back in the days of Nokia
* the only way to kill performance is to start writing tones of logic inside QML
* keeping Qt isolated without conversions is oxymoron. But I can't imagine an example with any significant amount of data to transfer
* popups and overlays are naturally going to the GUI side. And I'm not aware about the method of linking the tree to some other system, it should somehow know how to render it...

**Comment by ChipmunkV** [comment]
Code time:

https://github.com/ChipmunkV/openage/commit/223925baa04cdcfc0938a8aa55a6a34b0fa907b4

To get an idea what is the minimal implementation of the integration.

The expected effects are the following:
* scales everything to 640x480 regardless of the window
* breaks the terrain and unit rendering (leaves  existing overlays pretty much intact)
* draws a green square 100x100 from Qt

**Comment by TheJJ** [comment]
Not bad, haven't tried it out but the code looks relatively simple. Damnit, I really should finish the new renderer soon, at least use it as the base for the although-crappy current render pipeline.
Keep it going :)

**Comment by TheJJ** [comment]
After thinking longer about this, i think it's a good decision to go with Qt and QML.
Mods can provide new GUI arrangements with QML easily.

But we really need to have a sane integration of Qt, so the API can then quickly be utilized by mods and other game components that provide a gui. Namely, the `libopenage/gui` subsystem should provide our "internal" GUI API, and other components, e.g. the tech tree, settings manager, etc and more to come can use it.

That way the subsystem separation will stay strict I hope, and the Qt-internal stuff stays in `gui/`.

**Comment by ChipmunkV** [comment]
You can already see even in the first version of https://github.com/SFTtech/openage/pull/422 the pimpl wrapping of the classes that initialize the GUI.

So, the files outside `libopenage/gui` don't include any Qt headers or any readers from `libopenage/gui` that include Qt headers.

For the domain classes (game logic components) the possible arrangement is to add to the current classes that are in `libopenage/` some getters and callbacks. Then for each class write a QObject wrapper in `libopenage/gui` that will expose these things as QtProperties.

**Comment by ChipmunkV** [comment]
QtQuick GUI for the editor is way more interactive now: https://github.com/SFTtech/openage/pull/422

**Comment by TheJJ** [comment]
#422 has gone live!
