### ISSUE TITLE
Switch minimum compiler version to GCC 4.9/Clang 3.5

### ISSUE THREAD

**Issue by mic-e** [SFTtech/openage#193]
There has been discussion on the IRC channel about ditching GCC 4.8/Clang 3.4 support in order to make use of some new language features.

The obvious downside is that parts of the user/developer base would need to upgrade their toolchains, which may or may not require unreasonable effort.

I have been assured that Clang 3.5 is available on OSX Mountain Lion and upwards through XCode 6. The recent compiler versions are available on Debian testing-soon-to-be-stable as well as the most recent (non-LTS) version of Ubuntu.

What about mingw cross-compilers and other Linux distributions?

This issue is intended as a platform for discussion.

**Comment by TheJJ** [comment]
Distro overview:
* Ubuntu
  * 12.04 (travis): 4.6 (ppa: 4.8.1, 4.9.2)
  * 14.04: 4.8.2
  * 14.10: 4.9.1
* Gentoo has 4.9.2 but masked, 4.8.4 is stable
* Arch has 4.9.2
* Fedora 21 got 4.9.2
* Suse still seems to be at 4.8
* Debian wheezy at 4.7, jessie has 4.9

**Comment by StepS-** [comment]
:+1:

**Comment by janisozaur** [comment]
what are the features in question?

**Comment by fr3akout** [comment]
One problem is, that pull request https://github.com/SFTtech/openage/pull/192 produces a linker error with gcc 4.8.1. It makes use of thread_local variables. With gcc >= 4.8.2 there are no problems anymore.

**Comment by mic-e** [comment]
Moving forward to C++14 wouldn't be that much of an issue; it's a matter of changing a single byte in a CMakeLists.txt file, and we definitely want to do that sooner or later.

We're not limiting ourselves to the features provided by a certain standard, we're limiting ourselves to the minimum set of features supported by our supported compiler versions. This is ensured by the Travis CI, which checks every pull request and commit with those minimum compiler versions (and often finds issues due to the fact that on our local machines, we're working with more recent compilers).

Currently we're compiling with `-std=c++11` mostly to avoid accidentially using features that Travis would then reject.

So, yes, being able to switch to C++14 would be one of the benefits of dropping support for gcc 4.8/clang 3.4.

**Comment by franciscod** [comment]
mingw on arch has 4.9.2: https://www.archlinux.org/packages/community/x86_64/mingw-w64-gcc/

msys2 has 4.9.2 too: https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-gcc/PKGBUILD#L15

**Comment by TheJJ** [comment]
Hereby I officially request the switch to C++14 and all implied compiler updates :relieved:. Upgrading is the future, and the future starts with: us!

If there are no big counter-arguments, I'll perform the update next week, probably at 25 or 26.2.

**Comment by franciscod** [comment]
agreed!

**Comment by StepS-** [comment]
:+1:
