### ISSUE TITLE
The game doesn't work without without an audio device (at least on windows)

### ISSUE THREAD

**Issue by franciscod** [SFTtech/openage#206]
VM misconfigured while working on #9, woohoo! Probably ultra low priority, lol

```
Windows@Windows-PC MINGW32 ~/openage
$ ./openage.exe
MSG   launching engine with data directory './assets'
MSG   initialized SDL audio subsystems.
MSG   ERROR: Error opening audio device: DirectSoundCreate: No audio device found
FATAL Exception: Error opening audio device: DirectSoundCreate: No audio device found
```
##

**Comment by TheJJ** [comment]
Hm yeah, but the actual bug is that you do have an audio device, right?

**Comment by franciscod** [comment]
Nope, the vm didn't have the driver installed.

Should openage require an audio device?

**Comment by TheJJ** [comment]
Hm in that case it is a bug indeed, if no audio device is detected, the game should still work.
