### ISSUE TITLE
Progress notification from the asset conversion script

### ISSUE THREAD

**Issue by rkreis** [SFTtech/openage#215]
Ideally, there would be a progress bar and ETA displayed while the conversion script runs.  The first step could be some kind of progress notification from the script, possibly as simple as a counter incremented whenever an asset is converted to start with.
##

**Comment by TheJJ** [comment]
Good idea, this depends on implementing the Python API (#217) and calling convert from the game (#29).
Also the conversion targets (#79) and media versioning (#204) are related, as they introduce reconversion of the changed parts only.

**Comment by zuntrax** [comment]
I'll keep this in mind while tampering with the convert module.

**Comment by TheJJ** [comment]
There's no ETA displayed but we do have a items remaining counter now.
