### ISSUE TITLE
Symlinks and Windows

### ISSUE THREAD

**Issue by franciscod** [SFTtech/openage#222]
Currently, the main `./configure` script uses a symlink for `bin`. Also, on `crossplatform/os.cpp` there's a read_symlink function (unused by now), which is unimplemented for windows. Windows doesn't support symlinks in non obscure ways (at least, obscure for non-*nix users), so.. should we stop using them? Should we have workarounds for Windows? We do want to keep them for any reason in particular?
##

**Comment by franciscod** [comment]
http://www.howtogeek.com/howto/16226/complete-guide-to-symbolic-links-symlinks-on-windows-or-linux/

**Comment by TheJJ** [comment]
The symlink is the only way of having a convenient way switching compilers.

If we make our goal of crosscompiling for windows, then we can still use the symlinks, otherwise we probably have to tell windows-guys not to use `./configure` or come up with something else..

**Comment by StepS-** [comment]
`Windows doesn't support symlinks in non obscure ways`
And what does "non obscure" mean? Symbolic links and junction points work perfectly starting with Vista (XP only supported hardlinks AFAIK), it's also part of the NTFS specification (the version that Vista first ran on). It's just that some developers don't bother (I bet that the latest version of git still stubs out symlink support on Windows, despite multiple symlink-supporting branches having been created in the past).
Please provide a definition for "non obscure".

**Comment by franciscod** [comment]
I read a little bit. Thanks for your insight, StepS-.

On python the default os.symlink implementation is a stub, so I thought it wasn't supported by Windows. But it provides a WinAPI call and there is `mklink` too, so maybe someone can figure out how to put all these guys together. :)

https://stackoverflow.com/questions/1447575/symlinks-on-windows

https://stackoverflow.com/questions/6260149/os-symlink-support-in-windows

https://stackoverflow.com/questions/197379/how-do-i-create-a-symlink-in-windows-vista

**Comment by rkreis** [comment]
The build process currently creates two symlink: `bin -> .bin/...` depending on the selected build configuration and `openage -> .bin/.../cpp/openage` to comfortably run the binary.  You can easily build and run openage without creating any symlinks (check with `find . -type l`) using following steps:

 1. Comment out line 295 in the `configure` script (`os.symlink(linkto, name)`).
 2. ./configure with any flags you want.
 3. Modify line 12 in the Makefile (`BUILDDIR=`) to point to the right subdirectory in `.bin`.
 4. `make` and run `.bin/.../cpp/openage`.

I guess it should be easy to make the build process detect if symlinks are supported and work, and work around it when they aren't.

**Comment by franciscod** [comment]
`mklink` (and i assume the winapi call too) needs admin privileges

https://superuser.com/questions/129299/got-not-sufficient-privileges-message-in-cmd-when-logged-on-as-administrator

**Comment by StepS-** [comment]
Yes, by default symbolic links in Windows require elevation. That might have been the stopping factor for the devs. It's possible, however, to permanently get rid of the requirement to elevate, but only on your machine: https://superuser.com/questions/124679/how-do-i-create-a-link-in-windows-7-home-premium-as-a-regular-user/125981#125981

**Comment by TheJJ** [comment]
https://blogs.windows.com/buildingapps/2016/12/02/symlinks-windows-10/ windows 10 will support links now.

However, for other windows versions, I think this is a non-issue as you'd invoke cmake directly to develop under windows.

**Comment by StepS-** [comment]
Correction: symbolic links have been supported since Vista, the latest Windows 10 addition enables their creation without having admin rights. Previously, you had to elevate the process to call CreateSymbolicLink.

**Comment by Wandalen** [comment]
Windows has been supporting symlinks for long time.
Problem with that support it does not include relative symlinks what makes such support equi-useless
Windows supports absolute symlinks only.

**Comment by jazzpi** [comment]
@Wandalen That blog post implies that relative symlinks are supported:

![](https://winblogs.azureedge.net/win/2016/12/Picture31.png)

I think you're talking about NTFS junction points, not [NTFS symlinks](https://en.wikipedia.org/wiki/NTFS_symbolic_link). Quoting from Wikipedia:

> While NTFS junction points support only absolute paths on local drives, the NTFS symbolic links allow linking using relative paths. Additionally, the NTFS symbolic link implementation provides full support for cross-filesystem links.

**Comment by StepS-** [comment]
> Problem with that support it does not include relative symlinks what makes such support equi-useless
Windows supports absolute symlinks only.
Wrong. Relative paths are well supported, and I use such links every day.

**Comment by Wandalen** [comment]
@jazzpi Oh I see. Didn't know there are several different types of symbolic links on Windows. Yes I talked about junction. Thanks, interesting material.
