### ISSUE TITLE
Integrate gcc -fsanitize into buildsystem

### ISSUE THREAD

**Issue by TheJJ** [SFTtech/openage#226]
`gcc` supports [-fsanitize=...](https://gcc.gnu.org/onlinedocs/gcc/Debugging-Options.html#Debugging-Options) for identifying memory probloems and other things.

We could add the invokation to the `./configure` script to enable their usage conveniently.

**Comment by rkreis** [comment]
Clang also has -fsanitize flags.  MemorySanitizer will be tricky to use because all code, including the standard library, will have to be compiled with it (see http://clang.llvm.org/docs/MemorySanitizer.html).

**Comment by TheJJ** [comment]
done by #288
