### ISSUE TITLE
Make the code compliance Makefile targets selective

### ISSUE THREAD

**Issue by rkreis** [SFTtech/openage#229]
`make checkfull` takes roughly 10 seconds to run here.  If there was a way to only check files that were modified, it would be more practical to run code compliance checks as a commit hook.  That would lead to less frustration with pull requests failing to build because of things like copyright headers not being up to date.

**Comment by franciscod** [comment]
should travis do `make checkfull` **before** compiling?

**Comment by mic-e** [comment]
Offering to check only files that have changed... since `HEAD~1`? does indeed seem like a good idea.

**Comment by mic-e** [comment]
The relevant `git` command would be `git diff --name-only REF`; I suggest a option to `codecompliance`'s argparser: `--to-ref`, `default=None`, example:
`python3 -m buildsystem.codecompliance --all --to-ref=master`

**Comment by TheJJ** [comment]
Currently the build won't start if the checkfull fails. `make runci` does that, so at least we don't have to wait for the compilation to finish. Checking before all the dependencies are installed is impossible, as we need to `configure` to generate many files, and `configure` checks the dependency presence.

**Comment by mic-e** [comment]
I have incorporated this feature into my current PR, #288.
