### ISSUE TITLE
Avoid merge conflicts in copying.md author list

### ISSUE THREAD

**Issue by TheJJ** [SFTtech/openage#230]
The most common merge conflict are names in copying.md.

The only solution for this i can think of is creating a `contributors/` directory containing one file for each contributor, which contains further info in a yet-to-be-determined format.

This will finally stop all the merge conflicts in the author list. What do you think? Other ideas?

**Comment by janisozaur** [comment]
I think that, while perhaps common, it is the easiest merge conflict to solve.
Other projects, say scummvm, openrct2, etc, all have just one file with all the authors listed in it as well.
Once you reach a certain threshold, this problem will eventually go away, or at least no longer be of great importance.

**Comment by TheJJ** [comment]
this problem will never go away as long as users append themselves to the end of the list.

**Comment by franciscod** [comment]
http://git-scm.com/docs/gitattributes

union

    Run 3-way file level merge for text files, but take lines from both
versions, instead of leaving conflict markers.

this problem will never go away as long as users append themselves to the
end of the list.

—
Reply to this email directly or view it on GitHub
<https://github.com/SFTtech/openage/issues/230#issuecomment-74161132>.

**Comment by franciscod** [comment]
boo, github doesn't support this. made an experiment: https://github.com/franciscod/github-union-merge-test

**Comment by franciscod** [comment]
i've mailed a feature request to github :)

**Comment by franciscod** [comment]
a possible format for the `contributors/` directory idea:

```
contributors/Jonas Jelten:
    aliases: TheJJ
    email: jj@sft.mx

contributors/Matthias Bogad:
    aliases: delirium, masterofjellyfish
    email: matthias@bogad.at
```

**Comment by TheJJ** [comment]
How about underscores in the author filename? Having spaces will require ugly backslashes when referring to the files in a shell. But yeah, otherwise this is what i thought of.

**Comment by franciscod** [comment]
or simply drop the whitespace: `JonasJelten` `FranciscoDemartino` `MichaelEnsslin`

**Comment by zuntrax** [comment]
I'd rather have to merge pull requests with the CLI than have separate files for each author.

**Comment by rkreis** [comment]
I'm not quite happy with having one file per author. I think it would add too much complexity with too little benefit. If we just agree on keeping the list sorted, merge conflicts will eventually become quite rare (and easily resolved).

**Comment by TheJJ** [comment]
Sorting it alphabetically might work, but some people might be afraid to put themselves on top of the list just because of their name. The files would have the advantage of adding more information per author easily, the current table is a better and simpler overview.

**Comment by rkreis** [comment]
No matter if we use a table or one file per author (maybe vcf?), it
would be nice to also link authors to subsystems. Currently, to find
out who knows about feature X, you have to git blame or ask on IRC.

**Comment by franciscod** [comment]
I don't like the idea of forcing author<-->subsystem relations on the
documentation... Yes, always one of us has more knowledge or has written
more lines or has designed certain stuff, but I'd rather not write those
names in stone.

**Comment by dbrgn** [comment]
What about asking people to rebase against the current master? That's how I solved a conflict.

```
$ git fetch
$ git rebase origin/master
# Solve conflicts
$ git push -f
```

**Comment by franciscod** [comment]
Yeah, people can always solve the conflicts! But it's annoying and we could find a way to avoid it :)

**Comment by dbrgn** [comment]
I'm not a fan of separate files per contributor. And in a single file, there's no remedy against conflicts.

**Comment by franciscod** [comment]
For commandline git merges (not github web buttons) we can use the union merge driver:

union
Run 3-way file level merge for text files, but take lines from both versions, instead of leaving conflict markers. This tends to leave the added lines in the resulting file in random order and the user should verify the result. Do not use this if you do not understand the implications.

**Comment by dbrgn** [comment]
But what if the user did some other conflicting changes where a union merge is not appropriate? This might hide these conflicts.

Also, the conflicts are trivial to solve. I don't see a reason to use anything else than regular conflict resolution :) After all, it's a single line of text.

**Comment by mic-e** [comment]
I agree with @dbrgn. The current solution is the one that has maximum readability, and the merge conflicts are easy to solve.

No matter whether this is resolved via merge or rebase, it's just a matter of opening copying.md, searching for the signature '>>>>>>', and deleting the unnecessary lines. And the whole thing needs to happen at most once for every new contributor.

Adding one file per contributor would be massive overkill.

If you really think this is an issue, we could always sort the names alphabetically, thus lowering the chance of a merge conflict whenever two new contributors join the project at once to `O(1/n)`, and thus the number of merge conflicts until we reach n contributors to `O(log(n))`. But I think even that would be overkill.

**Comment by dbrgn** [comment]
@mic-e I like that idea!

**Comment by TheJJ** [comment]
kay, then we'll leave everything as it is for now^^

**Comment by franciscod** [comment]
@dbrgn you can specify on which files git will use the union strategy :)

:+1: for closing as is
