### ISSUE TITLE
Bountysource github plugin

### ISSUE THREAD

**Issue by x-a-n-a-x** [SFTtech/openage#235]
Hi.

I think you should consider adding the Bountysource.com github plugin on your github pages to let people place bounties on their favorite issues more easily.

Once installed, the plugin will make your github pages look like that (bounty values in titles and "Bounty" tags): https://github.com/OpenRA/OpenRA/issues?direction=desc&labels=bounty&page=1&sort=updated&state=open
If I remember, there are options to only display bounties in the title, or only tags, or both.. etc.

Here is doc (about how to integrate it on github):
http://blog.bountysource.com/post/48954271533/improved-github-integration-automatically-update

Thank you for your project !

**Comment by TheJJ** [comment]
Uh, don't we have that already? I think i added bountysource support to the project the way openra already has it. Issues with bounties do have the bounty tag and all issues get added a bountysource footer, or am I wrong?

**Comment by x-a-n-a-x** [comment]
Oops, sorry. It was obvious and I didn't see them. It seems I didn't pay attention enough. 😕
