### ISSUE TITLE
c++14-ize constexpr functions for string modification

### ISSUE THREAD

**Issue by TheJJ** [SFTtech/openage#255]
Now that we have c++14-support, the fancy constexpr functions can be written more readable.

https://github.com/SFTtech/openage/blob/7061e8bf1e54df177981415cd242f2d1dbf69ef1/cpp/util/constexpr.h

http://isocpp.org/files/papers/N3652.html

**Comment by iNaKoll** [comment]
This (unfortunately) needs GCC 5.0 C++14 implementation of N3652 ("Relaxing requirements on constexpr functions"). See [GCC C++14 support page](https://gcc.gnu.org/projects/cxx1y.html).

**Comment by mic-e** [comment]
@iNaKoll I was under the impression that gcc 4.9 would support this, but it seems like you're right. On the clang side of things, there has been support since version 3.5. Get your shit together, gcc.

**Comment by mic-e** [comment]
This is especially bad since the new LTS Ubuntu won't have gcc 5.0, so we'll have widespread, supported distributions that don't support this until 2018.

**Comment by detrumi** [comment]
Shouldn't this issue be closed?

**Comment by mic-e** [comment]
I guess so. We can always re-open it once we've migrated to gcc 5.0

**Comment by TheJJ** [comment]
is the problem resolved? no. -> why close it?

**Comment by TheJJ** [comment]
This may be implemented right now, with respect to needed compiler versions. That could be achieved by preprocessor switches or even buildsystem support. Until we require `>=gcc-5.0` we could have both versions in our tree that way.

**Comment by detrumi** [comment]
Duplicating it everywhere to get the new syntax in isn't really needed, and it makes it harder to maintain. So let's wait with this until we can apply it everywhere (so until we have the new gcc).

**Comment by mic-e** [comment]
I don't see an actual problem, or a need to solve it.
The only benefit of removing the recursion is that the code would be easier to read and write.
Duplicating code and adding preprocessor macros will remove both of those benefits.

**Comment by zuntrax** [comment]
I started rewriting that stuff.
