### ISSUE TITLE
Proposal: Split header files to avoid include dependency hell

### ISSUE THREAD

**Issue by mic-e** [SFTtech/openage#263]
Due to the nature of C++, for the purpose of compile-time reduction, it may be preferable to split some of our larger header files into three files. Take the following example files:

`a.h`

``` cpp
void f();

/**
 * docstring goes here
 */
struct A {
    /**
     * member function docstring goes here
     */
    template<int i>
    int member_function(int arg) {
        return arg + i;
    }
};
```

`b.h`

``` cpp
#include "a.h"
struct B {
    A *member_struct;
};
```

`c.h`

``` cpp
#include "b.h"
struct C {
    B *member_struct;
};
```

Every file that includes `c.h` will automatically include `b.h`, with all its own dependencies, including `a.h`. It will even need to parse the implementation of `a::member_function`. As a result, in practice everything that includes `engine.h` in openage automatically includes the huge majority of all openage header files.

However, `c.h` does not actually _need_ to know about the contents of `struct B`, it just needs to know that `B` _is_ a `struct`, so I suggest splitting the headers into:

`a_decl.h`

``` cpp
void f();

/**
 * docstring goes here
 */
struct A;
```

`a.h`

``` cpp
#include "a_decl.h"

struct A {
    /**
     * member function docstring goes here
     */
    template<int i>
    int member_function(int arg) {
        return arg + i;
    }
};
```

`b_decl.h`

``` cpp
struct B;
```

`b.h`

``` cpp
#include "b_decl.h"

#include "a_decl.h"
struct B {
    A *member_struct;
};
```

`c_decl.h`

``` cpp
struct C;
```

`c.h`

``` cpp
#include "c_decl.h"

#include "b_decl.h"
struct C {
    B *member_struct;
};
```

As an added bonus, this also prevents any unnecessary circular header dependencies.

To avoid unneeded parsing of template implementations, in addition `a.h` may be split into

`a.h`

``` cpp
#include "a_decl.h"

struct A {
    template<int i>
    int member_function(int arg);
};
```

`a_impl.h`

``` cpp
#include "a.h"

template<int i>
int A::member_function(int arg) {
    return arg + i;
}
```

I do not recommend making this policy mandatory, just to use it for headers where significant compile time reductions are to be expected.

**Comment by mic-e** [comment]
This github issue shall serve as a discussion platform, since the github issue tracker essentially functions as our mailing list. Everybody's feedback, criticism and ideas that are actually better than this are welcome.

BTW, someone should add that bit of info about our mailing list to README.md.

**Comment by Jon0** [comment]
The way I have tried to do things is for example b.h:
```c++
// just list the types
struct A;

/**
 * doc
*/
struct B {
    A *member_struct;
};
```

**Comment by mic-e** [comment]
@Jon0:
just listing the types seems a bit hacky. But it still might be the best solution; after all it avoids all of those boilerplate header files and keeps the docs centralized in a single file.

**Comment by franciscod** [comment]
how this dependency hell is an issue in our code? compilers don't figure this out?

**Comment by mic-e** [comment]
For example,

`game_main.h` includes `texture.h` because it has `Texture *gaben`.
`texture.h` includes `file.h` and `shader.h`, which are not needed in `game_main.h`, but nevertheless get included and parsed by the compiler.

This needlessly increases the compile time of every file that includes `game_main.h`. In addition, if someone edits `file.h`, this triggers a re-build of any file that includes `game_main.h`, again needlessly.

As a result, in practice, if you edit any header file, half of the project will be re-compiled.

**Comment by mic-e** [comment]
I've just learned the most amazing thing about C++:

It is allowed to write

    class A {
        class B *b;
    }

without ever forward-declaring `B`. I think this solves most of our issues.

**Comment by TheJJ** [comment]
In general, i like the idea. Details like filename conventions could be adopted, the `.tpp` idea or something else might be better.

**Comment by mic-e** [comment]
A lot of software would be very unhappy if header files started to have any ending but `.h` or `.hpp`.

**Comment by heinezen** [comment]
Most of this is probably more readable as a forward declaration as mentioned in https://github.com/SFTtech/openage/issues/263#issuecomment-87392772
