### ISSUE TITLE
Customizable key bindings

### ISSUE THREAD

**Issue by TheJJ** [SFTtech/openage#271]
Maybe store it as key-value pairs in `~/.openage/keybindings`.

This file should have a config version on top once the format gets more sophisticated to perform/detect updates.

Ideally, the bindings are managed in it's own subsystem (`cpp/keys`?) to allow central storage and changes.
The keys should probably point to functions that can be replaced at runtime. Avoid string lookups please. 

depends on the cvar config subsystem from #486

**Comment by detrumi** [comment]
I'll start working on this.

**Comment by mic-e** [comment]
I guess after #284, only the "read-keybindings-from-file-or-whatever" part remains to be implemented.

**Comment by Hoten** [comment]
I would like to begin contributing to this project, and I think this is a good way to start. I'll work on reading these key bindings from a configuration file.

**Comment by StepS-** [comment]
You might want to cooperate with @Elnabo then as I believe he already had plans for it in the meantime.

**Comment by elnabo** [comment]
The keybinds are now part of the generic config file(s). The config file reading should be done in python to be easily integrated with the cvar system (#486).

So I think you should focus on extracting any kind of couple key/value and if possible have a possibility to save modification.

**Comment by elnabo** [comment]
I think that  #537 has completed this issue, isn't it ?

**Comment by TheJJ** [comment]
YES! YES IT HAS!!!!


:beers:
