### ISSUE TITLE
Add docs on developing in IDE(s)

### ISSUE THREAD

**Issue by charego** [SFTtech/openage#279]
There are [free licenses](https://www.jetbrains.com/buy/opensource/?product=clion) for open source (core devs only).

https://www.jetbrains.com/clion/

> nobody uses any IDEs (unless you count emacs). If you want to use an IDE, first of all reconsider: Neither C++ nor Python are IDE-centric languages (unlike Java or C#) -- [development.md](https://github.com/SFTtech/openage/blob/master/doc/development.md)

:o

**Comment by TheJJ** [comment]
We're not forcing anyone to not use some IDE, you can use whatever you want.
However, advertising non-free software in our project documentation is not something I'll support.
What do you mean by "supporting the CLion IDE"?

**Comment by dbrgn** [comment]
I agree on this. Jetbrains make great IDEs, but we should not endorse any specific product. I'm pretty sure CLion has CMake support, so it should be easy to get started without any predefined project.

OTOH, if someone would want to create documentation how to set up common IDEs for this project (e.g. Eclipse CDT, Netbeans, QT Creator, maybe CLion), that would be something that might make sense.

**Comment by dbrgn** [comment]
This is probably related to #270.

**Comment by mic-e** [comment]
I agree that we should add documentation on using IDEs.

**Comment by meZee** [comment]
I think it would be nice to have documentation on how to use/configure them for working with this specific project as well. I don't think it should be required or endorsed, just maintained & easily available.

**Comment by rnestler** [comment]
I actually tried using qtcreator, but it was a bit cumbersome because of the rather custom build system. I could document it if someone is interested.

**Comment by ChipmunkV** [comment]
Related - #665

**Comment by simonsan** [comment]
> There are [free licenses](https://www.jetbrains.com/buy/opensource/?product=clion) for open source (core devs only).

I've wrote an application for 12 licenses today, will give a status update, when I have any news. Feel free to help documenting the development for starters with various IDEs in [/doc/ide.md](/doc/ide.md).

**Comment by TheJJ** [comment]
I added some words about setting up emacs in [/doc/ide/emacs.md](https://github.com/SFTtech/openage/blob/master/doc/ide/emacs.md).

**Comment by TheJJ** [comment]
I think we can close this, since there's now the ide doc folder in the repo and additions for any relevant IDE can simply be added there. Since it's not clear when this issue would resolve as there's probably arbitrarily many IDEs, specific setups should be requested as separate issues and addressed there.
