### ISSUE TITLE
create nyan - yet another notation

### ISSUE THREAD

**Issue by TheJJ** [SFTtech/openage#28]
_nyan_ is the future data storage format for openage.

It's designed for moddability and human-readability.

Development takes place here:
https://github.com/SFTtech/nyan

Tasks:
- [x] format specification
- [x] implement the [nyan database](https://github.com/SFTtech/nyan)

**Comment by TheJJ** [comment]
Soooo, we may have a specification:

https://github.com/SFTtech/nyan/blob/master/doc/nyan.md

head over there and improve it if things are missing :)

**Comment by TheJJ** [comment]
To "officially" announce it, my master's thesis is the design and implementation of nyan :tada:

**Comment by franciscod** [comment]
niceee!! openage goes to academia!

**Comment by elnabo** [comment]
Quick question, what is a master thesis and how long does it last ?

**Comment by janisozaur** [comment]
@elnabo (master) thesis is a work one has to create to be awarded a degree in a field of science. "Thesis" means the text document, but commonly the term also encompasses all of the derived products: source code, hardware platforms or other things, especially in other fields of studies. It "lasts" forever, as it gets archived by university and sometimes is made available to the public, as per agreement with the school. Perhaps you wanted to ask "how long does it take to create one?": in that case it's usually one or two terms (i.e. half a year or a year), but may, depending on the author, take also less or more time.

See also https://en.wikipedia.org/wiki/Master_of_Science (especially the pat about Germany, where I believe @TheJJ is) and https://en.wikipedia.org/wiki/Thesis

**Comment by elnabo** [comment]
Ok thanks, I was wondering what it was, as I think there is no equivalent in France or at least in my university.

**Comment by TheJJ** [comment]
The core nyan implementation should be done by now, some TODOs and mainly optimizations are left.
Next we have to come up with a step-by-step transition plan to integrate it.
