### ISSUE TITLE
GameMain / Renderer design?

### ISSUE THREAD

**Issue by Jon0** [SFTtech/openage#286]
`GameMain` could be broken into several components, I think splitting into model (terrain, units), view (main opengl rendering) and controller (hud/hotkeys) might work.

This would allow all the rendering code to be split into its own system, allowing easy future extensions (3d terrain or something)
The `UnitTypes` currently contain graphics, it maybe be better to remove these and have the renderer map `UnitTypes` to graphics which would allow easier graphic modding

**Comment by TheJJ** [comment]
Jup, that should be the way to go. Currently i'm implementing the new renderer which any object registers to. The renderer then fetches all the render instructions and orders them efficiently, then submits it to the driver (using either GL3 or Vulkan).

The model (terrain, units) therefore just provide render instructions, they can even be implemented in some other subsystem and a pointer to them is returned to the renderer.

**Comment by TheJJ** [comment]
By the way, i think the current design that the "engine" is created and is then passed to some "engine-user" (in this case `GameMain`) is pretty good. We have to create clean engine features that can be used by a "game".

Of course all game features are implemented in the engine someday, but that way we can create engine features from the `GameMain` until it is empty and our structure stays clean.
