### ISSUE TITLE
Invoke conversion script from the game binary

### ISSUE THREAD

**Issue by TheJJ** [SFTtech/openage#29]
The `openage.convert` script should be invoked by the game.

The game launches its own Python interpreter to perform the conversion.
The input path could be queried interactively someday,
the output path equals the *userassets* directory which will be `~/.openage/` later.

 - Create `openage --convert` invokation
 - Load python interpreter in the game (`cpp/python.cpp`)
 - Modify `sys.path`
 - `AGE2DIR`  equals the argument to `--convert`
 - Invoke `openage.convert.__main__.main()`

**Comment by TheJJ** [comment]
This will be done by #217.

**Comment by goto-bus-stop** [comment]
This is finished, isn't it? /cc @TheJJ

**Comment by TheJJ** [comment]
Yea, it is :) Thx4hint.
