### ISSUE TITLE
Gamedata sometimes not loading

### ISSUE THREAD

**Issue by detrumi** [SFTtech/openage#290]
When loading the game for the first time since booting, the game data sometimes takes a long time to load.

I've had times where it loaded after a few minutes, and sometimes it didn't seem to load at all. And when it does load, it only takes like 5 seconds.

**Comment by TheJJ** [comment]
Probably dup of #71 #70, the "not loading at all" symptoms are new though.

The reason is you not having a SSD in your machine, in combination of us not having implemented nyan and a better data pack format. Both are things we should fix :grin:.

**Comment by detrumi** [comment]
Whoops, didn't see the similarity with #70, so I'll close this one. Thanks for the tip on SSD though, I'll move the files to my SSD (which I normally only use for windows).
