### ISSUE TITLE
Audio error when placing mill

### ISSUE THREAD

**Issue by detrumi** [SFTtech/openage#296]
I'm getting the following error when I try to place a mill (building id 574)
`ERR [T1] Error:  ERR cpp/audio/opus_dynamic_loader.cpp:53 (virtual size_t openage::audio::OpusDynamicLoader::load_chunk(int16_t *, size_t, size_t), thread 1): Could not seek in assets/converted/Data/sounds.drs/5100.opus: -131`

It's not really high priority, because it doesn't seem to disrupt the sound.
##

**Comment by franciscod** [comment]
care to post the hash of the master on which you converted the data, for reference?

**Comment by franciscod** [comment]
(we really should at least output it when converting, this is related to #79)

**Comment by detrumi** [comment]
I'm not sure what you mean. What hash are you talking about?

**Comment by franciscod** [comment]
I meant the commit hash:
`git rev-parse HEAD`

**Comment by mic-e** [comment]
`openage --version` contains the commit hash as well.

**Comment by detrumi** [comment]
I reconverted the data to be sure, and the problem still occurs.
`openage --version` gives `openage v0.2.3-238-g41ccf5b`.

**Comment by TheJJ** [comment]
is this still an issue?
