### ISSUE TITLE
Unit Attributes

### ISSUE THREAD

**Issue by Jon0** [SFTtech/openage#299]
Units currently have attributes to hold all properties of a unit instance (current HP, max HP, Attacks, Garrison space, Building completion, resource content and many more) some attributes seem to be related to the type, and others seem tied to a specific unit instance.

To fix issues with unit attributes there needs to be a clear design, there are a few of ways I can think of:

1) Unit types have default attributes and these get copied to all new units, which allows any attribute to be modified at any time without affecting other units (allows engine to be used for other game designs other than aoc, but makes it hard for things like upgrading units)

2) Unit types hold all attributes and units have a minimal set of values like current HP. Easy to handle unit upgrades but could be difficult to extend and modify the game in future.

3) Unit types and Unit instances have the same attributes, looking up attributes on a unit first checks the instance, and if not there will check the Unit Type, This does the best of both since custom attributes are supported but not required.

**Comment by mic-e** [comment]
Maybe it would be best to leave the system as is, and *wait for nyan*™, as that will most certainly change stuff.

**Comment by TheJJ** [comment]
As nyan will probably take at least half a year from now, I'd say we go for:

There's a dynamic unit attribute class which has a map from attribute->value or something.
These attributes are initialized by the gamespec, and later by the nyan data.

If mods want to add new attributes, those need to be dynamic. We thought of something that mixes both:

All attributes can be queried dynamically `bla_type->get("hp")` but that this can be optimized to `bla_type->hp`. If the engine _requires_ some attribute, it can be compiled statically. If mods add new attributes, those are only used from python code (as mods are coded in python to influence the engine) and must be dynamic.

-> Make them dynamic. Copy them as dynamic attributes. This is what we can modify best when nyan and proper modding will be implemented.

**Comment by TheJJ** [comment]
Hm, nyan is still not there yet, cause like, fucking complicated. However, the attributes are currently implemented statically with templates. Thanks @Jon0 :)
