### ISSUE TITLE
Whitespace Style: Moving to Spaces for C++ indentation

### ISSUE THREAD

**Issue by mic-e** [SFTtech/openage#313]
I'm sure you're all aware of openage's current C++ [whitespace style](https://github.com/SFTtech/openage/blob/master/doc/code_style/tabs_n_spaces.md), which involves using tabs for indentation, and spaces for alignment.

Unfortunately, due to the nature of C++, automatic checking is non-trivial, to say the least.

Almost all contributions - especially by new contributors - are plagued by whitespace issues.

For reviewers, it is annoying to manually check the style for every contribution, nag about and patiently wait for them to be fixed, but I imagine it is even more annoying for contributors who have to waste time on the ridiculous exercise of fixing them.

Switching over to a whitespace indentation style (namely: 4 spaces, similar to our PEP8 Python style) would remove many of the annoyances. A project-wide ban on tab characters could be enforced by the existing code compliance checker.

Tabs remain my personal favorite indentation style, but most editors and programmers seem to prefer indenting by spaces these days. Please share your opinions on the subject, so we may come to a satisfying solution.

If we decide to switch over to spaces, I'll implement the change in the near future. The commit would break almost all automatic merging, so I'll wait until most open pull requests have been merged.

**Comment by detrumi** [comment]
:+1: 

This would also help against the strange mixed tab/space indentation rule when spanning multiple lines.

**Comment by TheJJ** [comment]
If this is what it takes to fight all the style problems, we should do it. The space->tab [conversion trick with git](https://github.com/SFTtech/openage/blob/a1300096255cb77aeb54094751303e6fd3fef8f1/doc/code_style/tabs_n_spaces.md#solution) still works for people who can't stand space indentation.

I really like well-indented code and alignments, but most people/editors are unable to do the proposed indent rules automatically (my emacs does...), so just using spaces everywhere might be the best solution.

**Comment by sreejithr** [comment]
Barging in. Excuse me. The git technique you guys mention in [tabs_n_spaces.md](https://github.com/SFTtech/openage/blob/7061e8bf1e54df177981415cd242f2d1dbf69ef1/doc/code_style/tabs_n_spaces.md) applies to Python only, right?

I use spaces for indent in Python anyway, btw.

**Comment by TheJJ** [comment]
It applies to any file tracked by git.

**Comment by sreejithr** [comment]
@TheJJ If git converts all tabs to spaces in the repo, then why have tabs at all?

**Comment by TheJJ** [comment]
This is a setting each developer can do on his own. But because of this, yes, we're having this discussion to remove all tabs from the entire project and replace them py-like by spaces, so each dev can still autoconvert them to tabs again locally.

**Comment by franciscod** [comment]
does the space to tab reconversion handle the cases when spaces are used for alignment (and spaces for indentation too)?

**Comment by TheJJ** [comment]
I don't think so, the git conversion just converts groups of n spaces at the line-beginning to one tab.

**Comment by franciscod** [comment]
The current style is the only *correct* one, but clearly it is not the best option in the pragmatic sense. 

The JS community has settled on 2 spaces. There's also the [Linux coding style](https://www.kernel.org/doc/Documentation/CodingStyle)

I think replacing every tab with 4 spaces and implementing @mic-e solution for detecting tabs would work awesome. That whitespace checker script should also catch trailing spaces :)

**Comment by jprashanth** [comment]
Another option is to make use of [clang-format](http://clang.llvm.org/docs/ClangFormat.html)

**Comment by zuntrax** [comment]
I just had a look at clang-format, sounds like we want to use it.
If we want to stick to our current style, we should try to rig it to match our coding style. I'm not sure how much work that would be, but we might give it a try.

**Comment by mic-e** [comment]
The problem with `clang-format` is that it doesn't support checking your code, it can only re-format code, which would be pretty useless for auto-checking on travis.

**Comment by TheJJ** [comment]
Are we gonna go ahead with this?

**Comment by goto-bus-stop** [comment]
I'm :+1:, figuring out how to set up $EDITOR to do this properly/easily can be a pain.

**Comment by TheJJ** [comment]
Heh, we should think about this again, maybe git supports whitespace-only changes when rebaseing easily.

**Comment by MaanooAk** [comment]
Time for a poll!
http://www.strawpoll.me/12682914

**Comment by TheJJ** [comment]
hehe, but the options should be:
* keep as is: tab-then-alignmentwhitespace
* only whitespace, indentation level = 4spaces

**Comment by zuntrax** [comment]
Since there is no strong support for switching to spaces, I consider this closed.
