### ISSUE TITLE
Binpacking algorithm for texture arrangement

### ISSUE THREAD

**Issue by TheJJ** [SFTtech/openage#314]
https://github.com/SFTtech/openage/blob/47294b90ee5410ff4e565edb22327155cf7eb02b/py/openage/convert/texture.py#L153

Implement efficient arrangement for all the textures grouped together on a big surface.
https://en.wikipedia.org/wiki/Bin_packing_problem

**Comment by mic-e** [comment]
It's funny because the problem is NP-complete and you tagged it "easy" :D

**Comment by frickler01** [comment]
Isn't the best-fit-first approximation still pretty good and even better if you have tiles with side lengths in powers of two? I think I read something like that once.™

**Comment by Ghostbird** [comment]
It seems really weird to tag a bin-packing problem as ”Easy” and “Just do it”. It reminds me of the first guys who researched computer vision. The legend goes they made a 3 month planning for “solving” it.

**Comment by janisozaur** [comment]
See also https://www.youtube.com/watch?v=P7riQin9Bfo
