### ISSUE TITLE
convert: HD 4.0 patch compatibility

### ISSUE THREAD

**Issue by goto-bus-stop** [SFTtech/openage#318]
The HD Edition 4.0 patch changed a lot in data file storage. For example, DRS files are a thing of the past. The good part is that the new storage format is like, a million times better. The bad part is that the openage conversion script no longer works for up-to-date HD installations, and needs more special cases, probably.

I'll have time to work on this in a bit over a week, but if somebody else wants to pick it up in the mean time, feel free :smile:

**Comment by franciscod** [comment]
Are we still supporting the old format?

**Comment by goto-bus-stop** [comment]
I'd say yes, at least for a while. The 4.0 patch is very buggy so a lot of people are still on 3.9.

**Comment by janisozaur** [comment]
and for original release of the game as well?

**Comment by detrumi** [comment]
It's probably best to keep supporting the original release, as we don't want to force people to buy the HD version if they already have the old version.

We can drop 3.9 support after a while, for example when 4.1 or something comes out, as most people will update their game. But that depends on how much has changed between versions. If it's just small changes, we can keep old versions in.

**Comment by goto-bus-stop** [comment]
Yeah, absolutely, the original releases should be supported. In fact, the original releases might still be more common than HD at this point among people who want to install openage :stuck_out_tongue_winking_eye:  4.0 support would be in addition to all other releases that are currently supported, just like how HD support itself was an extra thing.

**Comment by TheJJ** [comment]
We have #61 for this to support all kinds of input configs and select them automatically. #288 will bring a filesystem abstraction comparable to [physFS](http://icculus.org/physfs/), so we will be able to use the version detection to mount all the archives (including drs) transparently for the then-following conversion.
We can support the `.cab` files from the iso the same way as the new folder structure that way `\o/`!

**Comment by mic-e** [comment]
If anyone wants to work on this, __please__ base your work on the [current pyinterface branch](https://github.com/mic-e/openage/tree/pyinterface).

There have been __so many changes__ and simplifications that merging your patch would pretty much result in a re-write.

**Comment by TheJJ** [comment]
should be fixed by #337 now
