### ISSUE TITLE
travis: use new container system

### ISSUE THREAD

**Issue by zuntrax** [SFTtech/openage#326]
http://docs.travis-ci.com/user/migrating-from-legacy/
I had a look at this, we get more processing power and VM boot should be faster.
Our main problem is that this new system disallows `sudo`, so everything we want to install has to be handled by `addon.apt`. This means everything must live in repositories.

@mic-e I heard you like rigging debian packages, how about a `python3.3-pep8` for `ppa:sfttech/random`?

Also we need to get following repos whitelisted before the transition:
`ppa:zoogie/sdl2-snapshots`
`ppa:sfttech/random`

https://github.com/travis-ci/apt-source-whitelist

**Comment by mic-e** [comment]
We don't want to have `pep8` and `pylint` as packages; we always want the most recent version of those, straight from the PyPI. Luckily you can tell `pip install` to install stuff in the home folder (somehow).

I somehow doubt that travis would whitelist a PPA that's as hacky as `ppa:sfttech/random`.

**Comment by TheJJ** [comment]
Another reason to leave travis forever and set up our own buildbot infrastructure. Seriously, containers with "trusted" PPAs and no `sudo`.

**Comment by zuntrax** [comment]
@TheJJ do it nao.

**Comment by mic-e** [comment]
It'd be regrettable if we had to drop Travis entirely, though.

**Comment by zuntrax** [comment]
If we can get one solution for ci and building releases, i'd be happy to drop travis.

**Comment by TheJJ** [comment]
We're going for #397.
