### ISSUE TITLE
Purge engine singleton

### ISSUE THREAD

**Issue by TheJJ** [SFTtech/openage#329]
In our big mission to remove all global state, we can remove the engine singleton the following way:
each subsystem, upon initialization, gets passed the engine pointer.
Member functions of this subsystem can then use `this->engine->` to access the engine instead of `auto engine& = Engine::get(); engine.bla()`.

I recommend creating a `class SubSystem { public: Engine *engine };`, and all subsystem classes that currently use the global `Engine::get` method should inherit from that one. When the subsystem gets initialized, the engine pointer is stored.

The only funny thing left to solve is the coordinate subsystem. #322 is a big improvement in that direction.
##

**Comment by amit2103** [comment]
@JJ can I work on this? Also can you or anyone point out how to identify the submodules which might need be refactored this way. Any help will be appreciated.

Disclaimer:- I am highly profiecient in JAVA and Scala. But have recently started learning C++ and looking to contribute to open source C++ games like openage.

**Comment by zuntrax** [comment]
@amit2103 Go for it. Also hello.

**Comment by amit2103** [comment]
@zuntrax  okay..Will try to catch you guys in Freenode.

**Comment by spjoe** [comment]
I suggestion using a Dependency Injection framework. With the proposed solution the Engine Object has knowledge of too much(see anti pattern God Object).

**Comment by TheJJ** [comment]
@spjoe what is a dependency injection framework? It sounds kinda intrusive :)
If you wanna strip information out of the engine (namely making some subsystems unavailable), how do we reach them then?

**Comment by spjoe** [comment]
google for "dependency injection framework" and for "inversion of control", you will find a tone of information on this subject. The idea is that you do not need to "reach" your dependencies(in our case subsystems) you get them injected during construction time.

A C++ impl. of a DI framework https://github.com/krzysztof-jusiak/di

**Comment by amit2103** [comment]
Okay..I had actually started to code this...I come from a JAVA background where DI is almost a de facto standard for wiring dependencies...I can try this with the C++ DI framework.

**Comment by spjoe** [comment]
@amit2103 it was just a suggestion, you do not have to abandon your work ;-), I have experience with big code bases and IoC helps in my opinion a lot, but it is maybe not needed here :-)

**Comment by amit2103** [comment]
Well ...it might be worth while to do it. It might be better to do now..than to do it fully and again do it :)

**Comment by TheJJ** [comment]
@amit2103 how's it going? How much work is left to do to close this issue?

**Comment by TheJJ** [comment]
@spjoe The example of this dependency injection just looks like the members shouldn't be constructed in the object itself, but somewhere else and then passed as constructor parameter. Why's that such an improvement? As always with those "pattern" thingies, I get the impression that just doing it in the intuitive and "good" way is much easier than strictly following a guide where I can apply some "pattern" next, instead of just doing it the way you think is best (and of course respect feedback etc).

**Comment by amit2103** [comment]
@TheJJ A bit more testing to see I broke something or not.

**Comment by TheJJ** [comment]
https://doc.qt.io/qt-5/qtqml-cppintegration-contextproperties.html for pushing the non-singleton into the qml then.

**Comment by ChipmunkV** [comment]
> contextproperties

That's one of the most cancerous APIs in QML. It duplicates the functionality of the QML singletons using totally different syntax. Number of context properties is usually out of control after just few weeks.

**Comment by ChipmunkV** [comment]
So, the Engine as QML singleton (as it is currently now) will work if the Engine is not a C++ singleton. GUI is created in the Engine class, so there is only one of it accessible anyway. 

In the ideal QML world there is no need to prepare any singletons in advance. It's a scripting language where you write `import openage`, declare some objects from that namespace and use them.
