### ISSUE TITLE
What should the in-game console actually do one day?

### ISSUE THREAD

**Issue by tomolt** [SFTtech/openage#353]
In my opinion, there are 3 things we could do with the console:

 1. We could make an **interactive python console**, much like the one in blender. We could use python's *code.InteractiveConsole* module in combination with cython for this.

 2. Or we could make a **terminal emulator**. We could use unix' *pipe*, *fork* and *exec* calls for running a shell like the bash *in the game*.

 3. Or we could make a **simple shell / tcl - like scripting "language"**, but I don't think this would have any advantage over a python console.

I personally like the first one the most, but I don't know how you guys think about this.

**Comment by TheJJ** [comment]
So far we planned the first. But the second is also needed for that, as you can exec zsh from the interactive console in theory, launch vim, whatever. The scripting language is python, so 3 doesn't apply i hope.
-> 1. and 2.

**Comment by tomolt** [comment]
Thanks! Maybe I'll try to implement 1. some time soon :)

**Comment by TheJJ** [comment]
Awesome!
