### ISSUE TITLE
Ship fonts with the game.

### ISSUE THREAD

**Issue by jprashanth** [SFTtech/openage#355]
By providing the fonts required for the game in the assets folder, we can remove the dependencies dejavu font and fontconfig.

**Comment by TheJJ** [comment]
Why should we? Every distro and even macos has fonts, we don't need to provide them. For the ingame-stuff which should look authentic, we might extract the font from the original files.

All other fonts should be managed by the system and provided by fontconfig.

**Comment by jprashanth** [comment]
1. We may wish to incorporate a font in the game that may not be readily available in a particular distro.
2. Packaging the game is simpler by shipping the fonts alongside assets.
3. We are forcing the user to install a system-wide font.

**Comment by TheJJ** [comment]
to 1: yes, but this is not yet the case, and if we want a particular font, it's the one from the original game data.
to 2: yes, but we won't ever bundle third party stuff. that's what dependencies are for.
to 3: no, because fontconfig selects alternatives automatically if a particular font is not available.

**Comment by franciscod** [comment]
AoE used this if I recall correctly: http://fontsgeek.com/fonts/Copperplate-Gothic-Bold-Regular

![](http://image.fontsgeek.com/preview/9xjzmb2auss36b5y99vb198fa2736fCopperplate%20Gothic%20Bold%20RegularT.gif)

**Comment by TheJJ** [comment]
Okay, but the clean way would be requesting that font from fontconfig and hoping it's there.
If not, the game will work anyway using a similar, alternative font. We can then "recommend" to install that font.

**Comment by jfeo** [comment]
Just as a note, I think Georgia is used, at least for resource counts. In any case it's a font with text figures (ie. numerals with varying height). http://fontsgeek.com/fonts/Georgia-Bold
