### ISSUE TITLE
Rendering Glitch: Purple Trees

### ISSUE THREAD

**Issue by ghost** [SFTtech/openage#359]
Running Mesa 11.0-git, Arch Linux 64bit, MATE, AMD Radeon HD 7750.

I don't remember trees being this purple in the original game. Most likely a Mesa bug.

![Purple Trees](http://i.imgur.com/M3hdd6j.png)
##

**Comment by TheJJ** [comment]
Will be addressed in #287, i'll implement outline rendering properly which should fix this.

**Comment by heinezen** [comment]
Could be caused by the original textures. Apparently "pink = transparency" is a feature of the Genie engine according to Matt Pritchard.

> In our art tools, and renderings. Transparency was always color index 255, and viewed as pink (RGB 255, 0, 255)

[Source](http://aok.heavengames.com/cgi-bin/aokcgi/display.cgi?action=st&fn=3&tn=40110&st=38#post39)

**Comment by sandsmark** [comment]
possibly this: https://github.com/SFTtech/openage/blob/master/assets/shaders/teamcolors.frag.glsl#L49

**Comment by TheJJ** [comment]
Can anyone try to reproduce and change the color in the shader?

**Comment by heinezen** [comment]
Can confirm that @sandsmark is right. When set to this:

`pixel = vec4(0.0/255.0, 0.0/255.0, 0.0/255.0, 1.0);`

Trees are no longer pink.

![openage_2017-11-14_19-04-34_00](https://user-images.githubusercontent.com/6852422/32796394-ebe0fde6-c96e-11e7-94f6-4de00c4947c7.png)

**Comment by heinezen** [comment]
On second thought, this might be a player colour that is reserved for Gaia. Gaia objects are only supposed to show outlines when a villager interacts with them. The outline of a Gaia object then gets assigned the same colour as the player colour of the villager.

**Comment by heinezen** [comment]
Pink trees should be a relic of past development by now.
