### ISSUE TITLE
Villagers don't carry resources back to Town Centre

### ISSUE THREAD

**Issue by zesterer** [SFTtech/openage#363]
Kind of self-explanatory. Although, interestingly, they do carry things back when carrying gold.
##

**Comment by mic-e** [comment]
This is an issue with a current optimization: Only droppoints in a certain distance are searched.

**Comment by zesterer** [comment]
That would make sense. My gold region was fairly closeby.

**Comment by zuntrax** [comment]
@zesterer is this still bugged for you?

**Comment by alishak** [comment]
Taking a look at the code doing the terrain search, this is the code responsible.

https://github.com/SFTtech/openage/blob/c78a6ee490656a33dc768fd69f637e547e952f59/libopenage/terrain/terrain_search.h#L18-L20

-Is there a particular reason why the search has a default limit of 500? 
-Are we worried about computing resource usage? 
-Is the intent to be able to set different search limits depending on the type of resource being carried?

**Comment by TheJJ** [comment]
If we don't limit the search, it can take a freeze the game when no building of such a kind is found. So yes, we need to watch out on not spending too much time for such calculations. The `found` function indeed evaluates if the given `TerrainObject` satisfies the search needs.

I wouldn't sink too much time in investigating this issue as we're currently revamping the whole gamestate and simulation where we will optimize pathfinding and object search (you can see progress [here](https://github.com/SFTtech/openage/projects/14)).

**Comment by simonsan** [comment]
Can be closed, should be working. Also gamestate will be new and this issue will be out of date. https://youtu.be/4GujF6YGSBY?t=89
