### ISSUE TITLE
Python 3.4 library not found on Mac OS X.

### ISSUE THREAD

**Issue by darrenstrash** [SFTtech/openage#379]
**System setup:**
Mac OS X Yosemite 10.10.4 (14E46)
Python 3.4 installed with `brew install python3`
Using g++ version 5.2.0

**The symptom:** When building the "run" executable, the linker fails with error `ld: library not found for -lpython3.4`

My investigation reveals the following:

**The superficial cause:** Python libraries are not copied to system library directories in Mac installs. And no `-Lpath` compiler option is used for compiling "run".

**The root cause:** The distutils python package is currently being erroneously used to grab the C/C++ library information. In fact, distutils is currently returning the location of libraries to *import* into python scripts. It's a coincidence that the real library name has the same name `python3.4`. Therefore, since it wasn't designed for it, distutils can't be used to the find the library's location...

**Recommendation:** We use the python configuration tool to tell us the exact linker arguments instead: (e.g., with `python$(VERSION)-config --ldflags`). While we are at it, we could grab the cflags with `--cflags` as well. This way we are always using the appropriate flags that the Python package builders meant for us to use when linking against Python. 

**Drawbacks:** This solution works with the Homebrew Python 3.4 installation on Mac OS X. However, I have observed the ldflags can sometimes contain extra -lfile libs that are not currently included in our build system, which can then lead to a similar error. This was observed with the MacPorts installation.

**Comment by franciscod** [comment]
excellent investigation report!

**Comment by TheJJ** [comment]
Would you mind doing the changes and submitting a pull request? :stuck_out_tongue: 

Your explanation sounds reasonable, but mainly the ldpath has to be extended, right? (I mean that the `-lpython3.4m` or -lpython3.4` is correct, but that our `-L"/somewhere"` is not sufficient at the moment)

**Comment by darrenstrash** [comment]
Of course! I'll make the changes. Please assign it to me :-)

**Comment by TheJJ** [comment]
Go for it. Do you wanna be "really" assigned or is it ok to tell you you're now assigned? :wink:

**Comment by darrenstrash** [comment]
Either way is fine. Making it official might be the best way to avoid duplicate work.
