### ISSUE TITLE
Compiler errors with apple clang

### ISSUE THREAD

**Issue by darrenstrash** [SFTtech/openage#382]
OSX Yosemite 10.10.4 (14E46)
clang: Apple LLVM version 6.1.0 (clang-602.0.49) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.4.0
Thread model: posix

The clang build currently fails. Here is a rundown:

1. **Easy:** function call with invalid signature in game_control.cpp
2. **Easy:** missing #include \<string\> in header files.
3. **Hard:** thread_local storage is unsupported for types with "non-trivial destructors"

**Comment by TheJJ** [comment]
Just saying, under Linux with clang version 3.7.0 it builds perfectly fine. We'd never push a version to the master that fails building on our machines, but I acknowledge that it fails for you.

But this is also the reason I can hardly test if I fixed it, as it builds for me anyway.

So you either need to fix it yourself or tell me exactly what is wrong so I can fix things without experiencing the problems.

**Comment by darrenstrash** [comment]
Interesting. I will take a look and see what the major difference is. I see on the clang website that:

"thread_local support currently requires the C++ runtime library from g++-4.8 or later." 

http://clang.llvm.org/cxx_status.html

**Comment by darrenstrash** [comment]
After some investigation, I found that Apple's clang uses *old* gcc 4.2 headers, which have very limited support for C++11. I'll investigate what it takes to use updated headers / library with clang on Mac OS X. Then we should update building.md.

**Comment by darrenstrash** [comment]
This is fixed by:

1. installing clang 3.6 with Homebrew: brew install homebrew/versions/llvm36, 
2. modifying the game_control.cpp file to fix an argument mistmatch, and
3. removing the thread_local redeclaration from compiler.h (it's for old/unsupported compilers anyway).

I will make the code changes, modify building.md, and submit a pull request.

**Comment by TheJJ** [comment]
Thanks for the investigation. Why on earth are the apple headers outdated more than a year.... Jeez.

**Comment by darrenstrash** [comment]
The brewed clang needs to be version 3.5 or higher, version 3.4 doesn't have the necessary thread_local or initializer functionality. I will change building.md to reflect this.

**Comment by TheJJ** [comment]
should be fixed now, right?

**Comment by darrenstrash** [comment]
Should be. Thanks!
