### ISSUE TITLE
Fix devmode detection by not installing __pycache__/devmode.pyc

### ISSUE THREAD

**Issue by TheJJ** [SFTtech/openage#391]
To detect if we're running in the repo or as installed program in `/usr` or whatever,
we test if the devmode python module can be imported.

The `devmode.py` file is not installed to the installation directory. That way, when running as installed program, the module can't be imported.

The problem now is that the buildsystem converts all python code to compiled `.pyc` files.
The `devmode.py` is not installed, but the `devmode.pyc` file is.

Python does import the `pyc` file even though the `.py` file is missing.

=> Prevent the buildsystem to install corresponding `pyc` files to not-installed `py` files.

**Comment by jprashanth** [comment]
#372 removes `__pycache__` installation altogether.

**Comment by TheJJ** [comment]
Hmm, didn't see that, and it's not good. Weodp want to install the compiled py objs in the pycache folder, setup.py etc does this as well.

**Comment by TheJJ** [comment]
#372 is merged now, but devmode.pyc is still installed :)
If anyone has time and motication to tinker with cmake, go for it.
