### ISSUE TITLE
Safedisc DRM support

### ISSUE THREAD

**Issue by masterofjellyfish** [SFTtech/openage#392]
As the world [looses their mind](http://hexus.net/tech/news/software/86720-safedisc-securom-drm-support-removed-windows-8-7-vista/) over the last Windows updates that enhance your Age of Empires II (R) (TM)  gaming experience, I was wondering if openage would support that too.

I think adding Safedisc Support (as well as, erm, SecuROM?) would greatly enhance the user experience. Maybe we could utilize winelib to make this happen.

Somebody could also talk with the [Sony guys](https://en.wikipedia.org/wiki/Sony_BMG_copy_protection_rootkit_scandal) who have valuable experience in designing DRM for greatest user experience. I think we could learn a lot from them.

(PS: if you haven't already guessed it: this issue is for entertainment purposes only)

**Comment by TheJJ** [comment]
What part of the game should have DRM support? Should we require a online account that needs to be connected all the time to prevent illegal copies? Should each mouse action be confirmed by the central authority servers to prevent cheating? Oh wait, openage is free software.

**Comment by TheJJ** [comment]
If we once come back to the beauty of implementing DRM, we should probably reopen this.
