### ISSUE TITLE
Better out-of-source build python support

### ISSUE THREAD

**Issue by TheJJ** [SFTtech/openage#398]
We should consider boosting the buildsystem with ideas from:

https://stackoverflow.com/questions/13959434/cmake-out-of-source-build-python-files

Basically:
- Don't rely on the source folder at all when running
- Achieve this by symlinking/copying into build directory
- This makes `make install` easier to implement and understand as the runimage already is present in the binary dir (although symlinks have to be fixed then)

**Comment by jprashanth** [comment]
I have completed this in my "part2" of buildsystem cleanup. I will open this pull request in a few days :D
