### ISSUE TITLE
Villagers have their job animation glitched when they stop such activity

### ISSUE THREAD

**Issue by shamoanjac** [SFTtech/openage#403]
Whenever I send a villager to collect a resource, and then I withdraw him/her from that activity, the animation stays in a "glitched" state. It's particularly hilarious with lumberjacks, which seem to be hitting themselves on their heads.

**Comment by TheJJ** [comment]
Hahaha nice find :grinning:

**Comment by niklasf** [comment]
Has this been fixed? I can not reproduce it.

**Comment by TheJJ** [comment]
Kay, I havent noticed it either for a while now.
If it's still a problem, we'll reopen of course.
