### ISSUE TITLE
Check for compiler's thread_local support

### ISSUE THREAD

**Issue by TheJJ** [SFTtech/openage#404]
As apple is still failing horribly with thread local storage, we should abort the build as soon as possible.

http://stackoverflow.com/questions/28094794/why-does-apple-clang-disallow-c11-thread-local-when-official-clang-supports

Something like this will detect it at configure stage:

``` cmake
include(CheckCXXSourceCompiles)
check_cxx_source_compiles("thread_local int i = 0; int main() { return i; }" HAVE_COMPILER_TLS)
if(NOT HAVE_COMPILER_TLS)
    message(FATAL_ERROR "Your compiler sucks and doesn't support thread_local storage.")
endif()
```

**Comment by jprashanth** [comment]
this issue can be closed now.

**Comment by TheJJ** [comment]
Jup, thanks for the reminder.
