### ISSUE TITLE
Converter script doesn't specify text file encoding

### ISSUE THREAD

**Issue by inakoll** [SFTtech/openage#408]
While running the convert script, [util.fslike.path](https://github.com/SFTtech/openage/blob/0f895d3dbb0058d710dd8f0a839c3677b9b7edbe/openage/util/fslike/path.py#L100-L104) doesn't specify text file encoding nor give any mean to specify one. This could lead to some unicode encoding/decoding error at some point.

The default encoding used by [TextIOWrapper](https://docs.python.org/3/library/io.html#io.TextIOWrapper) is `locale.getpreferredencoding(False)` and depending on the system this doesn't necessarily return 'utf-8' ( ;o )

To reproduce the problem simply change the system locale (change the `LANG` environment variable on Linux systems) to another locale (try `ANSIX3.4-1968`) before the convert script runs. Hopefully, the script should raise an `UnicodeEncodingError` exception at some point while trying to encode a Python unicode string...

If we know the encoding of the our files, whether we are reading or writing them, we should specify that encoding explicitly instead of relying on some [weird default system encoding](http://askubuntu.com/questions/581458/how-to-configure-locales-to-unicode-in-a-docker-ubuntu-14-04-container).

**Comment by TheJJ** [comment]
Yes, we should specify `utf-8` as the encoding of choice and store and read our converted files in that format. Reading the original files is hardcoded to be some `iso8859-1` i think, because they are shippen in that format.

**Comment by mic-e** [comment]
I had hoped that Python would always use `utf-8`, but it seems like my darkest fears turned out to be true after all.

**Comment by heinezen** [comment]
`pylint` and Python complain now if the encoding is not specified, so this should be fixed.
