### ISSUE TITLE
dead units receive damage

### ISSUE THREAD

**Issue by azrdev** [SFTtech/openage#410]
I noticed this when attacking the enemy TC with lots of archers, who currently do splash damage: When one of them is near to the TC center, where the arrows arrive, he is being damaged, and quickly dies. I had him selected at that point.
His corpse remains selected (white circle), and keeps its health bar, until it is decayed. The health bar grows unlimited from the "0" point to the left, when he receives further damage.

**Comment by franciscod** [comment]
awesome! :skull:

**Comment by TheJJ** [comment]
lol nice bug :facepunch:

**Comment by s4chin** [comment]
I'd like to take this as a first contribution.
According to me [this] (https://github.com/SFTtech/openage/blob/0ec76d35063fbe65cb8b7b8054fb8b3ee24613d3/libopenage/unit/action.cpp#L88) line has to be changed to something like
```
if ((hp.current - dmg) > 0)
    hp.current -= dmg;
else {
    hp.current = 0;
    UnitSelection().remove_unit(target); // This line is wrong but you get the idea
}
```
Can someone guide me through this?

**Comment by TheJJ** [comment]
Why do you want to remove the unit from the selection?
If the HP stay at `0`, it should be alright or am i wrong?

That said, your snippet seems to be correct after removing the selection-adjust-line.

**Comment by s4chin** [comment]
Keeping the unit selected is of no use, is it? However, AOE 2 doesn't automatically deselect units which are dead, so it should be fine if it is not removed from the selection.
Should I submit a PR?

**Comment by TheJJ** [comment]
Yes it's no use i think, but we can add the deselection sometime later when we're annoyed enough of the problem :)

Sure, go for it. Don't forget to add yourself to `copying.md`.
