### ISSUE TITLE
The game should probably use locale

### ISSUE THREAD

**Issue by ChipmunkV** [SFTtech/openage#423]
The game should call *setlocale* to set the correct locale for the libc. For now it's working entirely in C locale. (there are some hacks in run.cpp that set an OS locale to do some stuff and then set locale back to C)

I've discovered that when was integrating Qt. The Qt library calls *setlocale* and that kills all units except the sheep (probably because the data file parsing breaks).

(occurs with fr_FR.UTF-8)

**Comment by TheJJ** [comment]
Why should setlocale be called? Currently, the encoding and decoding of the data happens in the encoding specified by the system (on mine that's `en_US.utf-8`). For python, this was already reported as #408.

**Comment by ChipmunkV** [comment]
Paste that into the render loop to see the current locale:

		log::log(MSG(info) << setlocale(LC_ALL, NULL));
		log::log(MSG(info) << setlocale(LC_ADDRESS, NULL));
		log::log(MSG(info) << setlocale(LC_COLLATE, NULL));
		log::log(MSG(info) << setlocale(LC_MONETARY, NULL));
		log::log(MSG(info) << setlocale(LC_NUMERIC, NULL));
		log::log(MSG(info) << setlocale(LC_TIME, NULL));
		etc

It's "C" regarrdless of OS env settings.

**Comment by TheJJ** [comment]
I believe you, but wtf, why is that so? It happens on my system as well:
```
LC_CTYPE=en_US.UTF-8;LC_NUMERIC=C;LC_TIME=C;LC_COLLATE=C;LC_MONETARY=C;LC_MESSAGES=C;LC_PAPER=C;LC_NAME=C;LC_ADDRESS=C;LC_TELEPHONE=C;LC_MEASUREMENT=C;LC_IDENTIFICATION=C
```
The locale in the shell is different:
```
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME=en_DK.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=de_DE.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=de_DE.UTF-8
LC_NAME="en_US.UTF-8"
LC_ADDRESS=de_DE.UTF-8
LC_TELEPHONE=de_DE.UTF-8
LC_MEASUREMENT=de_DE.UTF-8
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

Why is that overridden/forgotten? SDL?

**Comment by ChipmunkV** [comment]
It was never there and it doesn't work by itself. If you write

	#include <locale.h>
	#include <stdio.h>
	int main() {printf("%s\n", setlocale(LC_ALL, NULL));}

It's set to C.

**Comment by TheJJ** [comment]
Isn't it supposed to be set by environment for all the applications? I found this:
https://www.gnu.org/software/libc/manual/html_node/Setting-the-Locale.html

So yeah, you're right, we should call it to pass the environment locales.

**Comment by leeter** [comment]
strictly speaking in C++ you shouldn't call `setLocale` instead you should call [`std::locale::global(std::locale("en_US.utf8"));`](http://en.cppreference.com/w/cpp/locale/locale/global) which internally will set the C++ and C locale

**Comment by TheJJ** [comment]
Should be fixed now, right @ChipmunkV ?

**Comment by ChipmunkV** [comment]
Fixed by setting the numeric part of the locale back to POSIX (http://doc.qt.io/qt-5/qcoreapplication.html#locale-settings).
