### ISSUE TITLE
Support shell expansions in original game path

### ISSUE THREAD

**Issue by TheJJ** [SFTtech/openage#425]
When entering the path to the original game installation, `~` and `$HOME` can't be used.

A simple replace with the environment variable value is probably sufficient.

**Comment by franciscod** [comment]
yessss this annoys us since day 0

**Comment by niklasf** [comment]
This has been fixed by @lukky513: fcc4d8fa69d49f18fafbe6e1

**Comment by TheJJ** [comment]
Wheeeeeee

**Comment by TheJJ** [comment]
Wheeeeeee
