### ISSUE TITLE
Write slp parser in cython

### ISSUE THREAD

**Issue by TheJJ** [SFTtech/openage#431]
To enhance the code optimizations, the SLP reader in `openage/convert/slp.py` should be written in cython. Currently, this is the bottleneck for the asset conversion.

And if that's too slow as well, we can think about using C++ for it...

**Comment by niklasf** [comment]
Baseline performance of graphics conversion (`python3 -m openage convert-file Age2HD/Data/graphics.drs 61.slp /tmp/test`):

```
SLP parsing/drawing     | 0.038
determine_rgba_matrix() | 0.136     Surprise (to me)!
Texture packing         | 0.002
PNG encoding/writing    | 0.031
```

**Comment by niklasf** [comment]
New stats after 30980f60edee1d8185b54946:

```
                        | Old   | New
----------------------- | ----- | -----
SLP parsing/drawing     | 0.038 |
determine_rgba_matrix() | 0.136 | 0.053
Texture packing         | 0.002 |
PNG encoding/writing    | 0.031 |
```

**Comment by TheJJ** [comment]
Done in #723
