### ISSUE TITLE
make fails for every run after the first during generating the codegen depencies because of slp.cython.so 

### ISSUE THREAD

**Issue by gitkaste** [SFTtech/openage#435]
The following should reproduce it 

    ./configure & make & make #or configure 

I get 

    [...]
     Call Stack (most recent call first):
     CMakeLists.txt:72 (doxygen_configure)

     codegeneration depends on non-.py module
     openage/convert/slp.cpython-34.so
     CMake Error at buildsystem/codegen.cmake:25 (message):
     failed to get target list from codegen invocation
     Call Stack (most recent call first):
     libopenage/CMakeLists.txt:55 (codegen_run)
   [...]

After some debugging by TheJJ it appears that during the first make run, the slp.cython.[46].so gets generated by cython and that is then taken into consideration on finding the dependencies during the second run and it fails that condition. I also want to add, that make mrproper doesn't remove these files (and some others like the gen'ed .cpp and .h files and some __init__.py files). Maybe this assumption is wrong, but in my naive view I would expect mrproper  to clean everything added by the build probcess. This would be a different issue than this one though, if it even is one.

**Comment by TheJJ** [comment]
fixed in #439
