### ISSUE TITLE
CMake Error // no module named cython on mac Mavericks

### ISSUE THREAD

**Issue by alvarosaco** [SFTtech/openage#437]
I have completed the Prerequisite steps for Mac OS X and then, when I run the command `./configure --mode=release --cpp-compiler=g++-4.9` I get the following error related to cython:
```
   CMake Error at buildsystem/modules/FindPython.cmake:29 (message):
  failed:

  /Library/Frameworks/Python.framework/Versions/3.5/bin/python3 -c 'import
  cython; print(cython.__version__)'

  Traceback (most recent call last):

    File "<string>", line 1, in <module>

  ImportError: No module named 'cython'
Call Stack (most recent call first):
  buildsystem/modules/FindCython.cmake:14 (py_exec)
  buildsystem/HandlePythonOptions.cmake:7 (find_package)
  CMakeLists.txt:57 (include)

-- Configuring incomplete, errors occurred!
```
Any help? Thanks!

**Comment by TheJJ** [comment]
Do you have cython (for python 3) installed?

**Comment by tombouctou** [comment]
`pip install cython`

**Comment by alvarosaco** [comment]
@tombouctou when I run the command pip install cython I get:
Requirement already satisfied (use --upgrade to upgrade): cython in /usr/local/lib/python2.7/site-packages

Maybe python 3 is not the default one? How can I do that? Thanks!

**Comment by iNaKoll** [comment]
Try `pip3 install cython` instead :)

**Comment by tombouctou** [comment]
@alvarosaco you can check location of python used to build runner with `cat  CMakeCache.txt | grep PYTHON_EXECUTABLE:FILEPATH` at `bin` directory

**Comment by TheJJ** [comment]
and you can interactively view and edit that while being in the `bin/` folder with `ccmake`

**Comment by alvarosaco** [comment]
Wow @iNaKoll that worked!  : ) Thanks!

Now, after run ```make```, another error appears:
> ImportError: No module named 'PIL'
> make[3]: *** [dist/openage.png] Error 1
> make[2]: *** [dist/CMakeFiles/distfiles.dir/all] Error 2
> make[1]: *** [all] Error 2
> make: *** [build] Error 2

**Comment by TheJJ** [comment]
`pip3 install pillow` should fix that, or install pillow for python 3 via your distro package manager.

**Comment by TheJJ** [comment]
I guess it should be resolved by now, if not, feel free to reopen :)

**Comment by alvarosaco** [comment]
@TheJJ that worked! Then, I run ```make run``` and I get:
>INFO [py] No converted assets have been found
>media conversion is required.
>please provide your AoE II installation dir:
> \> 

Last step? : )
Thanks!

**Comment by TheJJ** [comment]
You have to enter the directory name where your original game is installed to, [see here](https://github.com/SFTtech/openage/blob/master/doc/media_convert.md).
