### ISSUE TITLE
./configure should test for presence of pygments

### ISSUE THREAD

**Issue by d33tah** [SFTtech/openage#443]
As in the title, `./configure` passed but "make" resulted in an error that probably should have been caught earlier.

**Comment by d33tah** [comment]
@TheJJ: I don't know CMake, so "just do it" doesn't really seem to apply to me. Thanks for quick labeling though ;)

**Comment by TheJJ** [comment]
:D the checks are performed here:
https://github.com/SFTtech/openage/blob/master/buildsystem/CheckRuntimeDependencies.cmake#L8

and pygments is already in there, so i wonder why it's not detected as missing.

**Comment by d33tah** [comment]
Virtualenv maybe?

**Comment by TheJJ** [comment]
Uh, I never saw anyone to use a virtualenv for openage. So it's totally untested and may require lot's of work. Doesn't your distro allow you to install it via its package manager?
