### ISSUE TITLE
Problems coverting the assets on aoe:hd 3.5?

### ISSUE THREAD

**Issue by d33tah** [SFTtech/openage#444]
```
(virtualenv)[][15:43:30][~/workspace/openage]$[SUDO] ./run.py   
INFO [py] No converted assets have been found
media conversion is required.
please provide your AoE II installation dir:
> /home/d33tah/.wine/drive_c/Program Files (x86)/Steam/steamapps/common/Age2HD/
WARN [py] Game version(s) could not be detected in [Directory(/home/d33tah/.wine/drive_c/Program Files (x86)/Steam/steamapps/common/Age2HD/)]:
WARN [py] None supported of the Game version(s) 
 ERR [py] game asset conversion failed
```

**Comment by TheJJ** [comment]
Are you sure this is the folder containing the `AoK HD.exe`? Do you have the 4.x (current steam) version?

**Comment by d33tah** [comment]
@TheJJ: no, 3.5. Perhaps the error message should mention that?

**Comment by TheJJ** [comment]
Ah, i thought you meant Python 3.5, silly me. Please update to aoe:hd 4.x, then it'll work.
You can add support for 3.5 yourself if you want to, but not many people use it since steam autoupdates to 4.x.

**Comment by TheJJ** [comment]
Can you

**Comment by d33tah** [comment]
Sorry, can't. Could you just add a note in the error about 3.5?

**Comment by TheJJ** [comment]
For that, I'd have to detect it, which is done by looking at which files are in that folder.

**Comment by d33tah** [comment]
How about changing "game asset conversion failed" to "game asset conversion failed. Perhaps this is not a directory containing .exe file for AoE2's 4.x?"

**Comment by goto-bus-stop** [comment]
OH. there's a 3.5 "beta" version on steam. I'll PR in a minute.

**Comment by aftalavera** [comment]
converting from '/home/aftalavera/.wine/drive_c/Program Files (x86)/Steam/steamapps/common/Age2HD'
WARN [T13034957277530963224] [py] Game version(s) could not be detected in [Directory(/home/aftalavera/.wine/drive_c/Program Files (x86)/Steam/steamapps/common/Age2HD)]:
WARN [T13034957277530963224] [py] No supported game version found:
WARN [T13034957277530963224] [py]  * Age of Empires 2: The Age of Kings
WARN [T13034957277530963224] [py]  * Age of Empires 2: The Conquerors
WARN [T13034957277530963224] [py]  * Age of Empires 2: The Conquerors, Patch 1.0c
WARN [T13034957277530963224] [py]  * Age of Empires 2: Forgotten Empires
WARN [T13034957277530963224] [py]  * Age of Empires 2: HD Edition (Version 3.0+)
WARN [T13034957277530963224] [py]  * Age of Empires 2: HD + Forgotten Empires (Version 4.0+)
WARN [T13034957277530963224] [py]  * Age of Empires 2: HD + African Kingdoms (Version 4.7+)
WARN [T13034957277530963224] [py]  * Age of Empires 2: HD + Rise of the Rajas (Version 5.x)
WARN [T13034957277530963224] [py] You need at least one of:
WARN [T13034957277530963224] [py]  * Age of Empires 2: The Conquerors, Patch 1.0c
WARN [T13034957277530963224] [py]  * Age of Empires 2: Forgotten Empires
WARN [T13034957277530963224] [py]  * Age of Empires 2: HD Edition (Version 3.0+)
WARN [T13034957277530963224] [py]  * Age of Empires 2: HD + Forgotten Empires (Version 4.0+)
WARN [T13034957277530963224] [py]  * Age of Empires 2: HD + African Kingdoms (Version 4.7+)
 ERR [T13034957277530963224] [py] game asset conversion failed

Help!!!!

**Comment by TheJJ** [comment]
Pls open a new issue for that :)
It seems like `openage` could not detect any game version in that folder. What version should be in there (i.e. should there be one of the "supported game versions")?
