### ISSUE TITLE
error: implicit instantiation of undefined template (while running make)

### ISSUE THREAD

**Issue by WesleydeSouza** [SFTtech/openage#452]
While running make:

    (...)/openage/libopenage/game_renderer.cpp:85:20: error: implicit instantiation of undefined template
          'std::__1::basic_stringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >'
            std::stringstream ss;
                              ^
    /usr/local/Cellar/llvm35/3.5.1/lib/llvm-3.5/bin/../include/c++/v1/iosfwd:126:33: note: template is declared here
        class _LIBCPP_TYPE_VIS_ONLY basic_stringstream;

On Mac OS 10.11.2.

**Comment by goto-bus-stop** [comment]
This should be fixed once #447 lands :)
