### ISSUE TITLE
Converted HD Language files lang codes are wrong

### ISSUE THREAD

**Issue by goto-bus-stop** [SFTtech/openage#454]
When reading HD Edition language files in [`openage/convert/hdlanguagefile.py`](https://github.com/SFTtech/openage/blob/master/openage/convert/hdlanguagefile.py#L11), the `langcode` value is passed in as a byte string (e.g. `b'en'`, `b'fr'`) [from here](https://github.com/SFTtech/openage/blob/master/openage/convert/driver.py#L47). The lang code is then passed through [this langcode map](https://github.com/SFTtech/openage/blob/master/openage/convert/hardcoded/langcodes_hd.py) to convert to a longer language code that's compatible with the output of an AoC 1.0c language file conversion.

However, the langcode_hd map uses "normal" strings and not byte strings, so trying to access the `b'en'` property fails. And we end up with `"b'en'"` in the language field in the generated language files.

Instead, langcodes should be converted to "normal" strings beforehand, so they can be used to access the `LANGCODE_HD_MAP`.

**Comment by jamesmcm** [comment]
Is this fixed yet? The conversion works with the HD language files, at least.

**Comment by goto-bus-stop** [comment]
It is still a problem with HD 3.x and up, at least:

![](http://i.imgur.com/79DudwD.png)

The `lang` values are all `b'en'`, `b'ko'` style, whilst they should be `en_US`, `ko_KR` style

**Comment by duanqn** [comment]
@heinezen Can you verify if this bug still exists in the new converter? Can we close this issue?

**Comment by heinezen** [comment]
@duanqn Should have been fixed when we added DE2 support, but I'll check in the debugger later.

**Comment by heinezen** [comment]
Yep, it's fixed :)
