### ISSUE TITLE
Check for oggenc in ./configure

### ISSUE THREAD

**Issue by d33tah** [SFTtech/openage#460]
I just ran `./run`, tried to convert my AoE assets and got an error complaining about lack of `oggenc`. IMHO `./configure` should check for that.

**Comment by TheJJ** [comment]
`oggenc`? do you mean `opusenc`?

It should already check for that here: https://github.com/SFTtech/openage/blob/master/buildsystem/CheckRuntimeDependencies.cmake#L11

**Comment by d33tah** [comment]
Yes, opusenc, you're right. Anyway, apparently ./configure didn't crash.
