### ISSUE TITLE
Missing StackAnalyzer implementation for WIN32

### ISSUE THREAD

**Issue by franciscod** [SFTtech/openage#479]
Currently, if the `WITH_BACKTRACE` flag is set by CMake, the modern `backtrace.h` is used. Else, the GNU's `execinfo.h` is tried.

When building on MSYS2, it tries to include `execinfo.h` and fails, because `execinfo` isn't available for windows.

[Here](http://spin.atomicobject.com/2013/01/13/exceptions-stack-traces-c/) is some example code for catching exceptions and getting stack traces on windows platforms.

This should be implemented in `libopenage/error/stackanalyzer.cpp`.
##

**Comment by TheJJ** [comment]
I think it should be placed in `stackanalyzer.cpp`, that crossplattform subfolder is getting more and more suspicious to me..

**Comment by tusharpm** [comment]
Closed in #982.
