### ISSUE TITLE
Missing util/compiler implementation for WIN32

### ISSUE THREAD

**Issue by franciscod** [SFTtech/openage#480]
The `dlfcn` headers are provided by this package https://github.com/dlfcn-win32/dlfcn-win32 that wraps winapi calls into the posix api.

However, `dlfcn-win32` doesn't provide dladdr (because it is not posix, more info here https://github.com/dlfcn-win32/dlfcn-win32/issues/21) so we should work around it on WIN32.

**Comment by franciscod** [comment]
Is this crucial for the pyinterface? @mic-e @TheJJ

**Comment by franciscod** [comment]
also related to #479, there's LLVM's libunwind with a [mingw-w64 port](https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-libunwind-svn/PKGBUILD)

**Comment by TheJJ** [comment]
So the `dladdr` is missing, right? But it must be possible on windows to somehow do the symbol lookup, so we should simply add that, or am i wrong?

**Comment by franciscod** [comment]
Yeah, `dladdr` and some data structures related to the internals of `dlfcn`.

It should be possible!

**Comment by tusharpm** [comment]
Closed in #982.
