### ISSUE TITLE
Cross-platform separation

### ISSUE THREAD

**Issue by TheJJ** [SFTtech/openage#485]
Currently, we try to use the `libopenage/crossplattform` folder for switches.
But this is kinda bad, ugly and hard to maintain.

New proposal:

Do everything within the subsystem, e.g. util/, job/, ... whatever.
The things currently in crossplattform/ should be migrated there.

Within a subsystem, the switches should be as clean and few as possible, e.g. one implementation for linux, win32, etc. Basically this equals the stubbing for windows we began.

That way, the code can stay in its subsystem and, if well coded, is better to understand as the subsystem locality is maintained and code jumps are minimized.

Thoughts?

**Comment by ChipmunkV** [comment]
Didn't noticed that `libopenage/crossplattform` is shared among the subsystems.

Anyway, from the point of view of the QtQuickGUI for example, it's not desirable to put its platform-specific function into `libopenage/crossplattform`. That's because this function it's a part of a module that's not openage-specific.

**Comment by franciscod** [comment]
I agree. Maybe for complex modules it would be useful but we are dealing with fairly short code. I think the starting point is `timing.cpp` since I blew away every platform checking here #477 :dancer:

**Comment by franciscod** [comment]
And, @TheJJ, let me be the grammar nazi and point out you always spell it wrong; it is pla**t**form, not pla*tt*form! :joy:

**Comment by TheJJ** [comment]
:stuck_out_tongue:

**Comment by TheJJ** [comment]
So I'd say if somebody is interested, just purge the folder by distributing the content to the appropriate subsystem. If nothing seems to match, choose `util`.
