### ISSUE TITLE
Add Age2:HD steamcmd installation guide

### ISSUE THREAD

**Issue by TheJJ** [SFTtech/openage#488]
The Linux steam won't download Age2:HD, but there's a trick:

Downloading raw depots when you launch steam with `-console` option.

Check https://steamdb.info/app/221380/depots/ for depot information.

```
$ steam -console
steam> download_depot <app_id> <depot_id> # app_id = 221380
```
There are multiple depots for a game possible, steam usually packages languages into depots, you need to download all the depots you need.

To download the main content, you would use:
```
steam> download_depot 221380 221381
```

See guide @janisozaur wrote for another project: https://github.com/OpenRCT2/OpenRCT2/wiki/Installation-on-Linux#native

Please add the guide to our docs! :dancers:

**Comment by ChipmunkV** [comment]
Getting corrupted stuff from there: `resources/_common/drs/interface/50500.bina` - just half of the file, in `empiresdat.py` zlib complains about "incomplete or truncated stream".
