### ISSUE TITLE
Missing dependency - readline

### ISSUE THREAD

**Issue by robindegen** [SFTtech/openage#490]
While attempting to build i got the following error:

```
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/robindegen/Development/Projects/openage/openage/__main__.py", line 102, in <module>
    exit(main())
  File "/Users/robindegen/Development/Projects/openage/openage/__main__.py", line 65, in main
    from .convert.main import init_subparser
  File "/Users/robindegen/Development/Projects/openage/openage/convert/main.py", line 6, in <module>
    import readline  # pylint: disable=unused-import
ImportError: No module named 'readline'
```

I used easy_install to install readline, after that the problem was gone. The building.md file makes no mention of this dependency. I think it should be added.

I'm using OSX 10.11.2 with python 3.5.

**Comment by TheJJ** [comment]
It is a standard library module, why isn't it available on mac?

https://docs.python.org/3/library/readline.html

**Comment by robindegen** [comment]
@TheJJ I don't know? I'm not really a python user. I installed python 3.5 though macports, maybe that makes a difference; although i can't imagine why.

I can't use homebrew on my mac because it requires the user that executes it to be an administrator (not just sudo), which is a horrible requirement if you ask me.

**Comment by TheJJ** [comment]
Hmm, I have no idea how the mac ecosystem works, so I can't help you there.
However, the `readline` module really is included in the py stdlib, so I guess it's a local or packaging problem for you.

If you think we can improve things, feel free to reopen.

**Comment by arnov** [comment]
I ran into the same problem on mac, adding a manually symlink finally fixed this. 

`ln -s /usr/local/opt/readline/lib/libreadline.dylib /usr/local/opt/readline/lib/libreadline.6.dylib`

**Comment by TheJJ** [comment]
Strange. Why does mac packaging require such things?

**Comment by robindegen** [comment]
I don't think it's a problem with a mac, but a problem with the 3rd party package manager(s) that people use to install these things. osx puts nothing in /usr/local/opt by default, that's a 3rd party app doing that for sure.
