### ISSUE TITLE
How to load data from drs files

### ISSUE THREAD

**Issue by senhor** [SFTtech/openage#491]
Hi, I am working on cloning age of Empires too but mine is just an amateur hobby work. I couldn't find a way to open .drs files and handle them. How do you do this?  I couldn't find that part of code. Thanks

**Comment by TheJJ** [comment]
All the documentation is in the `doc/` folder. For the drs format, there's `./doc/media/drs-files.md`.

We already implemented all of this, so I can really encourage you not to duplicate the work and instead help us work on parts that do not exist yet. If you still got problems, feel free to reopen.

**Comment by senhor** [comment]
Thanks for answering, I have stuff to do before starting the project, I can start helping in summer. I will make you know when I am able to help.

**Comment by senhor** [comment]
Do you extract all slp files into png's before using them are do you get them from .drs files at runtime? Sorry if it is a silly question because I have trouble with reading code on phone. Thanks

**Comment by senhor** [comment]
@TheJJ I am not able to reopen :/

**Comment by TheJJ** [comment]
We extract all files into pngs before using them. And I suggest using a real computer for working with the code :wink:...

**Comment by senhor** [comment]
@TheJJ thanks for the suggestion but this is why I can't help before summer :/ my computer is broken and I am preparing for university so I can't buy a new one. One last question comes: How do you colorize png's for different players? Do you use shaders or do you create one png per one color?

**Comment by TheJJ** [comment]
We're using shaders to replace the player color on the fly, so we don't duplicate the images for each player color.

If you wanna have a more interactive chat, feel free to join our irc on `freenode.net` channel `#sfttech`.

**Comment by senhor** [comment]
@TheJJ I will visit your channel next week when I find time 👍 thanks for the invitation.
