### ISSUE TITLE
Release CXX flags

### ISSUE THREAD

**Issue by ChipmunkV** [SFTtech/openage#499]
There are some unexplained lines in `buildsystem/HandleCXXOptions.cmake`:

    set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS} -g")
    set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS}")

Why someone isn't happy with CMAKE_CXX_FLAGS_DEBUG and CMAKE_CXX_FLAGS_RELEASE that CMake provides (in gcc, for example, it's "-g" and "-O3 -DNDEBUG")?

(putting aside the fact that CMAKE_CXX_FLAGS_DEBUG is concatenated to the CMAKE_CXX_FLAGS by CMake automatically, so there is no need to append CMAKE_CXX_FLAGS second time)

Question arose because there is no "-DNDEBUG" in Release currently, and I want it back.

**Comment by TheJJ** [comment]
Not sure, we should definitely let the distro package manager decide about the release flags, but we can add `-O3` before the distro flags are inserted, so it can still be overridden.

What's with the `-DNDEBUG`, I think i never saw it. Was it ever there and why do we need it?

**Comment by ChipmunkV** [comment]
Definite thing is that's a bug in the build script that causes repetition in the compile commnd "... -Wall -Wextra -pedantic -std=c++14 -fdiagnostics-color=auto -Og  -Wall -Wextra -pedantic -std=c++14 -fdiagnostics-color=auto -Og -g -fPIC ...".

(run `make VERBOSE=1`)

NDEBUG disables asserts.

**Comment by TheJJ** [comment]
Ah, maybe the behavior was changed in a way the `CMAKE_CXX_FLAGS_DEBUG` thingy is just appended, and before that one had to set the whole debug flags in there. That's my guess why flags are repeated now. Maybe you figure out more? :)

**Comment by ChipmunkV** [comment]
If you a talking about CMake, at least ten years ago the behaviour was the same.

**Comment by TheJJ** [comment]
Kay, then it's a bug. Do you wanna do a quick fix?

**Comment by ChipmunkV** [comment]
No, I've got more interesting stuff.
