### ISSUE TITLE
Clang 3.5 can't compile openage

### ISSUE THREAD

**Issue by budicze** [SFTtech/openage#505]
I've tried to compile openage using clang 3.5 on Fedora 22 and I've got following error when compiling libopenage/game_save.cpp:

error: debug information for auto is not yet supported

It's most probably bug in clang, the solution can be to bump up the required version of clang to 3.6, where this bug is fixed.

**Comment by TheJJ** [comment]
Interesting that I never ran into this back when I had clang 3.5 installed.
Are you sure it's a 3.5 issue? Nobody else complained about this so far.

You can, of course, also compile in release mode, then the debug information wouldn't be generated in the first place.

**Comment by budicze** [comment]
Well, after conversation on IRC, I've tried to compile openage under Debian Jessie which contains clang 3.5 too and it's worked. So it's probably bug in Fedora 22.

**Comment by LinuxDonald** [comment]
Give it not and package for fedora of openage? I don't remember the repo where you could find extra packages. My fedora days are to long ago..... Maybe ask on #fedora chanel for help on freenode irc
