### ISSUE TITLE
Visual Studio 2015 build

### ISSUE THREAD

**Issue by abhijitnandy2011** [SFTtech/openage#508]
Hi,

Continuing the discussion from IRC, making a note here. I have been trying to generate the build solution using cmake here: https://github.com/SFTtech/openage/compare/master...synth2014:master

I was able to generate the solution file. It would be great if some else could give it a try too. 

There were a number of projects generated in the VS solution: http://s12.postimg.org/4tz4oiivh/projects.png

I am now trying to get rid of the 800+ errors that I get with VS 2015 community edition in libopenage: http://pastebin.com/sn5bXv4V

The changes work in Linux and the makefile, and the build completes successfully.
##

**Comment by synth2014** [comment]
Just created pull request 509.

For finding python via FindPython,cmake, there are 3 variables exported by this module:
find_package_handle_standard_args(Python REQUIRED_VARS PYTHON PYTHON_INCLUDE_DIR PYTHON_LIBRARY)

PYTHON_LIBRARY seems to contain both the library directory & library name and is hard coded for linux to
set(PYTHON_LIBRARY "-L${PYTHON_LIBRARY_DIR} -l${PYTHON_LIBRARY_NAME}")

That may need to be changed for windows to:
set(PYTHON_LIBRARY "${PYTHON_LIBRARY_DIR}/${PYTHON_LIBRARY_NAME}")
