### ISSUE TITLE
'make doc' fails, if a parent directory has a white space

### ISSUE THREAD

**Issue by castilma** [SFTtech/openage#511]
'make doc' didn't create the documentation, only a sceleton index.html. This was repeatedly written on the shell:
`Warning: tag INPUT: input source '/home/castilma/somedir/otherdir' does not exist`
`Warning: tag INPUT: input source 'withwhitespace/openage/libopenage/' does not exist"`

Where 'otherdir withwhitespace' has a space in it's name.

As a workaround I renamed the 'otherdir withwhitespace' removing the space and rerun ./configure  and 'make doc'. 

I have no experience with cmake, but I imagine there's just somewhere one line like 
.... $OPENAGE_DIR ... 
which should be
... "$OPENAGE_DIR" ...
.

**Comment by TheJJ** [comment]
Ah, it is it because you cloned openage to some folder where a parent folder has whitespace in it, right?
The place where doxygen gets multiple of the input dirs is https://github.com/SFTtech/openage/blob/7f68dc4e0c526c9dbe17bf3d39667fdb3920dc83/buildsystem/templates/Doxyfile.in#L657.

CMake creates that variable here: https://github.com/SFTtech/openage/blob/7ad1e94e8b409fb8f621b6610c82690cedd76892/buildsystem/doxygen.cmake#L37

So maybe it's enough to write `'${CMAKE_CURRENT_SOURCE_DIR}/${folder}'` there. Can you try that please?

(Btw I wanted to answer you in IRC but both times you went offline already :)

**Comment by castilma** [comment]
That did not work. I guess >'< does not work inside " "?
The warning output included the >'<.
```
Warning: tag INPUT: input source `'/home/mcd/somedir/otherdir' does not exist
Warning: tag INPUT: input source `withwhitespace/openage/libopenage/'' does not exist
```

I'm not sure if I understood correctly, so here is the git diff.
```
diff --git a/buildsystem/doxygen.cmake b/buildsystem/doxygen.cmake
index 6f42bdf..39a4393 100644
--- a/buildsystem/doxygen.cmake
+++ b/buildsystem/doxygen.cmake
@@ -34,7 +34,7 @@ function(doxygen_configure)
 
                # create doc folder name list
                foreach(folder ${ARGN})
-                       set(DOXYGEN_SCAN_FOLDERS "${DOXYGEN_SCAN_FOLDERS} ${CMAKE_CURRENT_SOURCE_DIR}/${folder}")
+                       set(DOXYGEN_SCAN_FOLDERS "${DOXYGEN_SCAN_FOLDERS} '${CMAKE_CURRENT_SOURCE_DIR}/${folder}'")
                endforeach()
 
                # adapt doxygen config
```

**Comment by castilma** [comment]
I think it is an error from doxygen. 
in bin/CMakeFiles/doc.dir/build.make:L58 I found the command that throws the warning:
`/usr/bin/doxygen "/home/castilma/somedir/otherdir withwhitespace/openage/.bin/clang++-debug-Oauto-sanitize-none/Doxyfile"`
To me it looks like for some reason doxygen interprets the argument as a space-separated list of doxyfiles. I have doxygen 1.8.6 installed. It's [git repo](https://github.com/doxygen/doxygen/releases) says, that version is from 24.24.2013. The most recent Version 1.8.11 is from 29.12.2015. Maybe I should try that Version. (I'm running Ubuntu 14.04.)

**Comment by TheJJ** [comment]
But your error message says that the input source is not correct. I think the content of the Doxyfile (which was generated and you can see the output path in your last comment) is wrongly quoted.
