### ISSUE TITLE
Update gamedata-struct.md from implementation

### ISSUE THREAD

**Issue by TheJJ** [SFTtech/openage#513]
https://github.com/SFTtech/openage/blob/master/doc/media/gamedata-struct.md

is out of date as the actual implementation was updated (mainly by me) but not the docs.
- [X] Please **synchronize the struct** from the code at https://github.com/SFTtech/openage/tree/master/openage/convert/gamedata to the documentation at gamedata-struct.md
- [ ] The implementation is straightforward and pretty much declares the complete format.
  In theory, we can even generate the documentation from that to avoid redundancy (probably best solution). All further update effort will be 0 if you **create a python script** that reads the gamedata definition from the above implementation and saves to a markdown file with a pseudo-c-struct.
##

**Comment by dufferzafar** [comment]
The python script just needs to parse in the files present in the gamedata folder (perhaps using the `ast` module) and print out the `data_format` tuple of each `Exportable` class found in the files. Right?

**Comment by TheJJ** [comment]
Yes, it could be done that way. We should change the format though, especially the "READ" and "READ_UNKNOWN" properties are redundant with the name being `None`. Then the parsing might be easier.

We will require the conversion forever™, even after we have nyan (#28) as we still have to transform the original files. So if the parsing is improved, we will benefit from it.

I wouldn't use the `ast` module or some custom parser as we have the information in valid python anyway. We can just dump the information directly.

The format can be improved by some metaclass (like `Enum` does it) then python's parser does the work an we don't need another custom parser.

**Comment by TheJJ** [comment]
I removed the file because the convert script structure resembles much more up to date information. See `openage/convert` in the repo, the structs are represented there.
