### ISSUE TITLE
Asset conversion failure Age of Kings

### ISSUE THREAD

**Issue by ShadowCreator** [SFTtech/openage#520]
```
liam@liamacer ~/Software/openage (git)-[master] % ./run                                                                                                              
INFO [py] No converted assets have been found
media conversion is required.
please provide your AoE II installation dir:
> /home/liam/Games/aoe2
WARN [py] None supported of the Game version(s) Age of Empires 2: The Age of Kings
 ERR [py] game asset conversion failed
liam@liamacer ~/Software/openage (git)-[master] %

```

I have both empires2.exe and data/empires2.dat in the instillation directory however the data folder is in upper case. Even when changing it to lower it still fails.

Is there anything else I can do to debug this issue? The game is an old cd version not a steam one.

**Comment by hamma2** [comment]
I don't think you can use the cd version yet. But you may take a look at #488 ,when you need the assets.

**Comment by TheJJ** [comment]
You can use the CD version (I use it, too), but you need to update it to Age of Conquerors patch 1.0c. We only support the file of that version, which is included in the Steam version as well.

**Comment by ShadowCreator** [comment]
I updated and it worked, thanks!
