### ISSUE TITLE
Get rid of CMAKE_PY_INSTALL_PREFIX

### ISSUE THREAD

**Issue by ChipmunkV** [SFTtech/openage#534]
Is it possible to make it dependent on the `CMAKE_INSTALL_PREFIX` to free the cmake invocation from the python details?

**Comment by TheJJ** [comment]
``` cmake
if(NOT CMAKE_PY_INSTALL_PREFIX)
	py_exec("import site; print(site.getsitepackages()[0])" PREFIX)
	set(CMAKE_PY_INSTALL_PREFIX "${PREFIX}")
endif()
```

is used to determine the prefix. Additionally, the installation `DESTDIR` is prefixed so the installed package will then have the correct python paths.

What do you have in mind freeing the invocation? I'm not aware you have to do anything about that prefix when invoking cmake.

**Comment by ChipmunkV** [comment]
`cmake -DCMAKE_INSTALL_PREFIX ../openage`

That gives:

```
   install prefix | /usr
py install prefix | /usr/local/lib/python3.4/dist-packages
```

`make DESTDIR=/abc install`

And it goes to `/abc/usr/local/lib/python3.4/dist-packages` (other stuff goes to `/abc/usr`).

**Comment by TheJJ** [comment]
So you mean we should find a common prefix of the binary and py prefix, which is then turned into `CMAKE_INSTALL_PREFIX` so both are placed in the same directory?

**Comment by zuntrax** [comment]
I don't think there is much to to about that. We need a way to specify a python prefix. If you don't want `/usr/local` in the install path you can add `/usr/lib/python3.6/dist-packages` or whatever.

**Comment by TheJJ** [comment]
Some distros place their python stuff at a completely different location for python modiles than elf executables and libraries. So I don't think we have much choice than providing both prefixes as configuration. Nevertheless, the py prefix should be calculated "intelligently" if only a changed elf prefix was provided.

I.e. the elf prefix should be used for python as well by default if an python prefix is not explicitly given.

(Another example why we need this: in gentoo the games are installed in `/usr/local/games`, but python modules must be in `/usr/lib/python...`. So we really need both.)
