### ISSUE TITLE
SDL rendering without OpenGL

### ISSUE THREAD

**Issue by Toneymoon** [SFTtech/openage#54]
It would be great to have simple SDL rendering without OpenGL for old & troubled video chips, that has no hardware acceleration for 3D & OpenGL.

**Comment by franciscod** [comment]
do we really want to mantain another rendering subsystem? i mean, opengl is pretty standard nowadays...

**Comment by mic-e** [comment]
#153 will add support for multiple rendering subsystems (targeted at Vulcan).

**Comment by TheJJ** [comment]
Due to the lack of shaders this will probably never happen. Tell me if you think otherwise.
