### ISSUE TITLE
Header inclusion minimization

### ISSUE THREAD

**Issue by TheJJ** [SFTtech/openage#548]
In order to reduce compile times and prevent cyclic includes in the first place, all our files should be revisited:
- [x] In all header files, only non-pointer or non-reference data types are included from another header
- [x] All pointer or reference data types are forward declared in each header (`class Bla;`)
- [x] In the corresponding c++ file, those incomplete types are imported by `#include "header"`

Thus, complete types are only included in files where they are needed.
Template stuff and inheritance parents etc must be included in header files directly of course.

**Comment by MaanooAk** [comment]
This could help:
```bash
find . -iname *.h -exec cppclean "{}" \;  | grep "#include"
```

![screenshot from 2017-01-11 01-14-10](https://cloud.githubusercontent.com/assets/6997990/21828865/94f20aea-d79b-11e6-9ba8-4ee398ed0a0a.png)

To install cppclean
```bash
pip install cppclean
```

**Comment by ChipmunkV** [comment]
@MaanooAk, some false positives if the traits are in separate headers.

**Comment by MaanooAk** [comment]
@ChipmunkV I know, If you somehow pass all the files in one command, should be ok but it may crash... Not perfect in any way. I just used it recently in a much smaller project and thought could help if someone tries to actually to fix the headers...

**Comment by mic-e** [comment]
We should definitely include cppclean as part of the code compliance checker. Does it produce any false positives?

**Comment by zuntrax** [comment]
First file checked was a false positive (not needing `config.h` in the assetmanager). Also crashes every few files. Might be nice for cleanups, but sadly not suitable for codecompliance.

**Comment by mic-e** [comment]
Damnit... have i mentioned how the move to modules would solve everything™

**Comment by zuntrax** [comment]
We had some discussion about this back in #263. The idea here was not forward declaring manually, but having declaration headers.

**Comment by zuntrax** [comment]
Also we should think about explicit instantiation declaration. http://en.cppreference.com/w/cpp/language/class_template

**Comment by heinezen** [comment]
The `iwyu` run in https://github.com/SFTtech/openage/pull/1525 probably resolved most of this.
