### ISSUE TITLE
Update build procedure

### ISSUE THREAD

**Issue by TheJJ** [SFTtech/openage#549]
https://github.com/SFTtech/openage/blob/master/doc/building.md#build-procedure
- [ ] The `./configure` script no longer accepts `--cpp-compiler`
- [ ] The compiler versions should not be hardcoded, but it's probably difficult writing it in another way
- [ ] Create subfiles for all the distros and operating systems, so the file is less clobbered

**Comment by edgardmota** [comment]
Hi... may I try to update this documentation? I'll probably need to discuss a little bit on how to perform some of the changes.

Thansk,

**Comment by TheJJ** [comment]
Sure, go ahead!

**Comment by edgardmota** [comment]
As `--cpp-compiler` parameter no longer exists on `./configure`, it seems that the hardcoded versions of compiler will not be an issue anymore: they only seem to be "wrongly" used altogether with `--cpp-compiler`, am I right?

Any prefered pattern to split specific os/distro build instructions on their own files? I was thinking of creating them this way on the same current path: `building_<specific-distro-or-os-name>.md`. The Idea is to provide links to them on `building.md`.

Any comment on such ideas would be nice!

Thanks,

**Comment by TheJJ** [comment]
The new `--compiler` flag is used to specify a custom compiler type/version easily. Namely, you can select `clang` instead of `gcc` that way.

If you wanna split it up, yes, great idea :)
I'd create a new directory `build_instructions/` or similar and then create files like `ubuntu.md`, `gentoo.md` and so on in there.
The `building.md` can then link to them like you suggested.

**Comment by edgardmota** [comment]
Thanks for your comments, @TheJJ! I'll pick your suggestions.
