### ISSUE TITLE
Development cycle advice?

### ISSUE THREAD

**Issue by coffenbacher** [SFTtech/openage#551]
Is this the best way to make changes?

1. Make change in .cpp
2. make
3. ./run
4. Navigate to "Generate Game" and keep pushing it until assets have loaded
5. Test behavior

Just wondering, because I've done this about 50 times tonight, and if there are any recommended shortcuts (filesystem watch to make? launch with flags to automatically load game after assets load?) that would be good to know :+1: I'm on Ubuntu.

(Forgive me, I come from interpreted language world where this is a different ballgame.)

**Comment by coffenbacher** [comment]
Well, installing a debugger helped enormously, since I don't have to rebuild so often. Any other helpful tips?

**Comment by TheJJ** [comment]
My development cycle is using tests/demos.
e.g. for working on the renderer: `make && ./run test -v --demo renderer.tests.renderer_demo 1`

You can add arbitrary amounts of tests and demos to try something you're working on, which can later directly be used to test if it still works. The tests are non-interactive and just test some algorithm/procedure/whatever. The demos are interactive and used for e.g. displaying some window and working in it.

That demo/test can also be run in gdb then to debug things.
The demos/tests bypass the "normal" main function, so all the asset loading is not required. You have to design the function in a way you can test your modification, of course (e.g. show window, display unit, ...)

**Comment by coffenbacher** [comment]
Thanks @TheJJ, good suggestions. I'll start trying to move in that direction as I get a handle on the codebase.

**Comment by TheJJ** [comment]
Cool!
