### ISSUE TITLE
Unable to exit the prefix loop during detection of AoE2 installation

### ISSUE THREAD

**Issue by elnabo** [SFTtech/openage#558]
When you use wine to detect the installation and are unable to enter a valid prefix you can't leave the loop. Or at least I didn't find how.

```
This does not appear to be a valid WINEPREFIX.
Enter a valid one, or leave it empty to skip.
WINEPREFIX=
This does not appear to be a valid WINEPREFIX.
Enter a valid one, or leave it empty to skip.
```

I was only able to leave this loop by sending a `Ctrl + C`

**Comment by goto-bus-stop** [comment]
https://github.com/SFTtech/openage/blob/master/openage/convert/main.py#L205

Given an empty string, `expand_relative_path` returns the current directory, so it doesn't break out of the loop.
