### ISSUE TITLE
Add an option to activate the glDebugMessageCallback​

### ISSUE THREAD

**Issue by ChipmunkV** [SFTtech/openage#579]
The `glGetError` calls that are in the render loop don't indicate which GL function has caused the error. So maybe we should add an option to activate the `glDebugMessageCallback​` that will be showing that function in the stacktrace?

**Comment by TheJJ** [comment]
Yes, very good idea, i was just going to ask in the other thread how we could enhance the debugability :)

**Comment by TheJJ** [comment]
done in #597
