### ISSUE TITLE
Support for multi-layer buildings (village center)

### ISSUE THREAD

**Issue by TheJJ** [SFTtech/openage#58]
Buildings like the village center consist of multiple parts so that units can walk under roofs etc.

These layers have to be represented somehow, and rendered as one single building.
The draw layer priority is secondary and should be rather easy to implement afterwards.

**Comment by franciscod** [comment]
#172 is bringing a huge part needed for having the village center: delta graphics and building annexes :D

**Comment by Jon0** [comment]
The tc works perfect in my work, its just annexes are not rendered in the editor list. The tc is found after the monestry and blacksmith in the editor list which only shows the side arms of the tc - after placement its should work.

**Comment by TheJJ** [comment]
as #172 is merged, this is more or less done.
