### ISSUE TITLE
Flickering

### ISSUE THREAD

**Issue by syrobee** [SFTtech/openage#581]
Video: https://www.youtube.com/watch?v=TZEiBMJ3IiY (warning: flickering)
Running on Debian x86_64, compiled with g++ 6.1.

**Comment by TheJJ** [comment]
I can hardly explain where this comes from. We can only hope that #287 will fix it i guess.

**Comment by syrobee** [comment]
The last revision that didn't have flickering for me was 24fc81e, then the first one that did was 49fbd1a.
I tried the revisions in-between but they gave me this:
`openage.cppinterface.exctranslate.CPPException: Failed to read CSV file /converted/string_resources.docx: Empty or missing.`
so unfortunately I can't be more specific.

**Comment by ChipmunkV** [comment]
Maybe because this line was added to `libopenage/engine.cpp`:

    SDL_GL_SetAttribute(SDL_GL_STENCIL_SIZE, 8);

**Comment by syrobee** [comment]
My mistake.
I must have missed this, but the first revision that causes flickering is 3d0b0e8.
The two revisions (5a776a6 and cb5e991) between just give a `error: ‘gui_link’ does not name a type` but I don't think that's important.

**Comment by syrobee** [comment]
I commented `SDL_GL_SetAttribute(SDL_GL_STENCIL_SIZE, 8);` and removed `GL_STENCIL_BUFFER_BIT` but it still flickers.

**Comment by ChipmunkV** [comment]
Then maybe it's `MakeCurrent()` calls. The #595 has some magical effects on that if we're lucky.

**Comment by ChipmunkV** [comment]
And one other thing, pls: what is your 3d card and driver?

**Comment by syrobee** [comment]
Nvidia GTX 760 using proprietary driver version 352.79.

**Comment by ChipmunkV** [comment]
I've got the same card, 4GiB version. The difference is KDE/Unity.

**Comment by syrobee** [comment]
Well I found out what causes it...
In my xorg.conf I have `Option "TripleBuffer" "True"` and disabling it fixes the flicker.

**Comment by syrobee** [comment]
So in my opinion this is pretty much a non-issue and can be closed.
