### ISSUE TITLE
OpenAOE

### ISSUE THREAD

**Issue by janisozaur** [SFTtech/openage#589]
Hi, there's new kid on the block, https://github.com/angered-ghandi/OpenAOE

It aims AOE1 and is written in Rust. Perhaps you could be nice and collaborate?

**Comment by elnabo** [comment]
I'm pretty sure, it would be relatively easy to use OpenAge for AoE1, mostly parsing file to extract the relevant data.

**Comment by ChipmunkV** [comment]
Seen that. Maybe he has some important reason to roll a separate project.

We need the netcode and clean up the gamedata manipulations (https://github.com/SFTtech/nyan) to get it going. Don't know how the OpenAOE can help with that.

**Comment by elnabo** [comment]
Except for AoE1 related stuff, I'm not sure that OpenAOE will be so helpfull to OpenAge, especially since it's an early project in a new language.

**Comment by ChipmunkV** [comment]
You just have to deal with the funny languages. It's one of the things that keeps people motivated. He wasn't ready to deal with our python funny language, and has started writing gamedata parsing in Rust (slp, drs, dat...).

**Comment by TheJJ** [comment]
Indeed. Of course we are open for collaboration, but it seems kinda redundant rewriting all the basic stuff once again (namely all the conversion magic). Rust may be a good choice and cool language, but it will take openaoe probably the same time as it took us fighting the original formats, and the gamedata stuff (nyan) will be the same problem for them. Would be better if it was one project, our engine can support aoe1 with way less effort than starting from scratch again.

**Comment by elnabo** [comment]
I'm not sure there is a single feature of AoE1 that is not present in AoE2 anyway

**Comment by TheJJ** [comment]
The authors of `openaoe` can surely come here for help, but I don't think we can benefit from `openaoe` except motivate the team to work for `openage` instead. But I doubt they'll like C++ (I don't either :stuck_out_tongue: )...
