### ISSUE TITLE
Build system C++14 broken

### ISSUE THREAD

**Issue by lisacvuk** [SFTtech/openage#590]
So, build system for some reason first sets -std=c++14, then -std=gnu++11, which breaks all the C++14 functions. Hackfix:
1. mkdir build && cd build
2. nano libopenage/CMakeFiles/libopenage.dir/flags.make
3. replace -std=gnu++11 with -std=gnu++14
4. Ctrl+X, Y to save any exit.
5. make

**Comment by ChipmunkV** [comment]
Should edit CMake files to use `CXX_STANDARD` and `CXX_STANDARD_REQUIRED` for CMake version > 3.1.

**Comment by TheJJ** [comment]
Uh, where does the `-gnu++11` come from? we never set it as far as I remember.

**Comment by janisozaur** [comment]
You may want to know about gcc6's defaults:

https://gcc.gnu.org/gcc-6/changes.html

> The default mode for C++ is now -std=gnu++14 instead of -std=gnu++98.

**Comment by ChipmunkV** [comment]
That's not like it can pass actual options to itself. It came from CMake scripts.

**Comment by TheJJ** [comment]
I can confirm this also happens on the archlinux machine of a friend. Strange.

**Comment by TheJJ** [comment]
Which `cmake` version do you have? I cannot reproduce it on my machine even with `cmake 3.6`.

**Comment by ChipmunkV** [comment]
Ah, it's Qt 5.7.

I saw rants about that in the release notes earlier, but totally haven't linked it to this issue (only remembered that `CXX_STANDARD` is a fix for such kind of problems).

They say that it's a bug in CMake: https://bugreports.qt.io/browse/QTBUG-53002

**Comment by TheJJ** [comment]
Can you try if #596 fixes it?

**Comment by lisacvuk** [comment]
It works. :+1:
