### ISSUE TITLE
Taking window handle on OS X is broken

### ISSUE THREAD

**Issue by Longhanks** [SFTtech/openage#593]
Concerning issue #588 (and those before them), I tried to fix building and running openage on OS X. I failed, but maybe some of what I found out may be useful.

Building actually works by including

``` Objective-C
<AppKit/AppKit.h>
```

and replacing line 17 with

``` Objective-C
NSOpenGLContext *current_context = [NSOpenGLContext currentContext];
```

No magic there. I'll submit a pull request soon.

The runtime problems are a lot worse. In gui_renderer_impl.cpp 

``` C++
QWindow *w = QWindow::fromWinId(id);
```

now actually retrieves a valid handle to the window, but using it in line 112:

``` C++
this->ctx->makeCurrent(this->render_control->renderWindow(nullptr))
```

(could be written as)

``` C++
QWindow *window = this->render_control->renderWindow(nullptr);
this->ctx->makeCurrent(window)
```

makeCurrent will dramatically fail, the engine won't stop printing stack traces.
The somewhat opaque QOpenGLContext seems to be a different class at runtime corresponding to the platform. On my OS X machine, it's actually a QCocoaGLContext, which wraps the native NSOpenGLContext.

Now, looking at the source code of [QCocoaGLContext.mm:](http://code.qt.io/cgit/qt/qtbase.git/tree/src/plugins/platforms/cocoa/qcocoaglcontext.mm)

``` Objective-C++
bool QCocoaGLContext::makeCurrent(QPlatformSurface *surface)
{
    Q_ASSERT(surface->surface()->supportsOpenGL());

    QMacAutoReleasePool pool;

    QWindow *window = static_cast<QCocoaWindow *>(surface)->window();
    setActiveWindow(window);

    [m_context makeCurrentContext];
    update();
    return true;
}

void QCocoaGLContext::setActiveWindow(QWindow *window)
{
    if (window == m_currentWindow.data())
        return;

    if (m_currentWindow && m_currentWindow.data()->handle())
        static_cast<QCocoaWindow *>(m_currentWindow.data()->handle())->setCurrentContext(0);

    Q_ASSERT(window->handle());

    m_currentWindow = window;

    QCocoaWindow *cocoaWindow = static_cast<QCocoaWindow *>(window->handle());
    cocoaWindow->setCurrentContext(this);

    [(QNSView *) cocoaWindow->contentView() setQCocoaGLContext:this];
}
```

we see that the GLContext tries to cast the QWindow to QCocoaWindow, retrieve a QNSView which wraps the internal NSView and call a method on it with itself as an argument.
Since `contentView()` returns the internal NSView (the window is of type `Qt::Window | Qt::ForeignWindow`, which, looking at [QCocoaWindow's constructor](http://code.qt.io/cgit/qt/qtbase.git/tree/src/plugins/platforms/cocoa/qcocoawindow.mm), prevents the NSView from being wrapped in a QNSView), calling `setQCocoaGLContext` will fail, as there is no such method.

By the way, implementing a stub method on the class will make the game actually launch (Objective-C supports extending existing classes), but it will stay at black screen, and losing and regaining focus will make it crash, so it seems necessary for the QCocoaGLContext to actually receive a QCocoaWindow containing a QNSView.

As far as I can see, it's neither intended nor easy to use the internal Qt classes like QCocoaWindow or QNSView, which would be what the QCocoaGLContext expects. Even if there were access, I'm not sure wrapping an existing, foreign NSView will actually work, even more so with the OpenGL stuff around it.

That's as far as I could get. I hope porting this game to other platforms is not out of scope, but I think with the current design, this won't get far on OS X.
##

**Comment by ChipmunkV** [comment]
I see `[ns_window contentView]` in `context_extraction_cocoa.mm` and `[(QNSView *) cocoaWindow->contentView() setQCocoaGLContext:this]` in `QCocoaGLContext.mm`, that looks like two times the same thing.

I've skimmed very fast over this analysis (later today I'll try to read it properly).

**Comment by Longhanks** [comment]
It's actually not. The SDLWindow is contained by a NSWindow  (just like it's contained by a X11 Window on... well, X11). A NSWindow contains a NSView, that's the view hierarchy in OS X. By calling
```Objective-C
DL_SysWMinfo wm_info;
SDL_VERSION(&wm_info.version);
NSWindow *ns_window = wm_info.info.cocoa.window;
```
We get a pointer to the NSWindow, containing the NSView.

The problem is that the QOpenGLContext, which is opaque and wraps a QCocoaGLContext, expects to get passed a QCocoaWindow, containing a QNSView, retrievable via the contentView() method. Instead, it get's a QWindow, which doesn't contain a QNSView, just a regular NSView. And this class does not support this call: `[(QNSView *) cocoaWindow->contentView() setQCocoaGLContext:this];`, which makes the application crash.

Again, I'm not sure if it's even possible to wrap existing, foreign NSWindows and NSViews into QCocoaWindows and QNSViews, certainly it's not intended, since those classes are not exposed by Qt.

**Comment by ChipmunkV** [comment]
Looks like we'll have to do the GUI rendering into an FBO.

**Comment by TheJJ** [comment]
Maybe it's time continuing and integrating that and the whole gui into the #287 thingy or vice versa. Namely OpenGL 3 stuff and abstraction.

You can pick it up if you like @ChipmunkV, should be straightforward and has a nice todo list :P

**Comment by ChipmunkV** [comment]
Does #595 help?

**Comment by Longhanks** [comment]
No, when using #595, I get this output:

> INFO Initialized SDL video subsystems.
> DBG QOpenGLFramebufferObject: Framebuffer incomplete attachment.

It's crashing here:

```C++
this->fbo = std::make_unique<QOpenGLFramebufferObject>(this->window->size(), QOpenGLFramebufferObject::CombinedDepthStencil);
```
in libopenage/gui/guisys/private/gui_renderer_impl.cpp, line 144.

**Comment by ChipmunkV** [comment]
That's an error on a pretty basic thing: creating a framebuffer.

**Comment by TheJJ** [comment]
@Longhanks Can you try again? The #595 is merged and uses one context with a separate fbo now, before it was two contexts.

**Comment by ChipmunkV** [comment]
@TheJJ, actually I remember now: second context is a possible workaround for Mac OS. It's easier to create another context than feed an existing one to the qt.

But this kind of experiments should not be in the same PR as FBO.

**Comment by dusek** [comment]
Hitting this too on macOS 10.12.1, with Qt 5.7.0 and latest master of openage (28791066f36a9fff8cf629db5738855bdc0d4cc2) after applying macOS build fixes from #648 :

```
INFO launching engine with data directory './assets' and fps limit 0
INFO SDL audio subsystems initialized
INFO Using audio device: default [freq=48000, format=32784, channels=, samples=4096]
INFO Font queried: DejaVu Serif:style=Book
INFO Font file: /Library/Fonts/DejaVuSerif.ttf
INFO Font queried: DejaVu Serif:style=Book
INFO Font file: /Library/Fonts/DejaVuSerif.ttf
INFO Initialized SDL video subsystems.
2016-11-04 19:12:50.617 run[97142:5934152] -[SDLView setQCocoaGLContext:]: unrecognized selector sent to instance 0x7fb0b885db40

FATAL: terminate has been called

uncaught exception

non-standard exception object

current stack

Traceback (most recent call last):
  File ?, in ? [0x1]
  File ?, in start+0x1 [0x7fffc1a7a255]
  File ?, in main+0x544 [0x108020344]
  File ?, in PyInit_run+0x8bd [0x10801f56d]
  File ?, in __Pyx_PyFunction_FastCallDict(_object*, _object**, int, _object*)+0x155 [0x1080205d5]
  File ?, in PyEval_EvalFrameEx+0x5ca2 [0x1080c94ee]
  File ?, in fast_function+0xdd [0x1080cd705]
  File ?, in PyEval_EvalFrameEx+0x5e1d [0x1080c9669]
  File ?, in PyCFunction_Call+0x3c [0x10806611a]
  File ?, in __pyx_pw_7openage_4game_8main_cpp_1run_game(_object*, _object*, _object*)+0xd8f [0x10adfbe9f]
  File ?, in openage::pyinterface::translate_exc_cpp_to_py()+0x15 [0x108306665]
  File ?, in __cxa_rethrow+0x63 [0x7fffc068f9f2]
  File ?, in std::__terminate(void (*)())+0x8 [0x7fffc068fd69]
  File ?, in openage::error::terminate_handler()+0x39a [0x1082ced2a]
  File ?, in openage::error::StackAnalyzer::analyze()+0x44 [0x1082cf2b4]

standard terminate handler
...infinite stream of tracebacks...
```


Displays a completely white window.

**Comment by TheJJ** [comment]
I think this is now fixed, isn't it?

**Comment by Longhanks** [comment]
Yep, I'm getting as far as #852, but the window handle seems to be fixed :)
