### ISSUE TITLE
Active player isn't displayed correctly in HUD in action mode

### ISSUE THREAD

**Issue by jazzpi** [SFTtech/openage#607]
When generating a game with default settings (player_names = name1,name2), the first player is displayed as `[1] name2` at the top, the second player as `[2] gaia` and has red crosses all over the HUD. Switching to player 3 (even though there are only two) displays `[0] name1` and the red crosses, after that it cycles again.

**Comment by zuntrax** [comment]
Good catch. Without having looked at the code, I'd guess the player number (`1` in `PLAYER_1`) is used to index the array of player names. I'll have a look into it these days.

**Comment by TheJJ** [comment]
@ChipmunkV can you fix that please?

**Comment by ChipmunkV** [comment]
@TheJJ, I thought that it would be easy to fix for someone new to the codebase. But he hasn't come yet :). So I'll go ahead.

**Comment by TheJJ** [comment]
should be fixed now with #634
