### ISSUE TITLE
Version detection for original media files

### ISSUE THREAD

**Issue by TheJJ** [SFTtech/openage#61]
The convert script should detect the present version of the original game and provide the matching file actions. This allows us to support different patch levels as 1.0c and better AOE:HD support.

@zuntrax started implementing the ideas which need to be adapted to the new codebase.

**Comment by franciscod** [comment]
more status? i'd like to help, i have the classic aoc and the HD version

**Comment by zuntrax** [comment]
There is a working prototype in my repo, I'm adding features and redesigning stuff as needed. Right now, I'm trying to unfuck `mediafile.py` in another branch.
[version_detection.py](https://github.com/zuntrax/openage/blob/version_detection/py/openage/convert/version_detection.py)
[hardcoded/version_detection.py](https://github.com/zuntrax/openage/blob/version_detection/py/openage/convert/hardcoded/version_detection.py)

**Comment by zuntrax** [comment]
the old prs are probably obsolete, i won't work on this for a while
if you want to work on this, go ahead.

**Comment by TheJJ** [comment]
I think this is mostly in place now.
