### ISSUE TITLE
What is the intended approach for an installed launch?

### ISSUE THREAD

**Issue by boombatower** [SFTtech/openage#610]
[openage.desktop](https://github.com/SFTtech/openage/blob/f9f26c83555f13138be2193c8a315758805758eb/dist/openage.desktop) file:

``` desktop
Exec=openage %u
Path=.openage
```

Which no longer works since qml files are also expected to be sitting next to `./assets`. On an installed system the qml files are in `/usr/share/openage` while the assets are in `~/.openage/assets`. Short of symlinking the assets into `/usr/share/openage` and launching the game from that directory there does not appear to be a way to run it outside of a development setup where everything is in a single directory.

Seems like there needs to be some path discovery or somesuch.

**Comment by ChipmunkV** [comment]
That's probably because I've mixed up `global_asset_dir` and the game asset directory. Should use `global_asset_dir` in `engine.cpp`.

**Comment by TheJJ** [comment]
Currently the installed version is really untested, we have to spend some time there to get it working smoothly.

**Comment by TheJJ** [comment]
Fixed by #723

**Comment by TheJJ** [comment]
@boombatower please test #723, it should improve lots of things and allow an installed run.

**Comment by TheJJ** [comment]
#723 is merged.
