### ISSUE TITLE
Add quit button

### ISSUE THREAD

**Issue by TheJJ** [SFTtech/openage#616]
One should be able to quit the game by pressing an exit button. This shall be done in the menu mode.

**Comment by vijeth-aradhya** [comment]
@TheJJ Hey, I'm new to open source and I want to start contributing. Could you please help me go about this issue?

**Comment by TheJJ** [comment]
First, I can recommend reading our README and the [contributing intro](https://github.com/SFTtech/openage/blob/master/doc/contributing.md).

Then, try building the game and afterwards try to find the code section where the current menu is generated (maybe just search for the texts you see in clickable buttons).

When you found it, play around and google a bit to add a new button at the right place.
Finally, make the button do the right thing by figuring out how other buttons do their thing (just how, not what they do).

Then, in theory, you're done :)

**Comment by marcobarbosa16** [comment]
@TheJJ Hey, I'm found just the Creation Mode, Editor Mode and Action Mode. There is a Menu Mode?

**Comment by voidestructor** [comment]
If there is no one assigned to this issue, I would like to work on it. Can you assign it to me ?

**Comment by jazzpi** [comment]
@voidestructor There's two open PRs: #620 and #621, but neither of them really work... You might want to ask the authors of those two first :wink:

**Comment by TakesTheBiscuit** [comment]
@TheJJ / @ChipmunkV - upon quit we need to instruct all player units and buildings to stop moving/producing etc? or would we have the server do this in future?
so
```
quit
-> client disconnects and gracefully exits
-> server will stop all units and buildings owned by this player
-> other players continue like normal
```

**Comment by heinezen** [comment]
@TakesTheBiscuit All the event related to the units and buildings will have to be canceled too. This probably will be the servers job because we can't always ensure that a player disconnects cleanly (e.g. when his game crashes).

**Comment by TheJJ** [comment]
For this issue, and because we have no server part, I think its enough to just add a button that then calls a function where we can do more complicated things in the future. For now, it can just call `Engine::stop()`.

**Comment by TheJJ** [comment]
Done in #990. We will have to improve this greatly to make it a 'disconnect from game' button instead of a engine killer.
