### ISSUE TITLE
Villagers should build more buildings after finishing one

### ISSUE THREAD

**Issue by jazzpi** [SFTtech/openage#626]
Just something I noticed while testing #605.

Some info on how it works is in [doc/reverse_engineering/building_placement.md](https://github.com/SFTtech/openage/blob/master/doc/reverse_engineering/building_placement.md).

**Comment by elnabo** [comment]
I'm not sure, but aren't they also supposed to repair the building they just build if it is damaged ?

**Comment by jazzpi** [comment]
Closed in #627.

I don't think they repair the buildings immediately, but if they do that should probably be a separate issue.
