### ISSUE TITLE
python3 coding style check is failing under debian/stretch

### ISSUE THREAD

**Issue by timohaas** [SFTtech/openage#635]
Hi

i did a make checkall under debian/stretch:

> python3 -m buildsystem.codecompliance --all
************* Module openage.__main__
C: 28, 0: Unnecessary parens after 'print' keyword (superfluous-parens)
************* Module openage.cabextract.cab
E:132, 0: invalid syntax (syntax-error)
************* Module openage.cabextract.lzxdstream
E: 42, 8: Missing argument to super() (missing-super-argument)
************* Module openage.cabextract.test
E: 86,23: Undefined variable 'FileNotFoundError' (undefined-variable)
E: 90,23: Undefined variable 'FileNotFoundError' (undefined-variable)
E: 94,23: Undefined variable 'IsADirectoryError' (undefined-variable)
E: 98,23: Undefined variable 'FileNotFoundError' (undefined-variable)
E:102,23: Undefined variable 'IsADirectoryError' (undefined-variable)
E:109,23: Undefined variable 'FileNotFoundError' (undefined-variable)
************* Module openage.codegen.codegen
C:145, 0: Unnecessary parens after 'print' keyword (superfluous-parens)
C:152, 0: Unnecessary parens after 'print' keyword (superfluous-parens)
C:217, 0: Unnecessary parens after 'print' keyword (superfluous-parens)
E: 51,15: Missing argument to super() (missing-super-argument)
E: 63, 8: Missing argument to super() (missing-super-argument)
E: 73,15: Missing argument to super() (missing-super-argument)
E: 88, 8: Instance of 'list' has no 'clear' member (no-member)
E: 98, 8: Instance of 'list' has no 'clear' member (no-member)
E:139,19: Undefined variable 'FileNotFoundError' (undefined-variable)
C: 11, 0: standard import "from io import UnsupportedOperation" comes before "from enum import Enum" (wrong-import-order)
C: 12, 0: standard import "from itertools import chain" comes before "from enum import Enum" (wrong-import-order)
************* Module openage.codegen.cpp_testlist
C: 11, 0: Old-style class defined. (old-style-class)
************* Module openage.codegen.gamespec_structs
E: 22,23: Class 'MultisubtypeBaseFile' has no 'structs' member (no-member)
E: 23,23: Class 'EmpiresDat' has no 'structs' member (no-member)
************* Module openage.codegen.main
E:114,15: Undefined variable 'FileNotFoundError' (undefined-variable)
************* Module openage.convert.binpack
E:158, 4: Use of super on an old style class (super-on-old-class)
************* Module openage.convert.blendomatic
E:200, 8: Missing argument to super() (missing-super-argument)
************* Module openage.convert.colortable
E: 27, 8: Missing argument to super() (missing-super-argument)
************* Module openage.convert.driver
E:152, 0: invalid syntax (syntax-error)
************* Module openage.convert.drs
E: 75, 8: Missing argument to super() (missing-super-argument)
E: 81,17: Class 'DRSHeader' has no 'read' member (no-member)
E: 92,27: Class 'DRSTableInfo' has no 'read' member (no-member)
E:122,27: Class 'DRSFileInfo' has no 'read' member (no-member)
R: 70, 0: Too few public methods (1/2) (too-few-public-methods)
************* Module openage.convert.filelist
E: 53, 8: Missing argument to super() (missing-super-argument)
************* Module openage.convert.game_versions
R:  8, 0: Too few public methods (0/2) (too-few-public-methods)
************* Module openage.convert.main
C:188, 0: Unnecessary parens after 'print' keyword (superfluous-parens)
C:201, 0: Unnecessary parens after 'print' keyword (superfluous-parens)
C:203, 0: Unnecessary parens after 'print' keyword (superfluous-parens)
C:216, 0: Unnecessary parens after 'print' keyword (superfluous-parens)
C:217, 0: Unnecessary parens after 'print' keyword (superfluous-parens)
C:231, 0: Unnecessary parens after 'print' keyword (superfluous-parens)
C:232, 0: Unnecessary parens after 'print' keyword (superfluous-parens)
C:236, 0: Unnecessary parens after 'print' keyword (superfluous-parens)
C:241, 0: Unnecessary parens after 'print' keyword (superfluous-parens)
C:263, 0: Unnecessary parens after 'print' keyword (superfluous-parens)
C:267, 0: Unnecessary parens after 'print' keyword (superfluous-parens)
C:286, 0: Unnecessary parens after 'print' keyword (superfluous-parens)
C:289, 0: Unnecessary parens after 'print' keyword (superfluous-parens)
C:292, 0: Unnecessary parens after 'print' keyword (superfluous-parens)
C:478, 0: Unnecessary parens after 'print' keyword (superfluous-parens)
C:479, 0: Unnecessary parens after 'print' keyword (superfluous-parens)
E: 41,15: Missing argument to super() (missing-super-argument)
E:374,11: Undefined variable 'FileNotFoundError' (undefined-variable)
E:384,11: Undefined variable 'FileNotFoundError' (undefined-variable)
************* Module openage.convert.pefile
C:149, 0: Old-style class defined. (old-style-class)
E:158,17: Class 'PEDOSHeader' has no 'read' member (no-member)
E:164,18: Class 'PECOFFHeader' has no 'read' member (no-member)
E:173,17: Class 'PEOptionalHeader' has no 'read' member (no-member)
E:181,43: Class 'PEDataDirectory' has no 'read' member (no-member)
E:187,22: Class 'PESection' has no 'read' member (no-member)
************* Module openage.convert.peresource
E:137,17: Class 'StringLiteral' has no 'read' member (no-member)
C:142, 0: Old-style class defined. (old-style-class)
E:167,20: Class 'ResourceDirectory' has no 'read' member (no-member)
E:174,20: Class 'ResourceDirectoryEntry' has no 'read' member (no-member)
E:202,23: Class 'ResourceLeaf' has no 'read' member (no-member)
************* Module openage.convert.slp_converter_pool
C: 26, 0: Old-style class defined. (old-style-class)
E: 32,19: Module 'os' has no 'cpu_count' member (no-member)
************* Module openage.convert.stringresource
E: 23, 8: Missing argument to super() (missing-super-argument)
************* Module openage.convert.texture
E: 94, 8: Missing argument to super() (missing-super-argument)
************* Module openage.convert.dataformat.data_definition
E: 19, 4: Use of super on an old style class (super-on-old-class)
E:107, 4: Use of super on an old style class (super-on-old-class)
************* Module openage.convert.dataformat.exportable
E:500, 0: invalid syntax (syntax-error)
************* Module openage.convert.dataformat.header_snippet
E: 13, 4: Use of super on an old style class (super-on-old-class)
************* Module openage.convert.dataformat.members
E:503, 0: invalid syntax (syntax-error)
************* Module openage.convert.dataformat.struct_snippet
E: 22, 4: Use of super on an old style class (super-on-old-class)
E: 96, 4: Use of super on an old style class (super-on-old-class)
************* Module openage.convert.gamedata.empiresdat
E:206,15: Class 'EmpiresDat' has no 'format_hash' member (no-member)
E:253,15: Undefined variable 'FileNotFoundError' (undefined-variable)
************* Module openage.convert.gamedata.sound
E: 24, 8: Missing argument to super() (missing-super-argument)
E: 45, 8: Missing argument to super() (missing-super-argument)
************* Module openage.convert.gamedata.terrain
W: 46, 0: Cannot decode using encoding "ascii", unexpected byte at position 27 (invalid-encoded-data)
E: 36, 8: Missing argument to super() (missing-super-argument)
E: 64, 8: Missing argument to super() (missing-super-argument)
E:129, 8: Missing argument to super() (missing-super-argument)
************* Module openage.convert.gamedata.unit
E:434, 8: Missing argument to super() (missing-super-argument)
E:728, 8: Missing argument to super() (missing-super-argument)
E:746, 8: Missing argument to super() (missing-super-argument)
E:763, 8: Missing argument to super() (missing-super-argument)
E:789, 8: Missing argument to super() (missing-super-argument)
E:820, 8: Missing argument to super() (missing-super-argument)
E:879, 8: Missing argument to super() (missing-super-argument)
E:902, 8: Missing argument to super() (missing-super-argument)
E:979, 8: Missing argument to super() (missing-super-argument)
E:1028, 8: Missing argument to super() (missing-super-argument)
E:1045, 8: Missing argument to super() (missing-super-argument)
************* Module openage.convert.interface.visgrep
C:151, 0: Unnecessary parens after 'print' keyword (superfluous-parens)
C:153, 0: Unnecessary parens after 'print' keyword (superfluous-parens)
************* Module openage.log.logging
R: 18, 0: Too few public methods (0/2) (too-few-public-methods)
C: 11, 0: standard import "from inspect import currentframe" comes before "from enum import Enum, unique" (wrong-import-order)
C: 12, 0: standard import "from os import environ" comes before "from enum import Enum, unique" (wrong-import-order)
C: 13, 0: standard import "from threading import Lock" comes before "from enum import Enum, unique" (wrong-import-order)
************* Module openage.nyan.parser_exception
E:  8, 8: Missing argument to super() (missing-super-argument)
************* Module openage.testing.doctest
W:  8, 0: Module import itself (import-self)
************* Module openage.testing.list_processor
E: 68, 0: invalid syntax (syntax-error)
************* Module openage.testing.main
C: 22, 0: Unnecessary parens after 'print' keyword (superfluous-parens)
C: 91, 0: Unnecessary parens after 'print' keyword (superfluous-parens)
C: 93, 0: Unnecessary parens after 'print' keyword (superfluous-parens)
************* Module openage.testing.testing
E: 68, 0: invalid syntax (syntax-error)
************* Module openage.util.bytequeue
C: 11, 0: Old-style class defined. (old-style-class)
C: 84, 0: Old-style class defined. (old-style-class)
************* Module openage.util.context
C:  8, 0: Old-style class defined. (old-style-class)
W:  8, 0: Class has no __init__ method (no-init)
************* Module openage.util.filelike
E:196, 8: Missing argument to super() (missing-super-argument)
E:233, 8: Missing argument to super() (missing-super-argument)
E:315, 8: Missing argument to super() (missing-super-argument)
E:369, 8: Missing argument to super() (missing-super-argument)
************* Module openage.util.fsprinting
W: 94, 0: Anomalous Unicode escape in byte string: '\u'. String constant might be missing an r or u prefix. (anomalous-unicode-escape-in-string)
W: 96, 0: Anomalous Unicode escape in byte string: '\u'. String constant might be missing an r or u prefix. (anomalous-unicode-escape-in-string)
W: 96, 0: Anomalous Unicode escape in byte string: '\u'. String constant might be missing an r or u prefix. (anomalous-unicode-escape-in-string)
W: 99, 0: Anomalous Unicode escape in byte string: '\u'. String constant might be missing an r or u prefix. (anomalous-unicode-escape-in-string)
W:101, 0: Anomalous Unicode escape in byte string: '\u'. String constant might be missing an r or u prefix. (anomalous-unicode-escape-in-string)
C:104, 0: Unnecessary parens after 'print' keyword (superfluous-parens)
C:106, 0: Unnecessary parens after 'print' keyword (superfluous-parens)
C:108, 0: Unnecessary parens after 'print' keyword (superfluous-parens)
************* Module openage.util.iterators
E: 29, 0: invalid syntax (syntax-error)
************* Module openage.util.math
W:  7, 0: Module import itself (import-self)
E: 13,10: Module 'openage.util.math' has no 'pi' member (no-member)
************* Module openage.util.struct
E: 82, 0: invalid syntax (syntax-error)
************* Module openage.util.threading
E: 30, 0: invalid syntax (syntax-error)
************* Module openage.util.fslike.directory
E: 49, 0: invalid syntax (syntax-error)
************* Module openage.util.fslike.filecollection
E:120, 0: invalid syntax (syntax-error)
************* Module openage.util.fslike.path
E: 90, 0: invalid syntax (syntax-error)
************* Module openage.util.fslike.union
E: 89, 0: invalid syntax (syntax-error)
************* Module openage.util.fslike.wrapper
E:129, 8: Missing argument to super() (missing-super-argument)
E:142, 8: Missing argument to super() (missing-super-argument)
************* Module buildsystem.compilepy
C: 60, 0: Unnecessary parens after 'print' keyword (superfluous-parens)
C: 61, 0: Unnecessary parens after 'print' keyword (superfluous-parens)
E: 40,20: Module 'importlib' has no 'util' member (no-member)
************* Module buildsystem.cythonize
C: 26, 0: Unnecessary parens after 'print' keyword (superfluous-parens)
C: 90, 0: Unnecessary parens after 'print' keyword (superfluous-parens)
************* Module buildsystem.inplacemodules
C: 35, 0: Unnecessary parens after 'print' keyword (superfluous-parens)
C: 44, 0: Unnecessary parens after 'print' keyword (superfluous-parens)
************* Module buildsystem.pxdgen
E: 92, 0: invalid syntax (syntax-error)
************* Module buildsystem.codecompliance.util
E: 64, 0: invalid syntax (syntax-error)
************* Module buildsystem.codecompliance.__main__
E:138, 0: invalid syntax (syntax-error)
************* Module buildsystem.codecompliance.legal
E:137, 0: invalid syntax (syntax-error)
[33;1mWARNING[m linting issue: python code is noncompliant
Makefile:126: recipe for target 'checkall' failed

**Comment by TheJJ** [comment]
Oh dear. Can you rebase on the latest master please? After you use ebcc21b, pylint is no longer executed but imported instead. Your error above may occur because it uses the python2 pylint to check our fancy new Python 3 code.

-> If you rebase, the problem will very likely go away and make checkall will pass.

**Comment by timohaas** [comment]
you are right. Issue can be closed
