### ISSUE TITLE
Improve our texture atlas packing algorithm even more

### ISSUE THREAD

**Issue by TheJJ** [SFTtech/openage#636]
We might optimize our [texture atlas generation](https://en.wikipedia.org/wiki/Texture_atlas) even more.

http://clb.demon.fi/projects/rectangle-bin-packing
http://blackpawn.com/texts/lightmaps/default.html

http://clb.demon.fi/files/RectangleBinPack.pdf

The code is located in `openage/convert/binpack.py`. If necessary, you can make a Cython `.pyx` out of it.

**Comment by heinezen** [comment]
This should be what we already do with binpacking? Either way two of the links don't work anymore.
