### ISSUE TITLE
Split the hitpoints attribute

### ISSUE THREAD

**Issue by MaanooAk** [SFTtech/openage#651]
The one attribute must be shared and have the max hp (and possibly the size of the health bar)
The other attribute not shared and have the current hp

I am happy to implement it, but I need suggestions for the names of the two attributes.

**Comment by elnabo** [comment]
How are the converted units taken into account for the max hp ?

**Comment by MaanooAk** [comment]
Converted unit are not implemented yet and in the current system the cant (because no attribute could be shared). If the converted unit must not be affected by feature upgrades, a new unit type should be created. This applies even if we don't split the hitpoints attribute.
Check the unit_type.h and keep in mind that there are more attributes that need splitting.

**Comment by TheJJ** [comment]
The units only store the concrete values for that one entity. This means their current hp, position, etc. The "class" information, i. e. information about the unit type, e.g. villager, militia, whatever are stored in nyan. Nyan is also used to handle the monk conversion by "baking" the unit type and assigning the converted unit to it. This reflects the original game behavior that converted units can't be upgraded any more.

**Comment by TheJJ** [comment]
And to come back to your original question: The Unit must have a `hp` value and (just temporarily until nyan is merged) a `unit_type_max_hp` value which is shared and then replaced by the nyan object lookup.

**Comment by MaanooAk** [comment]
`unit_type_max_hp` is quite long but ok, (I will get on it when i have some time)

**Comment by TheJJ** [comment]
If you don't like it, chose another one suitable of course :D

**Comment by MaanooAk** [comment]
This was done with #683
