### ISSUE TITLE
Trouble building on Mac

### ISSUE THREAD

**Issue by shobhitg** [SFTtech/openage#653]
I am trying to build this on Mac. And I suspect that something is not perfectly right with my qt installation. I installed it using homebrew as described in building docs.

The stdout below is complaining that `/usr/local/plugins/platforms/libqcocoa.dylib` doesn't exist. Actually the whole `plugins` folder is missing in my `/usr/local/`.

Does anyone know what am I missing? See stdout below:

```
Testing /usr/local/opt/python3/bin/python3.5
Testing /usr/local/bin/python3
Testing /usr/bin/python
Testing /System/Library/Frameworks/Python.framework/Versions/2.6/bin/python2.6
Testing /System/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Testing /usr/bin/pythonw
Testing /System/Library/Frameworks/Python.framework/Versions/2.6/bin/pythonw2.6
Testing /System/Library/Frameworks/Python.framework/Versions/2.7/bin/pythonw2.7
Testing /usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Testing /usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/bin/python3.5
Testing /usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/bin/python3.5m
Testing /usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/bin/pythonw2.7
-- Looking for suitable Python >=3.4 - Success: /usr/local/opt/python3/bin/python3.5
-- Checking python3 module PIL.Image - Success
-- Checking python3 module PIL.ImageDraw - Success
-- Checking python3 module numpy - Success
-- Checking python3 module pygments - Success
-- Checking utility program opusenc - Success

cpp library
    libopenage                                          [212 sources] [15 generated]
CMake Error at /usr/local/lib/cmake/Qt5Gui/Qt5GuiConfig.cmake:15 (message):
  The imported target "Qt5::Gui" references the file

     "/usr/local/plugins/platforms/libqcocoa.dylib"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "/usr/local/lib/cmake/Qt5Gui/Qt5Gui_QCocoaIntegrationPlugin.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  /usr/local/lib/cmake/Qt5Gui/Qt5GuiConfig.cmake:128 (_qt5_Gui_check_file_exists)
  /usr/local/lib/cmake/Qt5Gui/Qt5Gui_QCocoaIntegrationPlugin.cmake:4 (_populate_Gui_plugin_properties)
  /usr/local/lib/cmake/Qt5Gui/Qt5GuiConfig.cmake:136 (include)
  /usr/local/lib/cmake/Qt5Quick/Qt5QuickConfig.cmake:81 (find_package)
  libopenage/CMakeLists.txt:91 (find_package)

```

**Comment by ChipmunkV** [comment]
Okay, I'll try to get my hands on Mac at work.

**Comment by jazzpi** [comment]
Could you try building with #648? I believe it should fix the build although the content extraction will probably fail, so you'll be met with an infinite stacktrace when running it (protip: do Ctrl-Z then `kill -9 %1` in the terminal to quit it :wink:).

**Comment by Birch-san** [comment]
how did you install qt, and which version do you have? and is it possible that you have _multiple versions_ of qt installed?

I am confused to see that it is trying to access `/usr/local/plugins/platforms/libqcocoa.dylib`. I don't have a folder `/usr/local/plugins` on my computer. I installed qt using `brew install qt5`, as per the instructions:

https://github.com/SFTtech/openage/blob/master/doc/building.md#prerequisite-steps-for-mac-os-x-users-os-x-1010-yosemite

**Comment by Birch-san** [comment]
btw I have my own Qt-related compile errors (https://github.com/SFTtech/openage/issues/643), so probably I'm not the best person to copy.

jazzpi didn't have this problem; compilation succeeded (https://github.com/SFTtech/openage/pull/648)

**Comment by Birch-san** [comment]
@jazzpi what version of qt did you use? I've only got 5.6.2 installed. I used brew, and _as far as I know_, there are no other versions of qt on my computer installed by any other means.

```bash
➜  ~ ls /usr/local/Cellar/qt5 
5.6.2
```

**Comment by jazzpi** [comment]
@Birch-san 5.7.0 I believe. Did you try building with #648 or only with your own fixes?

**Comment by Birch-san** [comment]
@jazzpi I have not checked to see whether your #648 produces any improvement in my environment. I built using just my own fixes. but I have a feeling they would be equivalent.

**Comment by shobhitg** [comment]
@Birch-san I installed by `brew install qt5` as well. And it ended up installing 5.7 for me.

**Comment by Birch-san** [comment]
that's weird. My brew is up-to-date, my OS X is up-to-date, and I ran those commands only days ago. I wonder why it gave me an older `qt5`.

**Comment by Birch-san** [comment]
> Did you try building with #648 or only with your own fixes?
@jazzpi Okay! I tried again with qt 5.7.0 instead. It builds! I used dusek's branch (#658), which is based on your fixes (but also incorporates feedback from the comments that followed).
