### ISSUE TITLE
Bountysource plugin broken

### ISSUE THREAD

**Issue by coffenbacher** [SFTtech/openage#661]
I don't see the bounty button showing up on new issues, and on old issues it's broken:

![image](https://cloud.githubusercontent.com/assets/245867/19877169/f760c9f8-9f99-11e6-866b-be27d7087f03.png)

Kinda stupid problem, but I intend to place some bounties and hopefully get other people to join me eventually, so relevant 😄

**Comment by TheJJ** [comment]
I'm not sure if we want to keep bountysource. The 10% share for almost no value contribution is very high in my opinion. On the other hand, I don't know an alternative.

Until now we had almost no bounties over all the years, so I'm not sure whether we should continue this. Also, many of the solutions were done by multiple people, so splitting up the bounty somehow won't be easy.

**Comment by coffenbacher** [comment]
Good point re: bounties being hard to assign to a person at the moment. After thinking about it, I agree / think the bountysource model may be counterproductive at the moment, since the development is still so foundational.

If a little financial support would ever help with development, feel free to ping me with a plan (are any of you guys co-located? Maybe have a party for a milestone or something). I can't help efficiently w/ development at the present stage because my skills don't intersect with the problem set yet but I'm happy to help however else I can, whether it's some money, legwork, coordination, or general cheerleading !
