### ISSUE TITLE
Efficient storage of unit positions

### ISSUE THREAD

**Issue by TheJJ** [SFTtech/openage#689]
We have to store the unit positions efficiently, so they are rendered and interacted with on demand only.
We might want to use our chunks for that.
Currently, all units are contained in the `class UnitContainer` in the `live_units` map.

The new hierarchy should be bound to our chunks to allow better local search for neighbors.

https://en.wikipedia.org/wiki/Quadtree

**Comment by lilezek** [comment]
Should not the quadtree be built again each time a unit moves across chunks?

**Comment by zuntrax** [comment]
We can choose a suitable bucket size to avoid that. For example if you allow up to 20 units per bucket, a less populated area of the map might have 4 chunks folded together, while in a crowded battle. this might go down to buckets corresponding to a single tile. @TheJJ did I get your  idea right?

Also, in this context, does unit mean something that can move around, or does it also refer to buildings, trees, and gold mines?

**Comment by lilezek** [comment]
@zuntrax then you don't need a quadtree , but an static partition of the space. A quadtree is built from the interesting points. If the interesting points (units) can move from one chunk to another, quadtree must be rebuilt to keep the balance of the structure. 

You can build a quadtree of buildings because they won't move. You only have to update quadtree each time a new building is built or destroyed, which may be efficient, but I don't see the point of doing it. 

By the way, static partition of map can only be done in fixed-size maps.

**Comment by zuntrax** [comment]
I think @TheJJ just wanted to have a rather coarse partition of space, dynamically subdividing it in the more busy areas. Using a quadtree for this seems reasonable at the first glance, but I just skimmed the Wikipedia article, so I might be completely wrong.

**Comment by lilezek** [comment]
The quadtree structure does not depend of the space but the points you want to classify. If you have 100 units in a 3-sized map and 100 units in a 8-sized map, the quadtree is the same for those two maps if those 100 units are placed in the same way. Adding a single unit to any of those quadtrees may change the entire structure, which under some circumstances will be less efficient than having an array of units.

**Comment by zuntrax** [comment]
From what I understand, this would be pretty much a point-region-quadtree.

**Comment by lilezek** [comment]
@zuntrax Yes, you are right.

**Comment by zuntrax** [comment]
Here are two other ways of storing this kind of information.
https://en.wikipedia.org/wiki/K-d_tree
https://en.wikipedia.org/wiki/R-tree
I will sit down with @TheJJ this evening and we will have a discussion and clarify the constraints we need to fulfill.

**Comment by heinezen** [comment]
We now use [curves](https://github.com/SFTtech/openage/blob/master/doc/code/curves.md) for unit positions. Whether they are efficient may be debateable but I'd say it's pretty good :)
