### ISSUE TITLE
build cython generated files with reduced warnings

### ISSUE THREAD

**Issue by zuntrax** [SFTtech/openage#702]
After upgrading the compiler, there are often lots of warnings about generated code. We need a sane way of silencing this, preferably by setting seperate compiler flags for handwritten and generated code.

**Comment by TheJJ** [comment]
What compiler and version complains this much? My `clang-3.9.1` was quite silent (except the `numpy` deprecation warning)

**Comment by TheJJ** [comment]
That's rather quiet :)

**Comment by zuntrax** [comment]
Well, those deprecated numpy api warnings would go away, and we would have a pretty build on debian stretch with g++. Also, on Arch, every now and then, clang starts emitting new warnings, and I don't want to be bothered with stuff i can't fix. We've had a bunch of warnings for quite a while, and nobody seems to be interested in fixing them.
Honestly, I'd like to run one of the kevin builds with `-Werror` just to raise awareness.
