### ISSUE TITLE
single file conversion for other file types

### ISSUE THREAD

**Issue by zuntrax** [SFTtech/openage#703]
Currently, only SLP files are supported. Exporting opus files and other stuff would be nice.

**Comment by TheJJ** [comment]
I added an interactive prompt to the convert script where you can explore the archives and extract stuff.
(in #723, commit 56bf018cf8172181e24f55d887f552329eff7236)
It's launched by:

```
python3 -m openage convert --interactive --source-dir ~/where/your/origina/game/is
```
