### ISSUE TITLE
blacklist pythontex in the buildsystem

### ISSUE THREAD

**Issue by zuntrax** [SFTtech/openage#708]
Pythontex is some kind of a python interpreter bundled with texlive. CMake finds it, but it's not suitable for what we are doing (obviously). We should blacklist it to get rid of clutter in the configure output. Also the "dropping invalid python interpreter" message (for the remaining possible cases) should not be a warning, but a normal message without modifiers.

<details>
<summary>Configure output</summary>
<pre>
[...]
Testing /usr/bin/python3
Testing /usr/bin/python3.6
Testing /usr/bin/python2.7
Testing /usr/bin/python3.6m
Testing /usr/share/texmf-dist/scripts/pythontex/pythontex.py
usage: pythontex.py [-h] [--version] [--encoding ENCODING]
                    [--error-exit-code {true,false}] [--runall [{true,false}]
                    | --rerun {never,modified,errors,warnings,always}]
                    [--hashdependencies [{true,false}]] [-j N] [-v]
                    [--interpreter INTERPRETER]
                    [--debug [<family>:<session>:<restart>] | --interactive
                    [<family>:<session>:<restart>]]
                    TEXNAME
pythontex.py: error: unrecognized arguments: -c
CMake Warning at buildsystem/modules/FindPython.cmake:149 (message):
  Dropping invalid python interpreter
  '/usr/share/texmf-dist/scripts/pythontex/pythontex.py'
Call Stack (most recent call first):
  buildsystem/HandlePythonOptions.cmake:6 (find_package)
  CMakeLists.txt:69 (include)
[...]
</pre>
</details>

**Comment by TheJJ** [comment]
Done in #723
