### ISSUE TITLE
Blacklist ASDF in the compliance checker as invalid

### ISSUE THREAD

**Issue by TheJJ** [SFTtech/openage#710]
@mic-e and I started to write `ASDF` or `asdf` in the code to denote things that must be changed before the pull request is merged. This is mainly to mark something so we can easily find it again.

To prevent accidential merges of code containing `asdf`, the compliance checker should reject it. You have to implement that in `buildsystem/codecompliance`.

Yes, currently there's `asdf` in the upstream code, and we need to get rid of it. The `global coordinate asdf` is resolved by #662.

**Comment by Btjones711** [comment]
Hi I am new to GitHub and contributing but I am a fan of RTS games and this project. I would like to help and contribute and starting with some of these code compliance issues seems like a good place to start. For this issue does this include all files from python to C++ that may have "asdf" in them? And is the best way to go about this to create a python program that checks files for asdf and then remove it if found?

I am currently studying other buildsystem files to try and learn what I can do.

Thanks!

**Comment by TheJJ** [comment]
ohai!
Yes, it basically means that the compliance check should fail if anywhere in the code there's an `asdf` or `ASDF`.
I would put this check in `buildsystem/codecompliance/textfiles.py` as another regular expression. Then you can generate a warning like "found asdf which indicates immediate todos". This warning is already treated as fatal when the continuous integration runs (see the `.kevin` file).

**Comment by Btjones711** [comment]
Awesome I will look into that! Thanks for the help!

**Comment by Btjones711** [comment]
![asdffix](https://cloud.githubusercontent.com/assets/21178349/22438273/f4326892-e6f0-11e6-83e4-4221931671b6.png)

Does this code look like it is correct and in the appropriate place in buildsystem/codecompliance/textfiles.py?

Thanks!

**Comment by TheJJ** [comment]
That looks like it's a nice place :)
The logic is wrong, unfortunately:
``` Python
if "asdf" or ...:
    # this is always true as "asdf" is true.
```
So you wanna do something like:
``` Python
if any(asdf in data for asdf in ("ASDF", "asdf")):
```

But that means that this file may contain an ASDF, so you have to extend that check:
``` Python
if any(...) and not filename.endswith(__file__):
```
`__file__` is a built-in magic variable that has the value of the current filename.

The filename check may be a bit more complicated to account for the resolving of relative paths etc.
This is done with the [`os.path`](https://docs.python.org/3/library/os.path.html) functions, but I'm not sure if you'll need them. Just test :)

Btw it should say `immediate`, a small typo.

**Comment by Btjones711** [comment]
Thank you for the quick reply and helping me learn! I'll make the changes and then run some tests!

**Comment by Btjones711** [comment]
Hey sorry I have been looking at the code and trying to devise a way to test my new addition. Is the best way to test the whole compliance checker or to create a unit test with a fake document containing asdf?

**Comment by TheJJ** [comment]
As this is part of the buildsystem, I fear our testing infrastructure doesn't work there. So i would just experiment if it detects the present asdfs in the code, and be done with it. The algorithm isn't too complicated so it's probably not worth adding test infrastructure just for that.

**Comment by Btjones711** [comment]
When I run the __main__ file in codecompliance I do not seem to be getting errors. I should expect some files containing asdf right? What would be the best way to test it? I have tried running the python file and calling it in terminal.

 I will attach my edited code.

![image](https://cloud.githubusercontent.com/assets/21178349/22478892/6b6d86b0-e7b1-11e6-8cee-36bd7dbb273d.png)

**Comment by TheJJ** [comment]
You should be in the `openage/` folder and then execute `python3 -m buildsystem.codecompliance --textfiles`. Before the `and` there should be a space, btw. If you run `python3 -m buildsystem.codecompliance --all`, it should show you this error.

I see you are on windows, so you may have problems to interact with the project. The above command should work, though.

**Comment by Btjones711** [comment]
![image](https://cloud.githubusercontent.com/assets/21178349/22492611/402ca3d4-e7f0-11e6-8177-01b3bc0e8fd5.png)

Hi JJ,

Thanks for the help! I have attached a screenshot of the test working and my finished code! Should I create a pull request?

**Comment by TheJJ** [comment]
Yes please. Don't forget to add yourself to `copying.md` etc (if in doubt, look at our `doc/contributing.md`).

**Comment by zuntrax** [comment]
Done in #776.
