### ISSUE TITLE
Provide support for building openage under a virtualenv

### ISSUE THREAD

**Issue by samkellett** [SFTtech/openage#715]
Bug to document issues uncovered when building under a virtualenv.

The first issue found from my attempt is that virtualenv ships it's own site.py which doesn't have getsitepackages defined. This appears to be a known issue for python 2.7 (see pypa/virtualenv#355) -- I can't see much online about this still being the case in python 3.6 but it definitely seems to be for me.

TensorFlow had this problem and fixed it by using the inspect module instead of site, [see here](https://github.com/tensorflow/tensorflow/pull/702) for details.

**Comment by samkellett** [comment]
Another potential alternative to getsitepackages: http://stackoverflow.com/a/29062571/649140

**Comment by TheJJ** [comment]
Fixed in #1031
