### ISSUE TITLE
convert: Support HD Edition terrain textures

### ISSUE THREAD

**Issue by goto-bus-stop** [SFTtech/openage#720]
HD Edition has different terrain textures than 1.0c. They're now pngs that are transformed during render to fit the terrain:

![g_uwtr_00_color](https://cloud.githubusercontent.com/assets/1006268/22264723/45c0011e-e279-11e6-9ed5-30f00391cc87.png)

Textures are found in `<Age2Dir>/resources/_common/terrain/textures`.

Older HD Edition versions also still shipped with 1.0c's terrain SLP files, but they were removed as of patch 4.8. Currently, users have to downgrade to patch 4.3 before running the conversion.

I suppose to convert these new textures, they need to be cut up and transformed to generate the same output as the SLP conversion.

Interesting data:

 - The texture names seem to be derived from the `name1` attribute on Terrains. eg. the `g_wtr` texture name is `g_wtr_00_color.png`.
 - The SLP id of the obsolete textures is still present on Terrain data from HD 4.8. So that could be used to map the texture name to an appropriate output file.

**Comment by TheJJ** [comment]
Which is actually cool in that far that we finally have to implement actual perspective terrain rendering and blending. Because we should rather convert the old perspective diamond to the actual square tile. See #141.

**Comment by Jon0** [comment]
Squares would be good, then you can implement 3d terrain rendering with isometric transorms in the shaders. would make terrain elevation quite easy to implement too.

**Comment by heinezen** [comment]
Should be implemented by https://github.com/SFTtech/openage/pull/1497
