### ISSUE TITLE
Google Summer of Code 2017

### ISSUE THREAD

**Issue by TheJJ** [SFTtech/openage#724]
I proposed SFTtech/openage as mentoring organization for the summer of code 2017.
To enhance the experience for students, we should:

* [x] Gather mentors (that means YOU! if you contributed larger parts of the code (@ChipmunkV, @Jon0, @mic-e, @zuntrax, @fr3akout, and more))
* [x] Complete our application until `February 09, 2017 at 17:00 UTC`
* [x] Think about work packages for students
  * The flow field pathfinder (#366)
  * Web frontend for our Kevin-CI (SFTtech/kevin#15)
  * Engine preparation for nyan (#734)
  * Networking with curve transmission (#530)
  * ...
* [ ] Create informational website for gsoc information, we could maybe use the github wiki if we're incompetent for web development.
  * To avoid information duplication we should mainly use the issue tracker
  * Do we need more information that we should put on the wiki?

**Comment by elnabo** [comment]
I didn't contribute a lot to the code, but if you need I could help on the side.

**Comment by ChipmunkV** [comment]
Can make the serialization-deserialization-playback layer of the #530 into a task. It's RTS-fundamental and has a well-defined result: viewing the game on another client.

**Comment by TheJJ** [comment]
Unfortunately, we were not selected as mentor organization. We'll try again next year :)

(I must admit, we didn't put enough energy into the application, but at least I was very busy)
