### ISSUE TITLE
./configure can't find opus even though it is installed on Fedora 25

### ISSUE THREAD

**Issue by kaiser-dg** [SFTtech/openage#733]
I have all the dependencies installed yet, whenever I run ./configure it claims it cannot find opus.

**Comment by kaiser-dg** [comment]
NVM, turns out a symlink to the library as libopus.so fixed it. Just fedora being weird I guess.

**Comment by kaiser-dg** [comment]
Now when make runs, it can't find opus_multistream.h and I can't find it either. Am I missing something?

**Comment by TheJJ** [comment]
Uh, no idea. On our arch/debian/gentoo boxes it works, so i assume you're missing some dev package on fedora?

**Comment by LinuxDonald** [comment]
An quick Google search say the file is in opus-devel package.

**Comment by kaiser-dg** [comment]
I have opus development though. Also, is there a way to get it to link libopus.so.0 instead of libopus.so? It won't even take a symlink to libopus.so.0.

**Comment by TheJJ** [comment]
This is done by `buildsystem/modules/FindOpusfile.cmake`, where the call to [`find_library`](https://cmake.org/cmake/help/v3.4/command/find_library.html) locates the file. CMake should succeed to find symlinked files and any libopus.* found in your library paths. Is the file in some non-standard path?

**Comment by kaiser-dg** [comment]
No, just /lib (or /usr/lib or /usr/lib64)

**Comment by TheJJ** [comment]
I can't really help you, this is some issue between your distro and cmake. Can you play around with our `FindOpusfile.cmake` please? Other than that, I cannot give you advice what else to try except maybe using a different distro.
They all reinvent all the wheels over and over again, but some do it worse than others.

**Comment by TheJJ** [comment]
If you need further help, please ask.
