### ISSUE TITLE
pxdgen sometimes runs multiple times when building on multiple cores

### ISSUE THREAD

**Issue by mic-e** [SFTtech/openage#739]
This has potentially dire consequences (maybe it hasn't, but are we sure it's just cosmetical?), and the cause must be identified and eliminated.

    mic@mic ~/git/openage $ make -j4
    [  0%] Automatic moc for target libopenage
    [  1%] pxdgen: generating .pxd files from headers
    [  1%] pxdgen: generating .pxd files from headers
    Scanning dependencies of target libopenage
    ...

**Comment by TheJJ** [comment]
fixed
