### ISSUE TITLE
ROR question : population limit

### ISSUE THREAD

**Issue by Wandalen** [SFTtech/openage#741]
Maybe somebody can give a hint which file/files of ROR contains information about population limit / unit cap?

**Comment by goto-bus-stop** [comment]
In AoE 1 and 2, the possible population limits are hardcoded into the executable. Is that what you mean?

**Comment by Wandalen** [comment]
Yes, thank you @goto-bus-stop. In single player of ROR population limit bound strictly to 50. @goto-bus-stop, do you have idea which binary? Empiresx.exe, probably?

**Comment by goto-bus-stop** [comment]
Yeah, that should be in the empires.exe for your game version. I'm not very familiar with AoE1 so I'm afraid I can't tell you more (and it's also kind of off-topic for this issue tracker). The [AoE HeavenGames forum](http://aoe.heavengames.com/cgi-bin/aoecgi/index.cgi) is probably the best place to ask for specifics.

**Comment by Wandalen** [comment]
Thank you for help guys. Please close 👍

**Comment by Wandalen** [comment]
Amazing ROR in [AoE II](http://aok.heavengames.com/blacksmith/showfile.php?fileid=12722) skin :)
