### ISSUE TITLE
Male villager idle graphics

### ISSUE THREAD

**Issue by MaanooAk** [SFTtech/openage#748]
In the villager idle graphics we can see a knife-like-thing. So the current default idle graphics should go to the attack idle graphics and we should find the idle graphics without the knife.

Also, the idle loops in the original had a frame which lasted 1-2s and the rest at normal rate, is this something openage will have too?

**Comment by TheJJ** [comment]
Jup, all the animation speed and graphics need to be fixed. I'd not invest too much time fiddling around with it, as nyan will completely overhaul it.

**Comment by heinezen** [comment]
This should be fixed in the new renderer and gamestate implementation.
