### ISSUE TITLE
First Run Documentation Doesn't Match Actuality

### ISSUE THREAD

**Issue by Enverex** [SFTtech/openage#752]
The documentation states that you'll be asked where the assets are the first time you run the game so that it can convert them, I'm not getting that at all, just an error that doesn't even make sense:

```
usage: openage [-h] [--version] {game,test,convert,convert-file,codegen} ...
openage: error: directory does not exist: ./assets
```

The part that doesn't make sense is "directory does not exist: ./assets" because even if I create a folder named ".assets" on the current folder, I still get the same error, so I assume it's looking elsewhere (but again no information on where).

Running something like "openage convert" instead still just results in the same error.

What exactly is the process to convert assets and run the game once you have installed OpenAGE on Linux?

**Comment by TheJJ** [comment]
I'm currently totally overhauling the asset search in #723 (just now debugging funny exceptions).

Did you follow the `doc/building.md` guide? It should work if you follow the procedure to build and run from the git repo directly. The `make install` variant is very broken and my above pull will finally fix it.

**Comment by Enverex** [comment]
I was using the Arch build for this (https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=openage-git - although slightly modified, because that build without edits will literally render your system unbootable by breaking /usr/lib64 for some odd reason).

Anyway, this uses the make install method which is likely where the problem lies then. Is your advice to follow the "Development" rather than "Release" section of the guide for now then?

**Comment by TheJJ** [comment]
Yes, the release will work after my changes are merged. Try the development method pls.
(btw wtf would that pkgbuild break the system...)

**Comment by ChipmunkV** [comment]
`./assets` is the directory that comes with the source code, I think.

**Comment by Enverex** [comment]
@TheJJ Apparently make install creates a /usr/lib64 folder which overwrites the /usr/lib64 symlink that already exists which in turn breaks mkinitcpio which breaks kernel updates which then breaks booting. Bit of a long-winded but potentially catastrophic mess. Really should be fixed in the PKGBUILD rather than anything that needs to be sorted here though.

Trying the dev release directly from GIT now.

**Comment by Enverex** [comment]
Well, that seemed to convert everything happily and the game starts, but then it crashes out when clicking "generate_game". I'll leave it for now as it looks like you guys are in the middle of rewriting a bunch of things.

**Comment by TheJJ** [comment]
Can you post the crash trace you encountered? The master version should always work. At least when running in the source tree.

**Comment by Enverex** [comment]
Sorry for the delay:

```
INFO launching engine with data directory './assets' and fps limit 0
INFO SDL audio subsystems initialized
INFO Using audio device: default [freq=48000, format=32784, channels=2, samples=2048]
INFO Initialized SDL video subsystems.
INFO Compiled with Qt 5.8.0 and run with Qt 5.8.0
INFO loading configuration files...
INFO [py] loading config file /home/ben/Games/openage/cfg/keybinds.oac...
INFO Loading time [engine]: 1.438 s
INFO Loading time   [game]: 1.538 s
INFO [T1] Loading multi csv file: gamedata.docx
INFO [T1] Loaded csv files: 115100
WARN [T1]    file ./assets/converted/terrain/15001.slp.png is not there...
WARN [T1]    file ./assets/converted/terrain/15002.slp.png is not there...
WARN [T1]    file ./assets/converted/terrain/15017.slp.png is not there...
WARN [T1]    file ./assets/converted/terrain/15007.slp.png is not there...
WARN [T1]    file ./assets/converted/terrain/15014.slp.png is not there...
WARN [T1]    file ./assets/converted/terrain/15000.slp.png is not there...
WARN [T1]    file ./assets/converted/terrain/15004.slp.png is not there...
WARN [T1]    file ./assets/converted/terrain/15005.slp.png is not there...
WARN [T1]    file ./assets/converted/terrain/15009.slp.png is not there...
WARN [T1]    file ./assets/converted/terrain/15011.slp.png is not there...
WARN [T1]    file ./assets/converted/terrain/15006.slp.png is not there...
WARN [T1]    file ./assets/converted/terrain/15008.slp.png is not there...
WARN [T1]    file ./assets/converted/terrain/15010.slp.png is not there...
WARN [T1]    file ./assets/converted/terrain/15033.slp.png is not there...
WARN [T1]    file ./assets/converted/terrain/15029.slp.png is not there...
WARN [T1]    file ./assets/converted/terrain/15015.slp.png is not there...
WARN [T1]    file ./assets/converted/terrain/15016.slp.png is not there...
WARN [T1]    file ./assets/converted/terrain/15018.slp.png is not there...
WARN [T1]    file ./assets/converted/terrain/15019.slp.png is not there...
WARN [T1]    file ./assets/converted/terrain/15024.slp.png is not there...
WARN [T1]    file ./assets/converted/terrain/15021.slp.png is not there...
WARN [T1]    file ./assets/converted/terrain/15022.slp.png is not there...
WARN [T1]    file ./assets/converted/terrain/15023.slp.png is not there...
WARN [T1]    file ./assets/converted/terrain/15026.slp.png is not there...
WARN [T1]    file ./assets/converted/terrain/15027.slp.png is not there...
WARN [T1]    file ./assets/converted/terrain/15028.slp.png is not there...
WARN [T1]    file ./assets/converted/terrain/15030.slp.png is not there...
WARN [T1]    file ./assets/converted/terrain/15031.slp.png is not there...
INFO [T1] Loading game specification files...
INFO [T1] Loading time  [data]: 16.199 s
INFO gaia has civilisation Gaia
INFO name1 has civilisation British
INFO name2 has civilisation French
INFO freeing GUI...
INFO GUI was reset
INFO Cleanup gamemain
WARN Cleanup container
Traceback (most recent call last):
  File "run.py", line 15, in init run (/home/ben/Games/openage/run.cpp:1055)
    main()
  File "/home/ben/Games/openage/openage/__main__.py", line 97, in main
    return args.entrypoint(args, cli.error)
  File "/home/ben/Games/openage/openage/game/main.py", line 47, in main
    return run_game(args, assets)
  File "openage/game/main_cpp.pyx", line 26, in openage.game.main_cpp.run_game (/home/ben/Games/openage/openage/game/main_cpp.cpp:1155)
    result = run_game_cpp(args_cpp)
  File "", line 0, in 
  File "", line 0, in openage::run_game(openage::main_arguments const&)+0x48c
  File "", line 0, in openage::Engine::run()+0x1f
  File "", line 0, in openage::Engine::loop()+0x363
  File "", line 0, in openage::GameRenderer::on_draw()+0x5d
  File "", line 0, in openage::Terrain::draw(openage::Engine*, openage::RenderOptions*)+0x26f
  File "", line 0, in openage::Texture::draw(openage::coord::tile, unsigned int, int, openage::Texture*, int) const+0xac
  File "", line 0, in openage::Texture::draw(int, int, unsigned int, bool, int, unsigned int, openage::Texture*, int) const+0xf6
  File "", line 0, in openage::Texture::get_subtexture(int) const+0xfb
  File "", line 0, in openage::error::Error::Error(openage::log::message const&, bool, bool)+0x152
  File "", line 0, in openage::error::StackAnalyzer::analyze()+0xb6
  File "libopenage/texture.cpp", line 358, in const gamedata::subtexture* openage::Texture::get_subtexture(int) const
    throw Error(MSG(err) <<
openage.cppinterface.exctranslate.CPPException: Unknown subtexture requested for texture ./assets/missing.png: -1145602496
process 984: arguments to dbus_connection_close() were incorrect, assertion "connection->generation == _dbus_current_generation" failed in file dbus-connection.c line 2935.
This is normally a bug in some application using the D-Bus library.
  D-Bus not built with -rdynamic so unable to print a backtrace
Aborted (core dumped)
```

Asset import was done (and completed) using the AoE2HD contents from Steam.

**Comment by TheJJ** [comment]
Kay, then I'll have to redirect you to #682 :)

**Comment by Enverex** [comment]
Ouch, well that was a waste of a 5GB download (which is odd given that the Steam store says it only needs 2GB of space).

So the fix for now then is to switch to the old beta version and re-run the converter? May be worth adding this rather big caveat to the front-page documentation.

Additionally, do you know the exact name of the beta branch? I'm using steamcmd so I can't "see" what they are and steamdb.info doesn't seem to list them either.

**Comment by goto-bus-stop** [comment]
Yeah, switch to the old version and rerun. I can't check atm but IIRC the branch name is `patch-43`

**Comment by goto-bus-stop** [comment]
Sorry, it's `patch43`. @Enverex

**Comment by Enverex** [comment]
Thanks @goto-bus-stop - I'll keep an eye on the other threads in the meantime.

**Comment by TheJJ** [comment]
The original problem (the asset folder) is now fixed.
