### ISSUE TITLE
Enforce proper comment format?

### ISSUE THREAD

**Issue by castilma** [SFTtech/openage#771]
The comment style inside libopenage is pretty mixed. Have a look on these comments:
unit_type.h:48:
```
/**
 * UnitType has to main roles:
 *
 * initialise(unit, player) should be called on a unit to give it a type and the required attributes, abilities and initial actions
 * of that type
 *
 * place(unit, terrain, initial position) is called to customise how the unit gets added to the world -- used to setup the TerrainObject location
 *
 * UnitType is connected to a player to allow independent tech levels
 */
class UnitType {
```
unit_type.h:68:
```
        /**
         * gets the parent id of this unit type
         * which is used for village base and gather types
         */
```

path.h:23:
```
/**
 * The data type for movement cost
 */
```
path.h:39:
```
/**
 * Cost comparison for node_pt.
 * Extracts the ptr from the shared_ptr.
 * Calls operator < on Node.
 */
```
All except the last comment lack punctuation. While reading them in source, this does not matter because of the linebreaks. In doxygen, however, simple linebreaks vanish.
The second comment is missing proper capitalization.
I think, the last one is pretty ok. If there is something that deserves a fancy comment, `@param` etc. can be used.
From `code_style/mom.cpp` I thought the fourth comment style was the only way to go, but then, in line 122:
```
private:
        /** links to the story of the game */
        Story *story;
```
(private ?) attributes may be commented in lower-case without punctuation?

So, how strict are we with comment-styles?

**Comment by TheJJ** [comment]
I'm glad if people write useful comments at all :) However, yes, I agree the "best looking" style is the punctuated one, and I think we should use it.
The `mom.cpp` is buggy, it shoule be `/** Links to the story of the game. */`

It's hard to enforce the comment style easily, I'd have to be very picky, which annoys contributors. Any suggestions how we could improve stuff? (maybe even add a codecompliance module for comment style...)

**Comment by TheJJ** [comment]
If you like, you may fix the codestyle guide bug and use a proper comment style there.
Next step would be, although with way more effort, to write a codecompliance module and fix the comments all over the codebase.

**Comment by castilma** [comment]
Can you give me hint, how to check inside comments, if every sentence has a fullstop?

**Comment by TheJJ** [comment]
Hard to tell, I mean it's impossible without natural language processing to tell where sentence boundaries are... To enforce that there's at least one `.` is also kinda strange, but I doubt it's worth the effort and pissing off contributors if we're so fascist about comment style.

How would you proceed? The longer I think about it, the worse the idea of forcing comment style seems, especially if we want to allow things like ascii art and whatever in the comments to explain things. Then the pxd annotations, etcetc. I'm really unsure what the best way is to "fix" this. Maybe just check if there's at least one dot, and if not, complain "comments are sentences with full-stop", then people that don't dot at all will have to add at least one, and others already wrote sentences.

However, we shouldn't annoy people too much that do write comments. Hmmmm.

**Comment by TheJJ** [comment]
How should we proceed here? Further ideas on what we shall change or integrate in the compliance check?

**Comment by castilma** [comment]
Maybe test for one full-stop and if there is none, print a message kindly asking for at least proper punctuation?

**Comment by TheJJ** [comment]
So how do we want to proceed here? Be happy if people comment at all or enforce a comment style and fix the whole codebase to adhere to it?

It's hard to guess if the advantage of enforcing the style outperforms the amount of fixing existing docstrings. And I'm sure there will be loads of exceptions in the enforced style (think of ascii-art drawings etc).

**Comment by simonsan** [comment]
I would totally support that. Today I fixed the comment format in 116 files from // TODO to // \todo for doxygens todolist input. To enforce a basic comment format lets the automatically generated doc benefit in great way in the future. I know that this is some kind of annoying if you just want to code for a project, but I would mark that having good comments in a project with so many different (new) contributors makes it way easier for (also new) people in the future.

To establish a basic workflow regarding commenting your own code is a good habit. Some good habits:

- inline comments should not be used, put it rather in front or after a function or on an extra line above the line you're talking it about

- write your code, but write you doc commentary immediately afterwards in the way you want to read it even after months of not working on the code

- formatting comments for doxygen might be a good idea, here you'll find a good overview of doxygens commands: http://www.doxygen.nl/manual/commands.html

Also some situations give an indication that you should write a comment (from "Weniger schlecht programmieren", O'Reilly)

- the code shows unexpected behaviour
- the code has to be worked on, but you don't have time for it
- the code could be just used in a limited area of application
- there were lines of code you had to comment out
- you already tried an obvious choice that was not working out
- if a solution looks complicated, give a justification ("program needs 75% less memory")
- if you already know that you could do something wrong and couldn't test it
- if you use alien code

I think we should make a nice overview of ways to document your code, also out of the docs that are already there and place it somewhere obvious (getting started, developing openage or so).

**Comment by TheJJ** [comment]
we do on demand enforcement by code review, a ruleset seems very impractical :)
