### ISSUE TITLE
Make not working

### ISSUE THREAD

**Issue by bradleyJohnson55** [SFTtech/openage#772]
I followed the steps for the build procedure, but when I get to "make" in the terminal, it stops at 88% and I get these errors.

![openage_error](https://cloud.githubusercontent.com/assets/26680994/24327637/fbe54752-118a-11e7-9703-981c4e32738d.png)

Using Ubuntu 16.04 LTS

How do I proceed?
Thanks

**Comment by castilma** [comment]
I'm on Ubuntu 16.04. Building from commit 93f9022c works. 
My libopenage/util/path.pxd looks like yours. Maybe try updating cython:
`pip3 install --upgrade cython`

**Comment by TheJJ** [comment]
See #773, you need `cython >=0.25`, sorry :)

**Comment by TheJJ** [comment]
Was the cython update successful? Did it build afterwards?

**Comment by bradleyJohnson55** [comment]
Yes, it was successful. Thank you!
