### ISSUE TITLE
File format documentation incomplete

### ISSUE THREAD

**Issue by aap** [SFTtech/openage#781]
I've been working on documenting the .dat files lately, check out:
https://github.com/aap/geniedoc
Sorry this is not a PR but I wanted to compile everything in one place in the same style and didn't want to write it twice. I hope you find it helpful.

**Comment by TheJJ** [comment]
The implementation of this is in `openage/convert/`, documentation in `doc/media/`. Would be cool if you could add missing pieces to our documentation or code :)

**Comment by TheJJ** [comment]
we added many more data conversions
