### ISSUE TITLE
Problems building after removing Anaconda

### ISSUE THREAD

**Issue by tejasjadhav** [SFTtech/openage#803]
**Operating system:** Ubuntu 16.04 (64-bit)
**System Python Path:** `/usr/bin/python`
**Anaconda Path:** `/opt/anaconda3/bin/python`

I forked this repository and pulled the latest code on my local machine. I had Anaconda installed already at `/opt/anaconda3` with its binary path in my `$PATH` variable. When I first ran `./configure` I had some issues with Anaconda (sorry I don't remember what issues I had). So, I decided to switch my Python interpreter to the one that comes with Ubuntu at `/usr/bin/python`. I removed Anaconda's Python Path from my `$PATH` variable in `.zshrc`, `.bashrc` and `.bashrc_profile` and restarted my machine. However, when I ran `./configure` again, it still picked Anaconda's Python binary instead of `/usr/bin/python`. I even ran `python` manually in the same session but it correctly picked Ubuntu's Python binary instead of Anaconda's.

I got annoyed and removed Anaconda completely and this time it correctly picked Python binary from `/usr/bin/python`. But, I started getting other issues now. It seems the build system was still looking for Anaconda's libraries (I don't know why and how). The build system even had couple of issues with `libfreetype6-dev` library which could be solved only by symlinking the include files in the right places

But now, I'm stuck with this nasty one.
```
make[3]: *** No rule to make target '/opt/anaconda3/lib/libfontconfig.so', needed by 'libopenage/libopenage.so.0'.  Stop.
CMakeFiles/Makefile2:1482: recipe for target 'libopenage/CMakeFiles/libopenage.dir/all' failed
make[2]: *** [libopenage/CMakeFiles/libopenage.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make[1]: *** [all] Error 2
Makefile:33: recipe for target 'build' failed
make: *** [build] Error 2
```

I've completely removed Anaconda and `which python` returns `/usr/bin/python`. Does anyone has a slightest idea of what's going wrong?

**Comment by zuntrax** [comment]
I assume cmake chose `/opt/anaconda3/lib/libfontconfig.so` to satisfy the fontconfig dependency (which should not have happened). After removing Anaconda, this file does not exist, so cmake tries to build it. This obviously won't work.
Try `make mrproper && ./configure`. It might just work since Anaconda is no longer there.

However, we need to investigate why cmake found Anaconda's libfontconfig and how to suppress that.

**Comment by tejasjadhav** [comment]
@zuntrax Thanks a ton, mate! `make mrproper && ./configure` solved it. If I can reproduce Anaconda's issue again in future, I'll definitely create another issue and keep you'll updated,
