### ISSUE TITLE
Remember previous asset location

### ISSUE THREAD

**Issue by TheJJ** [SFTtech/openage#807]
After a "successful" conversion, we could store the location of the source folder in `root/cfg/asset_location` so that upon the next conversion, that folder will be reused by default.

Implementation should probably be in:
* `openage/convert/main.py`
* and pass the full `root` path to the `conversion_required` in `openage/game/main.py` (currently it's just `root/assets` but we wanna have `root/cfg` there to read and write the file)

**Comment by Chinmaygoyal** [comment]
Is the issue still open?

**Comment by heinezen** [comment]
@Chinmaygoyal Functionality was merged with #921 so I think this can be closed.
