### ISSUE TITLE
make compiler issues on os x

### ISSUE THREAD

**Issue by iezed** [SFTtech/openage#817]
Hello, on osx 10.10.5, I have this error:
```
make[3]: *** No rule to make target `/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/Pillow-4.1.1-py3.5-macosx-10.6-intel.egg/PIL/_binary.py', needed by `codegen_timefile'.  Stop.
make[2]: *** [libopenage/CMakeFiles/codegen.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [build] Error 2
```

any tips? Thanks.

**Comment by TheJJ** [comment]
Does the file `/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/Pillow-4.1.1-py3.5-macosx-10.6-intel.egg/PIL/_binary.py` exist?
Did you use the `./configure` script?

My guess is that the file no longer exists after you updated Python?

**Comment by iezed** [comment]
Yes, I installed Pillow from source before, and I use ./configure and dont'have any error. Sorry for my english.

**Comment by iezed** [comment]
I have only file Pillow-4.1.1-py3.5-macosx-10.6-intel.egg, and not folder. It's the problem?

**Comment by TheJJ** [comment]
What do you mean "not folder"?
The error indicates that the buildsystem can't access this file.

**Comment by zuntrax** [comment]
Please try `make mrproper && ./configure && make`. That might resolve the problem if cmake has old information cached.

**Comment by iezed** [comment]
I have just files .egg it's not a folder. I need install Pillow with pip and not from source?

**Comment by iezed** [comment]
I installed with pip and now I have  a folder. Ok, thanks.

**Comment by TheJJ** [comment]
So your error is resolved?

**Comment by iezed** [comment]
Yes, thank you all.

**Comment by iezed** [comment]
Hi, now I have this error.
/Users/fabrizio/github/games/SFTtech/openage/libopenage/util/fslike/directory.cpp:213:16: error: use of undeclared
      identifier 'CLOCK_REALTIME'
        clock_gettime(CLOCK_REALTIME, ts);
                      ^
1 error generated.

**Comment by iezed** [comment]
This is the env :
-- The CXX compiler identification is AppleClang 7.0.2.7000181
-- Check for working CXX compiler: /usr/bin/clang++
-- Check for working CXX compiler: /usr/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test CXX_SUPPORTS_CXX14
-- Performing Test CXX_SUPPORTS_CXX14 - Success
-- Performing Test HAVE_THREAD_LOCAL_STORAGE
-- Performing Test HAVE_THREAD_LOCAL_STORAGE - Failed
-- Using python interpreter: /Library/Frameworks/Python.framework/Versions/3.5/bin/python3
-- Found Python: /Library/Frameworks/Python.framework/Versions/3.5/bin/python3 (Required is at least version "3.4") 
-- Found Cython: /Library/Frameworks/Python.framework/Versions/3.5/bin/python3 -m cython (found suitable version "0.25.2", minimum required is "0.25") 
-- Found numpy: /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/numpy/core/include  
-- Checking python3 module PIL.Image - Success
-- Checking python3 module PIL.ImageDraw - Success
-- Checking python3 module numpy - Success
-- Checking python3 module pygments - Success
-- Checking utility program opusenc - Success
-- Found Doxygen: /usr/local/bin/doxygen (found version "1.8.13")
