### ISSUE TITLE
make compiler issues on os x Yosemite.

### ISSUE THREAD

**Issue by iezed** [SFTtech/openage#819]
Hi, I have this error.

```
/Users/fabrizio/github/games/SFTtech/openage/libopenage/util/fslike/directory.cpp:213:16: error: use of undeclared
      identifier 'CLOCK_REALTIME'
        clock_gettime(CLOCK_REALTIME, ts);
                      ^
1 error generated.
```

**Comment by TheJJ** [comment]
@Birch-san it works for you, right? Any idea why it might bug for @iezed?

**Comment by zuntrax** [comment]
This happens in an Apple specific code block. I'd expect this to be included from `time.h` or `sys/time.h` in your include directory. This files should be present, otherwise there would have been another error. Can you check if `CLOCK_REALTIME` is defined in these files (and if not, in any other header in the global include directory)?

**Comment by Birch-san** [comment]
It worked for me; I use macOS Sierra. But apparently anything older than that will have trouble:

https://stackoverflow.com/questions/5167269/clock-gettime-alternative-in-mac-os-x

**Comment by iezed** [comment]
I found this tips : https://gist.github.com/jbenet/1087739, Maybe it may be useful.

**Comment by Birch-san** [comment]
Am I right in assuming that `#ifdef __MACH__ ` is basically the same as `#ifdef __APPLE__`? So it probably treats macOS Sierra and older macOS the same way.

If we use it verbatim: it will mean that we don't use `clock_gettime()` on macOS Sierra (even though it's available). maybe that's not a problem (I mean we're already in the middle of a compromise because we don't have `utimensat`), but still: I would prefer to keep the macOS Sierra build running the way it currently does.

I wonder if there's a more specific check that we can do than `#ifdef __MACH__ `.
I am not sure how to verify those constraints: `macOS > 10.12 && XCode >= 8`

**Comment by iezed** [comment]
I'm try this : 
#ifdef __MACH__
#include <mach/clock.h>
#include <mach/mach.h>
#endif

#ifdef __APPLE__
	struct timespec ts;
	//clock_gettime(CLOCK_REALTIME, ts);
	
	clock_serv_t cclock;
	mach_timespec_t mts;
	host_get_clock_service(mach_host_self(), CALENDAR_CLOCK, &cclock);
	clock_get_time(cclock, &mts);
	mach_port_deallocate(mach_task_self(), cclock);
	ts.tv_sec = mts.tv_sec;
	ts.tv_nsec = mts.tv_nsec;
	
	struct timeval tv[2];
	tv[0].tv_sec = ts.tv_sec;
	tv[0].tv_usec = ts.tv_nsec*1000;
	tv[1].tv_sec = ts.tv_sec;
	tv[1].tv_usec = ts.tv_nsec*1000;
	int result = utimes(path.c_str(), tv);
#else
	int result = utimensat(AT_FDCWD, path.c_str(), nullptr, 0) == 0;
#endif 
and worked, but when I runned I have blank screen.

**Comment by iezed** [comment]
http://stackoverflow.com/questions/2166483/which-macro-to-wrap-mac-os-x-specific-code-in-c-c

**Comment by ChipmunkV** [comment]
> and worked, but when I runned I have blank screen.

That may be another issue. We need someone with Mac to debug the input/dispatcher thing (https://github.com/SFTtech/openage/pull/756#issuecomment-292798424). It's not really reproducible.

**Comment by Birch-san** [comment]
I confirm that black screen is exactly what you should expect on master.

Like ChipmunkV says: you will need his magic commit if you want it to work:
https://github.com/ChipmunkV/openage/commit/d577f5681bf61e09cd7d8175661be2df389b9b4d

@ChipmunkV, I know you've said that the commit was removed because it was unexplainable. But where did you get the idea to do that? Did you read something somewhere?

**Comment by iezed** [comment]
Hi, I worked with copy download from gui-gl-context-fix-3 and I wrote in to the directory.cpp this : 

[directory.zip](https://github.com/SFTtech/openage/files/972085/directory.zip)
[directory.zip](https://github.com/SFTtech/openage/files/972086/directory.zip)

#ifdef __APPLE__
#include <time.h>
#include <sys/time.h>
#include <mach/clock.h>
#include <mach/mach.h>
#endif

#ifdef __APPLE__
	struct timespec ts;
	clock_serv_t cclock;
	mach_timespec_t mts;
	host_get_clock_service(mach_host_self(), CALENDAR_CLOCK, &cclock);
	clock_get_time(cclock, &mts);
	mach_port_deallocate(mach_task_self(), cclock);
	ts.tv_sec = mts.tv_sec;
	ts.tv_nsec = mts.tv_nsec;
	
	struct timeval tv[2];
	tv[0].tv_sec = ts.tv_sec;
	tv[0].tv_usec = ts.tv_nsec*1000;
	tv[1].tv_sec = ts.tv_sec;
	tv[1].tv_usec = ts.tv_nsec*1000;
	int result = utimes(path.c_str(), tv);
#else
	int result = utimensat(AT_FDCWD, path.c_str(), nullptr, 0) == 0;
#endif

I can build and when I ran, dont'have a black screen, I can see something.

https://gist.github.com/iezed/92c423da1ffe822e18d1da3284a6819a

**Comment by Birch-san** [comment]
@iezed, I want to see what preprocessor macros are available in your environment.
Please show me the output you get on your computer when running:

```bash
clang -x c++ -dM -E - < /dev/null | egrep -i '(apple|clang|mac)'
```

For reference, this is what I get (Mac OS 10.12 Sierra, XCode 8.3.2):
```
#define __APPLE_CC__ 6000
#define __APPLE__ 1
#define __ENVIRONMENT_MAC_OS_X_VERSION_MIN_REQUIRED__ 101200
#define __MACH__ 1
#define __VERSION__ "4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)"
#define __apple_build_version__ 8020042
#define __clang__ 1
#define __clang_major__ 8
#define __clang_minor__ 1
#define __clang_patchlevel__ 0
#define __clang_version__ "8.1.0 (clang-802.0.42)"
```

For reference I have heard that XCode 7 resembles this:
https://stackoverflow.com/questions/32985758/what-is-the-llvm-version-bundled-with-xcode-7

**Comment by iezed** [comment]
#define __APPLE_CC__ 6000
#define __APPLE__ 1
#define __ENVIRONMENT_MAC_OS_X_VERSION_MIN_REQUIRED__ 101000
#define __MACH__ 1
#define __VERSION__ "4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)"
#define __apple_build_version__ 7000181
#define __clang__ 1
#define __clang_major__ 7
#define __clang_minor__ 0
#define __clang_patchlevel__ 2
#define __clang_version__ "7.0.2 (clang-700.1.81)"

**Comment by Birch-san** [comment]
thanks. looks like `ENVIRONMENT_MAC_OS_X_VERSION_MIN_REQUIRED` tells us the macOS version, and `clang_major` tells us the XCode version.

so…
if `ENVIRONMENT_MAC_OS_X_VERSION_MIN_REQUIRED >= 101200 && clang_major >= 8`, then we can use `clock_gettime()`. otherwise we can fallback to the other implementation.

**Comment by iezed** [comment]
It's not possibile install xcode 8 on OSX 10.10.5.

**Comment by Birch-san** [comment]
yes, but it's possible to install XCode 7 on macOS 10.12, which would also mean `clock_gettime()` is unavailable.

**Comment by iezed** [comment]
I think clang_major depend from XCode not from macOS.

**Comment by TheJJ** [comment]
https://github.com/xdevs23/busybox-osx/blob/master/coreutils/touch.c

They just use `utimes(filename, nullptr)`, maybe it's another option?

**Comment by Birch-san** [comment]
I had just finished writing a very long macro:

```cpp
// __apple_build_version__ implies Apple Clang
// we need macOS 10.12 Sierra and XCode 8
// Apple Clang major version seems to imply XCode major version.
#if (defined __apple_build_version__ \
&& __ENVIRONMENT_MAC_OS_X_VERSION_MIN_REQUIRED__ >= 101200 \
&& __clang_major__ >= 8)
	#define clock_gettime_implemented 1
#endif
```

but yeah, nullptr is probably a much better option.

**Comment by TheJJ** [comment]
Wanna submit a quick pull? :D

**Comment by Birch-san** [comment]
hm, I've tried that with ChipmunkV's magic commit, and it does compile, but it crashes:

```
./run game
INFO [py] launching openage v0.3.0-898-g171ca610
INFO [py] compiled by AppleClang 8.0.0.8000042
INFO [py] running in DEVMODE
INFO launching engine with Path(Union(Directory(/Users/birch/git/openage/cfg).root @ (b'cfg',), Directory(/Users/birch/git/openage/assets).root @ (b'assets',)):) and fps limit 0
INFO SDL audio subsystems initialized
INFO Using audio device: default [freq=48000, format=32784, channels=2, samples=4096]
INFO Initialized SDL video subsystems.
INFO Compiled with Qt 5.8.0 and run with Qt 5.8.0
INFO Falling back to separate render context for GUI
INFO loading configuration files...
INFO [py] loading config file [Union(Directory(/Users/birch/git/openage/cfg).root @ (b'cfg',), Directory(/Users/birch/git/openage/assets).root @ (b'assets',))]:cfg/keybinds.oac...
INFO Loading time [engine]: 0.392 s
INFO Loading time   [game]: 0.433 s
INFO [T1] Loading game specification files...
INFO [T1] Loaded multi-csv file: 99984 sub-files
INFO [T1] Loading textures...
INFO [T1] Loading sounds...
INFO [T1] Loading time  [data]: 18.469 s
WARN [T2] ImageProvider was stopped during the load, so it'll appear like the requestTexture() isn't implemented.
WARN [T2] ImageProvider supports Texture type but has not implemented requestTexture()

SIGSEGV

FATAL: terminate has been called

current stack:

Traceback (most recent call last):
  File ?, in thread_start+0xd [0x7fffe82c008d]
  File ?, in _pthread_body [0x7fffe82c0887]
  File ?, in _pthread_body+0xb4 [0x7fffe82c093b]
  File ?, in QThreadStorageData::finish(void**)+0x99a [0x1087b49ba]
  File ?, in QQuickTransition::animations()+0x8b56 [0x107aa2696]
  File ?, in QQuickTransition::animations()+0x6c73 [0x107aa07b3]
  File ?, in QQuickTransition::animations()+0x79a1 [0x107aa14e1]
  File ?, in openage::gui::GuiGameSpecImageProviderImpl::requestTexture(QString const&, QSize*, QSize const&)+0xf7 [0x106c76d27]
  File ?, in QQuickImageProvider::requestTexture(QString const&, QSize*, QSize const&)+0x4c [0x107aada9c]
  File ?, in QMessageLogger::warning(char const*, ...) const+0xa7 [0x1087a0cf7]
  File ?, in QMessageLogger::debug(char const*, ...) const+0x11a [0x1087a015a]
  File ?, in qt_message_output(QtMsgType, QMessageLogContext const&, QString const&)+0x1ca [0x1087a626a]
  File ?, in openage::gui::gui_log(QtMsgType, QMessageLogContext const&, QString const&)+0x108 [0x106c7da18]
  File ?, in openage::log::log(openage::log::message const&)+0x1d [0x106d8d30d]
  File ?, in openage::log::LogSource::log(openage::log::message const&)+0x282 [0x106d8f122]
  File ?, in openage::log::FileSink::output_log_message(openage::log::message const&, openage::log::LogSource*)+0xf7 [0x106d8c2f7]
  File ?, in std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::operator<<<std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*)+0x2c [0x106b49b6c]
  File ?, in std::__1::char_traits<char>::length(char const*)+0x15 [0x106ab6965]
  File ?, in ?
  File ?, in _sigtramp+0x1a [0x7fffe82b6b3a]
  File ?, in std::terminate()+0x40 [0x7fffe6cb3df0]
  File ?, in std::__terminate(void (*)())+0x8 [0x7fffe6cb3d69]

handing over to the system...

libc++abi.dylib: terminating
make: *** [run] Abort trap: 6
```

**Comment by Birch-san** [comment]
Edit: actually, master + ChipmunkV's magic commit _does_ crash for me. so maybe this is not what caused it to crash.

**Comment by Birch-san** [comment]
https://github.com/SFTtech/openage/pull/821
fixes this compile issue.

**Comment by ChipmunkV** [comment]
> @ChipmunkV, I know you've said that the commit was removed because it was unexplainable. But where did you get the idea to do that? Did you read something somewhere?

@Birch-san, I knew that event loops in Qt use event dispatchers that have OS-specific implementation. Then you just disable the input handling part and try.

I think that the issue is easily fixable by implementing and installing a custom dispatcher with [QCoreApplication::setEventDispatcher()](http://doc.qt.io/qt-5/qcoreapplication.html#setEventDispatcher).

**Comment by iezed** [comment]
With last commit make finishes the job, but when i launch ./run still have blank screen.
Thank you so much.

**Comment by iezed** [comment]
I think now I can close this issues?

**Comment by iezed** [comment]
I think Yes :)
