### ISSUE TITLE
Purge opusfile (use libogg and libopus instead)

### ISSUE THREAD

**Issue by zuntrax** [SFTtech/openage#830]
Since we will start to use libopus and libogg directly with @castilma's PR #814, it makes sense to get rid of opusfile and implement sound loading with the more basic libraries.
This would also help us concerning our windows port since opusfile seems to be the last dependency not conveniently available through vcpkg.

**Comment by TheJJ** [comment]
Keep in mind that this would mean re-implementing `opusfile`, which might just be a wasted effort. The #814 tackles a totally different problem: `opusfile` can't write opusfiles, so we just reimplemented the writing.

**Comment by zuntrax** [comment]
@TheJJ I'm totally aware of that. However, implementing that for the cases we need shouldn't be too much effort. The other choice is packaging opusfile for vcpkg, but there was some weirdness there. I'd rather get rid of that dependency.

**Comment by Birch-san** [comment]
Rewriting opus support may help with Mac also:

https://github.com/SFTtech/openage/issues/831

**Comment by TheJJ** [comment]
I think that this is now obsolete as opusfile is packaged for windows vcpkg. As it can do the exact same loading we would reimplement, we should keep it.
