### ISSUE TITLE
Game detection

### ISSUE THREAD

**Issue by aftalavera** [SFTtech/openage#857]
```
converting from '/home/aftalavera/.wine/drive_c/Program Files (x86)/Steam/steamapps/common/Age2HD'
WARN [T13034957277530963224] [py] Game version(s) could not be detected in [Directory(/home/aftalavera/.wine/drive_c/Program Files (x86)/Steam/steamapps/common/Age2HD)]:
WARN [T13034957277530963224] [py] No supported game version found:
WARN [T13034957277530963224] [py]  * Age of Empires 2: The Age of Kings
WARN [T13034957277530963224] [py]  * Age of Empires 2: The Conquerors
WARN [T13034957277530963224] [py]  * Age of Empires 2: The Conquerors, Patch 1.0c
WARN [T13034957277530963224] [py]  * Age of Empires 2: Forgotten Empires
WARN [T13034957277530963224] [py]  * Age of Empires 2: HD Edition (Version 3.0+)
WARN [T13034957277530963224] [py]  * Age of Empires 2: HD + Forgotten Empires (Version 4.0+)
WARN [T13034957277530963224] [py]  * Age of Empires 2: HD + African Kingdoms (Version 4.7+)
WARN [T13034957277530963224] [py]  * Age of Empires 2: HD + Rise of the Rajas (Version 5.x)
WARN [T13034957277530963224] [py] You need at least one of:
WARN [T13034957277530963224] [py]  * Age of Empires 2: The Conquerors, Patch 1.0c
WARN [T13034957277530963224] [py]  * Age of Empires 2: Forgotten Empires
WARN [T13034957277530963224] [py]  * Age of Empires 2: HD Edition (Version 3.0+)
WARN [T13034957277530963224] [py]  * Age of Empires 2: HD + Forgotten Empires (Version 4.0+)
WARN [T13034957277530963224] [py]  * Age of Empires 2: HD + African Kingdoms (Version 4.7+)
 ERR [T13034957277530963224] [py] game asset conversion failed
```

How does this detect the game version? What does this message mean?

**Comment by TheJJ** [comment]
The game detection happens in `/openage/convert/game_versions.py`. The procedure works by looking at the folder contents and it checks if all the files that make up a version are there.

We need to do this to support different input formats for the media conversion. In your folder, the contents are apparently unknown. Can you `cd` to the folder and post the output of `ls -la` here please?

**Comment by aftalavera** [comment]
drwxrwxr-x 12 aftalavera aftalavera     4096 Jun 16 10:48 .
drwxrwxr-x  3 aftalavera aftalavera     4096 Jun 15 10:22 ..
-rw-rw-r--  1 aftalavera aftalavera      540 Jun 15 10:23 221380_install.vdf
-rwxrwxr-x  1 aftalavera aftalavera  7331840 Jun 15 10:23 Aok HD.exe
-rw-rw-r--  1 aftalavera aftalavera   246332 Jun 15 10:23 avutil-ttv-51.dll
-rw-rw-r--  1 aftalavera aftalavera    11531 Jun 15 10:23 BVT_FULL.ahk
-rw-rw-r--  1 aftalavera aftalavera     3696 Jun 15 10:23 BVT_INDIVIDUAL_TEST.ahk
drwxrwxr-x  4 aftalavera aftalavera     4096 Jun 15 10:25 _CommonRedist
-rw-rw-r--  1 aftalavera aftalavera   250605 Jun 15 10:23 curl-ca-bundle.crt
drwxrwxr-x  2 aftalavera aftalavera     4096 Jun 15 10:25 D3D9_DLLBACKUP
drwxrwxr-x 14 aftalavera aftalavera     4096 Jun 15 10:25 Docs
drwxrwxr-x  2 aftalavera aftalavera     4096 Jun 15 10:25 EmptySteamDepot
-rw-rw-r--  1 aftalavera aftalavera       11 Jun 15 10:23 .gitignore
-rw-rw-r--  1 aftalavera aftalavera      812 Jun 15 10:23 launch.ahk
-rwxrwxr-x  1 aftalavera aftalavera  1853952 Jun 15 10:23 Launcher.exe
-rw-rw-r--  1 aftalavera aftalavera   342016 Jun 15 10:23 libcurl-ttv.dll
-rw-rw-r--  1 aftalavera aftalavera  1271808 Jun 15 10:23 libeay32-ttv.dll
-rw-rw-r--  1 aftalavera aftalavera 12118968 Jun 15 10:23 libmfxsw32.dll
-rw-rw-r--  1 aftalavera aftalavera   394810 Jun 15 10:23 libmp3lame-ttv.dll
drwxrwxr-x 12 aftalavera aftalavera     4096 Jun 16 08:08 Logs
drwxrwxr-x  2 aftalavera aftalavera     4096 Jun 15 10:51 mods
-rw-rw-r--  1 aftalavera aftalavera      780 Jun 15 10:23 PerformanceTracker.txt
drwxrwxr-x  2 aftalavera aftalavera     4096 Jun 15 10:44 Profiles
drwxrwxr-x 16 aftalavera aftalavera     4096 Jun 15 10:25 resources
drwxrwxr-x  3 aftalavera aftalavera     4096 Jun 15 23:31 SaveGame
-rw-rw-r--  1 aftalavera aftalavera   158902 Jun 15 10:24 scenariobkg.bmp
-rw-rw-r--  1 aftalavera aftalavera   326144 Jun 15 10:24 ssleay32-ttv.dll
-rw-rw-r--  1 aftalavera aftalavera   217168 Jun 15 10:24 steam_api.dll
drwxrwxr-x  2 aftalavera aftalavera     4096 Jun 15 10:25 Support
-rw-rw-r--  1 aftalavera aftalavera   113171 Jun 15 10:24 swresample-ttv-0.dll
-rw-rw-r--  1 aftalavera aftalavera   142336 Jun 15 10:24 zlibwapi.dll

**Comment by aftalavera** [comment]
It may be hitting Support.breaks on Rise of the Rajas

**Comment by TheJJ** [comment]
Then the error message should tell you that a breaking version was found.

What version should be found? How did you download the stuff? Current Steam version?

**Comment by aftalavera** [comment]
Steam updates every time it runs.

I have this one HD Edition v5.1+ with Rise of the Rajas

**Comment by TheJJ** [comment]
Okay. Can you see if all the files you listed above do exist in your folder? Probably one is missing then.

**Comment by aftalavera** [comment]
???? listed and not there? Please explain

drwxrwxr-x 12 aftalavera aftalavera     4096 Jun 16 11:01 .
drwxrwxr-x  3 aftalavera aftalavera     4096 Jun 15 10:22 ..
-rw-rw-r--  1 aftalavera aftalavera      540 Jun 15 10:23 221380_install.vdf
-rwxrwxr-x  1 aftalavera aftalavera  7331840 Jun 15 10:23 Aok HD.exe
-rw-rw-r--  1 aftalavera aftalavera   246332 Jun 15 10:23 avutil-ttv-51.dll
-rw-rw-r--  1 aftalavera aftalavera    11531 Jun 15 10:23 BVT_FULL.ahk
-rw-rw-r--  1 aftalavera aftalavera     3696 Jun 15 10:23 BVT_INDIVIDUAL_TEST.ahk
drwxrwxr-x  4 aftalavera aftalavera     4096 Jun 15 10:25 _CommonRedist
-rw-rw-r--  1 aftalavera aftalavera   250605 Jun 15 10:23 curl-ca-bundle.crt
drwxrwxr-x  2 aftalavera aftalavera     4096 Jun 15 10:25 D3D9_DLLBACKUP
drwxrwxr-x 14 aftalavera aftalavera     4096 Jun 15 10:25 Docs
drwxrwxr-x  2 aftalavera aftalavera     4096 Jun 15 10:25 EmptySteamDepot
-rw-rw-r--  1 aftalavera aftalavera       11 Jun 15 10:23 .gitignore
-rw-rw-r--  1 aftalavera aftalavera      812 Jun 15 10:23 launch.ahk
-rwxrwxr-x  1 aftalavera aftalavera  1853952 Jun 15 10:23 Launcher.exe
-rw-rw-r--  1 aftalavera aftalavera   342016 Jun 15 10:23 libcurl-ttv.dll
-rw-rw-r--  1 aftalavera aftalavera  1271808 Jun 15 10:23 libeay32-ttv.dll
-rw-rw-r--  1 aftalavera aftalavera 12118968 Jun 15 10:23 libmfxsw32.dll
-rw-rw-r--  1 aftalavera aftalavera   394810 Jun 15 10:23 libmp3lame-ttv.dll
drwxrwxr-x 12 aftalavera aftalavera     4096 Jun 16 08:08 Logs
drwxrwxr-x  2 aftalavera aftalavera     4096 Jun 15 10:51 mods
-rw-rw-r--  1 aftalavera aftalavera      780 Jun 15 10:23 PerformanceTracker.txt
drwxrwxr-x  2 aftalavera aftalavera     4096 Jun 15 10:44 Profiles
drwxrwxr-x 16 aftalavera aftalavera     4096 Jun 15 10:25 resources
drwxrwxr-x  3 aftalavera aftalavera     4096 Jun 15 23:31 SaveGame
-rw-rw-r--  1 aftalavera aftalavera   158902 Jun 15 10:24 scenariobkg.bmp
-rw-rw-r--  1 aftalavera aftalavera   326144 Jun 15 10:24 ssleay32-ttv.dll
-rw-rw-r--  1 aftalavera aftalavera   217168 Jun 15 10:24 steam_api.dll
drwxrwxr-x  2 aftalavera aftalavera     4096 Jun 15 10:25 Support
-rw-rw-r--  1 aftalavera aftalavera   113171 Jun 15 10:24 swresample-ttv-0.dll
-rw-rw-r--  1 aftalavera aftalavera   142336 Jun 15 10:24 zlibwapi.dll

**Comment by TheJJ** [comment]
Do you have these three files?
* `AoK HD.exe` :white_check_mark:, I see it
* `resources/_common/dat/empires2_x2_p1.dat` :question:
* `resources/_packages/rise-of-the-rajas/config.json` :question:

**Comment by aftalavera** [comment]
All checked!

**Comment by TheJJ** [comment]
Then I have no idea why it would not detect the version correctly. Nevertheless, to use `openage` you need to select the african kingdoms version in the betas tab in Steam (-> 4.x).

**Comment by aftalavera** [comment]
Patch 4.3?

**Comment by TheJJ** [comment]
Yes, for example. They removed some graphics files from `5.x` which we need, that's why you need to downgrade at the moment.

**Comment by aftalavera** [comment]
It's doing something now!

Thanks a lot and how can I help?

**Comment by TheJJ** [comment]
See here: https://github.com/SFTtech/openage/blob/master/doc/contributing.md#what-can-i-do
And you probably want to join our matix/irc chatroom :)
