### ISSUE TITLE
Create asset packs and automatically locate them with the engine

### ISSUE THREAD

**Issue by mic-e** [SFTtech/openage#86]
Implement an asset loader that overlays multiple asset source directories. For an installed game, this should be `/usr/share/openage` (installed by the package) and `~/.openage` (the user-writable "userasset" folder).

You can also specify further paths to look for packs.

The userasset folder is used for storing files that are created by the user (e.g.: datapacks (converted game assets)), savegames, screenshots, etc.

The "asset locating mode" may be specified via `--assets={dev, installed}`. If not specified, it's auto-determined from the files in the folder where the executable lies (does `openage_version` exist?). `dev` => look in ./assets.

Performance optimization feature: Support packing folders in (tar) archives.

The AssetLoader takes an asset path (such as `termcolors.docx`) and an optional "on-modification" callback function (think inotify, manual "reload-assets" instruction) and returns a file-like object for reading (or raise an Exception).

All code in openage should rely on the AssetLocator instead of directly opening files.

**Comment by TheJJ** [comment]
A basic data pack format will be proposed with #204 as the pack is exactly the place to store versioning information.

**Comment by a-detiste** [comment]
Hi,

I'll add support for Age Of Empires II to Debian's game-data-packager, a tool that aim to support automatically packaging data for _all_ the games with a free engine and non-free assets.

You can have look here if you're curious:
http://anonscm.debian.org/cgit/pkg-games/game-data-packager.git/tree/data

Please also look for data in `/usr/share/games/openage` :smile:

**Comment by mic-e** [comment]
Nice to see that debian supports something like this. We will look in `/usr/share` as well as the user's homefolder.
Note that an installed version of the game is required for performing the conversion.

**Comment by a-detiste** [comment]
> debian

Feel free to adapt it to the distro of your choice if you find it usefull.

> conversion

There is a plugin system for games with specific needs and data conversion is already supported for [LGeneral][1] ; only requirement is that it can happen in a dedicated command-line tool provided by your repo.

If [this][2] is the conversion program, this could also be directly `import`ed in a to-be `openage.py` plugin:

[1]: http://anonscm.debian.org/cgit/pkg-games/game-data-packager.git/tree/game_data_packager/games/lgeneral.py

[2]: https://github.com/SFTtech/openage/tree/master/py/openage/convert
----

does this engine plan to support the demo version of the game ?

**Comment by janisozaur** [comment]
You should rather try using `$XDG_DATA_HOME` instead of `~/.openage`.

> `$XDG_DATA_HOME` defines the base directory relative to which user specific data files should be stored. If `$XDG_DATA_HOME` is either not set or empty, a default equal to `$HOME/.local/share` should be used.

http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by TheJJ** [comment]
Superseeded by #631
