### ISSUE TITLE
fslike test broken for case-insensitive filesystems

### ISSUE THREAD

**Issue by TheJJ** [SFTtech/openage#876]
Windows filesystems and apparently some mac systems (#874) have case insensitive filesystems.

Our `fslike` system was built for case-sensitive filesystems like Linux has.
So we have a test in `openage/util/fslike/test.py` that assumes the underlying filesystem is case-sensitive: It checks that when just an `a` is created, then an `A` is created and redirected to be the same `a`, and then we test if only `a` exists and not `A`, as `A` was redirected to `a`.

If now the underlying filesystem is case-insensitive, it will report that `A` and `a` exist, which breaks the test.

Solution: test if the underlying filesystem is case sensitive or not and adjust the test to expect different results then.

**Comment by Vtec234** [comment]
The problem would be that we then have different usage for case-sensitive and insensitive file systems. Maybe it would be better to make fslike a case-insensitive abstraction and on case-sensitive systems convert all paths to lowercase.

**Comment by TheJJ** [comment]
I think rewriting this might be too complicated. I think everything is implemented the right™ way, just that this test assumes the underlying filesystem properties. If we fix the test, the file creation procedures and naming don't need to be adjusted.

**Comment by ChipmunkV** [comment]
> convert all paths to lowercase

I've no idea about the question, but properly `convert to lowercase` means pulling a unicode library into the project.

**Comment by TheJJ** [comment]
We already have that, with Python (`filename.lower()`). The case-insensitive wrapper (which emulates a windows-like behavior on linux in order to locate original assets) is implemented [here](https://github.com/SFTtech/openage/blob/6a06adfbf66e725a8395e1e51cfe063047377546/openage/util/fslike/directory.py#L113).
