### ISSUE TITLE
Arch Linux package & insecure RPATH

### ISSUE THREAD

**Issue by FabioLolix** [SFTtech/openage#885]
Hi, some time ago I have adopted the AUR pkgbuild of Openage because it was orphaned and failed to install

It would be nice if you write that can be installed with "yaourt -S openage-git" or equivalent for Arch & derivates

I haven't tested yet the program because of issue #788 

Analyzing the package with [namcap](https://wiki.archlinux.org/index.php/Namcap) give me this result:

> $ namcap openage-git-v0.3.0.r980.g9661a697-1-x86_64.pkg.tar.xz
openage-git E: Insecure RPATH '/home/lolix/Dev/Github/PKGBUILD/openage-git/src/openage/build/libopenage' in file ('usr/bin/openage')

**Comment by TheJJ** [comment]
Thanks for reporting.

For reference, the error is printed when:
```
An RPATH (for an executable) is outside /usr/lib.
An RPATH to an insecure location is a potential security issue.
See FS#14049 for discussion.
```

**Comment by TheJJ** [comment]
The error is in the Arch PKGBUILD:

```
cp "$srcdir/$_pkgbase/run" $pkgdir/usr/bin/openage
```

This file has the rpath to run openage in the source folder successfully.

For gentoo, I package openage by installing `run.py` as `/usr/bin/openage`, not the compiled `run` file. It is not marked for install by `cmake` and therefore does not get its development-rpath removed. The arch package installs it anyway.

=> install `run.py`, not `run`

(`run` also embeds the python interpreter, which is only useful for debugging)

Another thing: why move files out of `lib64` into `lib`? Doesn't arch have a `lib64`?

**Comment by FabioLolix** [comment]
Thanks @TheJJ I have corrected the PKGBUILD

> why move files out of lib64 into lib? Doesn't arch have a lib64?

/usr/lib64 is a symlink to /usr/lib 
without this trick it fails to install because /usr/lib64 is a symlink in the system and a folder in the compiled package

**Comment by FabioLolix** [comment]
I have found a proper way for addressing the /usr/lib issue with a cmake flag 
`-DCMAKE_INSTALL_LIBDIR=/usr/lib`

@castilma I am the maintainer for the AUR package, I've seen @TheJJ is on the AUR too, I can add him if he wants

Anyway the build file can be found here https://github.com/FabioLolix/PKGBUILD/blob/master/openage-git/PKGBUILD

**Comment by FabioLolix** [comment]
I was asked to add Nyan as a dependency for the AUR, it is needed?

About cmake, I don't have seen the use of that flag often, just to say; I'm not a programmer, but I look at AUR and Arch's pkgbuild very often

**Comment by TheJJ** [comment]
Yes, that would be good. For now we should have `nyan-git` and once we have a first release, `nyan` should also be there.

**Comment by FabioLolix** [comment]
I have added the -DDOWNLOAD_NYAN=YES flag just before seeing this message, doing so simplify when I build with clean chroot 
but I can change it

**Comment by TheJJ** [comment]
For packaging, the auto-download should never be used. It's there to simplify developer life and allow development in both repos in parallel (without the need of a release).

**Comment by FabioLolix** [comment]
OK, I have setted for the packaged version 
I have some other questions I forgot before
* doxygen and graphviz are needed for building?

And what about this options?
> disabled options:
	backtrace
	gperftools-profiler
	gperftools-tcmalloc

Backtrace is in the AUR, while gperstools is in the official repository and provide both, I see tcmalloc is disabled by default in cmakelist

**Comment by TheJJ** [comment]
`doxygen` is not required, it's only required if there shall be a doc target which generates documentation. The `gperftools`-things are there for debugging and profiling. The `backtrace` in the AUR is the wrong one, we used `libbacktrace` from gcc. All of them are only useful for developing.

**Comment by FabioLolix** [comment]
Thanks
