### ISSUE TITLE
Build fails on armv7l

### ISSUE THREAD

**Issue by castilma** [SFTtech/openage#890]
I'm trying to build on a raspberry pi 3. after `./configure`ing  without additional options, make fails.

```
[  1%] Building CXX object libopenage/CMakeFiles/libopenage.dir/gui/guisys/public/gui_renderer.cpp.o
In file included from /usr/include/arm-linux-gnueabihf/qt5/QtGui/qopengl.h:99:0,
                 from /usr/include/arm-linux-gnueabihf/qt5/QtQuick/qquickwindow.h:45,
                 from /usr/include/arm-linux-gnueabihf/qt5/QtQuick/QQuickWindow:1,
                 from /home/pi/code/openage/libopenage/gui/guisys/public/../private/gui_renderer_impl.h:12,
                 from /home/pi/code/openage/libopenage/gui/guisys/public/gui_renderer.cpp:7:
/usr/include/GLES3/gl31.h:73:25: error: conflicting declaration ‘typedef khronos_ssize_t GLsizeiptr’
 typedef khronos_ssize_t GLsizeiptr;
                         ^~~~~~~~~~
In file included from /usr/include/GL/gl.h:2055:0,
                 from /home/pi/code/openage/libopenage/gui/guisys/public/../public/gui_renderer.h:12,
                 from /home/pi/code/openage/libopenage/gui/guisys/public/gui_renderer.cpp:3:
/usr/include/GL/glext.h:468:19: note: previous declaration as ‘typedef ptrdiff_t GLsizeiptr’
 typedef ptrdiff_t GLsizeiptr;
                   ^~~~~~~~~~
In file included from /usr/include/arm-linux-gnueabihf/qt5/QtGui/qopengl.h:99:0,
                 from /usr/include/arm-linux-gnueabihf/qt5/QtQuick/qquickwindow.h:45,
                 from /usr/include/arm-linux-gnueabihf/qt5/QtQuick/QQuickWindow:1,
                 from /home/pi/code/openage/libopenage/gui/guisys/public/../private/gui_renderer_impl.h:12,
                 from /home/pi/code/openage/libopenage/gui/guisys/public/gui_renderer.cpp:7:
/usr/include/GLES3/gl31.h:74:26: error: conflicting declaration ‘typedef khronos_intptr_t GLintptr’
 typedef khronos_intptr_t GLintptr;
                          ^~~~~~~~
In file included from /usr/include/GL/gl.h:2055:0,
                 from /home/pi/code/openage/libopenage/gui/guisys/public/../public/gui_renderer.h:12,
                 from /home/pi/code/openage/libopenage/gui/guisys/public/gui_renderer.cpp:3:
/usr/include/GL/glext.h:469:19: note: previous declaration as ‘typedef ptrdiff_t GLintptr’
 typedef ptrdiff_t GLintptr;
                   ^~~~~~~~
libopenage/CMakeFiles/libopenage.dir/build.make:1766: die Regel für Ziel „libopenage/CMakeFiles/libopenage.dir/gui/guisys/public/gui_renderer.cpp.o“ scheiterte
make[3]: *** [libopenage/CMakeFiles/libopenage.dir/gui/guisys/public/gui_renderer.cpp.o] Fehler 1
CMakeFiles/Makefile2:1513: die Regel für Ziel „libopenage/CMakeFiles/libopenage.dir/all“ scheiterte
make[2]: *** [libopenage/CMakeFiles/libopenage.dir/all] Fehler 2
Makefile:138: die Regel für Ziel „all“ scheiterte
make[1]: *** [all] Fehler 2
Makefile:33: die Regel für Ziel „build“ scheiterte
make: *** [build] Fehler 2
```
I understand the error but have no clue, how to fix it.

**Comment by Vtec234** [comment]
As a hacky hack that might work, try replacing `typedef khronos_ssize_t GLsizeiptr` with `typedef ptrdiff_t GLsizeiptr` and `typedef khronos_intptr_t GLintptr` with `typedef ptrdiff_t GLintptr`. Source : https://bugs.webkit.org/show_bug.cgi?id=133550

**Comment by janisozaur** [comment]
As I was testing the other day, the `BREAKPOINT` macro also is invalid for architectures different than x86/x86-64

https://github.com/SFTtech/openage/blob/9661a697809b5f481ca8536b17e2d1272eb16264/libopenage/util/compiler.h#L64

**Comment by ChipmunkV** [comment]
The easy way to compile stuff for raspberry pi 2 or 3 with armv7 is to crosscompile on a x86_64 Ubuntu installation with installed 'lib*-armhf' packages. Needs a cmake toolchain file (haven't got it with me, but it was something rather short).

**Comment by Seadragon91** [comment]
For cross compiling this stackoverflow answer could be helpful
https://stackoverflow.com/a/19269715

**Comment by deltaidea** [comment]
I'm just passing by, but why do you even support building _this_ on a freaking _Raspberry Pi_? What's the use case?

**Comment by ChipmunkV** [comment]
@deltaidea, well, someone (castilma) appears to be motivated to run it on Pi. I know that there is usually no effort required to build for armv7 Pi (Debian supports armv7). The only thing was the Pi's poor (pun intended) OpenGL ES driver, but some guy is doing or already done a real OpenGL driver for Pi.

**Comment by castilma** [comment]
@deltaidea , I bought a PI so I can save energy by developing on it instead on my desktop pc. So that's why I'd like not to crosscompile. I will try vtec234's solution, even though they changed headers from 3rd party code that exists in their source dir by undefining a macro. I will see if this works for me, too.

**Comment by chocoladisco** [comment]
@janisozaur what we maybe should do there is fix the definition of BREAKPOINT to something like:
```c
#ifdef _MSC_VER
#define BREAKPOINT __debugbreak()
#elif __ARM__
#define BREAKPOINT  __builtin_trap()
#elif __M_ARM
#define BREAKPOINT whatever
#else
#define BREAKPOINT asm("int $3;")
#endif
```
no guarantees that this works however...

**Comment by Askmewho** [comment]
the pi 3 cant give you opengl 3.1 support

**Comment by TheJJ** [comment]
as a few years have passed, we should try again and open new issues if necessary.
