### ISSUE TITLE
Setup CI via Travis CI

### ISSUE THREAD

**Issue by sairam** [SFTtech/openage#913]
Travis CI has offering for Mac OS X . Offers free for OpenSource projects.

https://blog.travis-ci.com/2017-09-22-macos-update

**Comment by TheJJ** [comment]
The previous discussion for that matter was here: #658 

So our main concern was speed and customizability of the machine. Did this improve since then?

**Comment by D4N** [comment]
I don't think that the speed has really improved, at least not on the osx side. If you submit a build on a bad time & day then it can take hours for the job to start.

**Comment by TheJJ** [comment]
I've just heard from a friend who uses the travis mac builds that they queue up horribly. So I'd say we still shouldn't use travis, but instead rely on our own [kevin](https://github.com/SFTtech/kevin) that does blazingly fast builds.

**Comment by zuntrax** [comment]
Once we have working windows builds, I might think about macos again...
