### ISSUE TITLE
Weird pillow error in CMake

### ISSUE THREAD

**Issue by hgdagon** [SFTtech/openage#932]
Trying to compile for Windows, but can't even get there, since CMake throws an error when generating Makefile:

`tError: The _imaging extension was built for another version of Pillow or PIL: Core Version: "4.2.1"Pillow Version:  4.2.1`

Any ideas?

**Comment by heinezen** [comment]
@tusharpm

**Comment by tusharpm** [comment]
I haven't seen this on my machine. The Pillow version I have is 4.3.0.
@hgdagon do you mind trying an upgrade? `pip install Pillow --upgrade` should do that.

python-pillow/Pillow#2607 reports a similar error (although it is for python27). Can we make sure this is not a regression there?

**Comment by hgdagon** [comment]
Upgrading does not work, I had to compile from source, and I really hope you guys don't use JPEG2000, because I had to compile [without it](https://github.com/python-pillow/Pillow/issues/2759). 
CMake seemed OK with that, but now it says opusenc is missing. I'll file a new issue about msys2 in general, once I get somewhere.

**Comment by tusharpm** [comment]
For `opusenc` see [this section in the build instructions](https://github.com/SFTtech/openage/blob/master/doc/build_instructions/windows_msvc.md#the-other-missing-dependencies).
I haven't used msys2 yet. There's a page in [the project's wiki](https://github.com/SFTtech/openage/wiki/%5BWIP%5D-Compiling-on-Windows), but it could be outdated.

**Comment by hgdagon** [comment]
@tusharpm completely disregard what I said, I thought I had `opus-tools`, apparently I didn't...
I can already tell you the wiki page is outdated (not just the part about Pillow). I'll make a new issue when I have built OpenAGE (or if I give up at some point).

**Comment by hgdagon** [comment]
Refer to [this one](https://github.com/SFTtech/openage/issues/934)
