### ISSUE TITLE
Why not use POEditor for translation?

### ISSUE THREAD

**Issue by TomJansen** [SFTtech/openage#943]
First I want to say thank you all for this great project. I want to contribute but my code is still to shitty to do so. Anyway, I really want to help and I can add localization for Dutch. I think that https://poeditor.com/ is the easiest way to localize. Let me know what you think.

-TJ

**Comment by TomJansen** [comment]
I see now that only the first 1000 strings are free. Maybe some other website? Or more information on how to translate would be nice.

**Comment by heinezen** [comment]
Free or open translation tools would be preferred, but are rare these days. I guess a new Github repo for language translation will do the job. The software backend will probably use `qtlinguist` as mentioned in #107 .

**Comment by TheJJ** [comment]
I suggest we continue the discussion in #107. To have a online translation option is certainly a good option, but we're currently lacking any translation infrastructure in the overall code anyway.

@TomJansen if you like, you can do a bit research on how to perform translations for a Qt-C++-project in a sane way. Once we have some ideas, we can start implementing them.

-> #107.
