### ISSUE TITLE
CMake Error at buildsystem/codegen.cmake:25 (message):   failed to get target list from codegen invocation

### ISSUE THREAD

**Issue by ryandakid** [SFTtech/openage#946]
I almost fixed everything, just this is left...

```
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files (x86)\Python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\SFTtech-openage-fb4a9eb\openage\__main__.py", line 133, in <module>
    sys.exit(main())
  File "C:\SFTtech-openage-fb4a9eb\openage\__main__.py", line 83, in main
    from .convert.main import init_subparser
  File "C:\SFTtech-openage-fb4a9eb\openage\convert\main.py", line 7, in <module>
    import readline  # pylint: disable=unused-import
ModuleNotFoundError: No module named 'readline'
CMake Error at buildsystem/codegen.cmake:25 (message):
  failed to get target list from codegen invocation
Call Stack (most recent call first):
  libopenage/CMakeLists.txt:54 (codegen_run)


-- Configuring incomplete, errors occurred!
See also "C:/SFTtech-openage-fb4a9eb/build/CMakeFiles/CMakeOutput.log".
```

**Comment by tusharpm** [comment]
This seems missing in the build instructions: `pip install pyreadline readline` in the “python modules” section.

**Comment by ryandakid** [comment]
New Error: When Running, I get

```
C:\SFTtech-openage-fb4a9eb>run
Traceback (most recent call last):
  File "run.py", line 15, in init run
    main()
  File "C:\SFTtech-openage-fb4a9eb\openage\__main__.py", line 126, in main
    return args.entrypoint(args, cli.error)
  File "C:\SFTtech-openage-fb4a9eb\openage\game\main.py", line 32, in main
    from .main_cpp import run_game
ImportError: DLL load failed: The specified procedure could not be found.
```

**Comment by tusharpm** [comment]
For DejaVu, get the latest `dejavu-fonts-ttf` zip file. That is [`dejavu-fonts-ttf-2.37.zip`](http://sourceforge.net/projects/dejavu/files/dejavu/2.37/dejavu-fonts-ttf-2.37.zip) as of now. From that you'll need to install `ttf/DejaVuSerif*.ttf`. Installing a font on Windows is done by double-clicking or copying the file to `%WINDIR%/Fonts`.

The error you've mentioned is seen if `openage.dll` or one of its dependencies is not found. Did you follow the procedure mentioned in ["Running openage (in devmode)"](https://github.com/SFTtech/openage/blob/master/doc/build_instructions/windows_msvc.md#running-openage-in-devmode)? Alternatively, did you see any errors on your command window for any of the steps before?

**Comment by TheJJ** [comment]
Any success in fixing your issue?

**Comment by ryandakid** [comment]
No...

**Comment by tusharpm** [comment]
@ryandakid, if you're still facing "`ImportError: DLL load failed`", please follow these steps:
- Download and extract [Dependency Walker](http://dependencywalker.com/depends22_x86.zip), to a convenient location. Copy the full path to `depends.exe`.
- Find `openage.dll` in your build directory: that should be `<openage directory>\build\libopenage\RelWithDebInfo\openage.dll`, if you followed the instructions exactly.
- In a command prompt where you tried running openage:
`<path to depends.exe> /ot:depends_output.txt <path to openage.dll>`
This will create a text file called `depends_output.txt` in your current directory which lists `openage.dll`'s dependencies recursively.
- You can try scrolling in the GUI to look for the missing dependency; ignore errors related to `api-ms-*` and `ext-ms-*` DLLs.
- Please share the generated `depends_output.txt` in case you don't find it.

If you're facing a different issue than before, please provide more details about it.

**Comment by TheJJ** [comment]
Closed due to inactivity. Please report back if you need further assistance.
