### ISSUE TITLE
What's the difference to 0ad?

### ISSUE THREAD

**Issue by rugk** [SFTtech/openage#948]
Why should I use this software instead of a – nearly – clone 0ad?

**Comment by heinezen** [comment]
First and foremost, 0.a.d. is a game and tries to do its own thing in regards to mechanics, strategy and gameplay. We want to create close a FLOSS replica of the Genie Engine. They are incorporating various ideas that are similar to AoE, but prevent us from using their Pyrogenesis engine:

* Pyrogenesis is a 3D engine. We will use 2D sprites like the original AoE2 did.
* 0 a.d is one game, we're building an engine. We're aiming for supporting the 3 official Genie games AoE1, AoE2 and SWGB (+ addons) and simultaneously be a platform for new AoE-like game.
* Our design approach is much more focussed on modularity and mod support. Most of our engine features are built from scratch to satisfy the needs of the AoE2 modding community.

To answer your question properly: You should wait for openage, if you want to play a reimplementation of Age of Empires plus better modding support, minus annoying old bugs. I hope this answers your question :)

**Comment by rugk** [comment]
Yeah, thanks. This answers my question very well.

**Comment by mdrost** [comment]
Couldn't openage be a modified version of 0ad?

**Comment by rugk** [comment]
(or a plugin)

**Comment by TheJJ** [comment]
Everything™ can be done, but at the moment we have the intention of creating the engine ourselves. The openage engine and its upcoming features (especially nyan and the tickless game simulation) are quite different from 0ad.

And we do have fun reinventing the wheel and to add rockets to it.
