### ISSUE TITLE
Improve language on the contributing section of the README file

### ISSUE THREAD

**Issue by caio1982** [SFTtech/openage#950]
Hi there, it is your project and yeah I do get irony and sarcasm but people might easily misread it and find the contributing section of the README too passive aggressive. The detailed doc on how to contribute is actually pretty awesome so I don't see the need for the current language, which even spawned a micro sub-thread about it on Hacker News: https://news.ycombinator.com/item?id=16029855

Humbly, I don't have any specific fix at hand for the README file but I'd rather simply link the detailed doc on how to contribute/help there instead. It's simpler and gets the job done without ambiguity, unless such ambiguity is being used as a pre-filter of interested developers (and this is totally your right to do so, none of my business!).

**Comment by TheJJ** [comment]
You guessed exactly right, this is intended as a pre-filter :)

We want to build a fun developer community where we don't have to watch out for social landmines constantly. This worked very well so far 😄.
