### ISSUE TITLE
Failed to load assets: converted sounds

### ISSUE THREAD

**Issue by tusharpm** [SFTtech/openage#972]
The following errors are reported by the program (`run.py` or `run.exe`) before halting:
```
File "T:\GitRepo\openage\libopenage\audio\opus_loading.cpp", line 118, in struct openage::audio::opus_file_t __cdecl openage::audio::open_opus_file(const class openage::util::Path &)
class openage::audio::Error: Could not open opus file: Path(Union(Directory(T:/GitRepo/openage\cfg).root @ (b'cfg',), Directory(T:/GitRepo/openage\assets).root @ (b'assets',)):/assets/converted/sounds/5123.opus) = 'T:/GitRepo/openage\assets/converted/sounds/5123.opus': Header packet was invalid or missing
[...]
  File "T:\GitRepo\openage\libopenage\audio\opus_loading.cpp", line 118, in struct openage::audio::opus_file_t __cdecl openage::audio::open_opus_file(const class openage::util::Path &)
class openage::audio::Error: Could not open opus file: Path(Union(Directory(T:/GitRepo/openage\cfg).root @ (b'cfg',), Directory(T:/GitRepo/openage\assets).root @ (b'assets',)):/assets/converted/sounds/5353.opus) = 'T:/GitRepo/openage\assets/converted/sounds/5353.opus': Header packet was invalid or missing
```
Note: this used to work with `opusenc.exe` earlier.

**Comment by zuntrax** [comment]
Can't reproduce on linux, this might be windows-specific.

**Comment by tusharpm** [comment]
@heinezen observed the same error on Ubuntu, as mentioned in the chat.
@zuntrax, can you check if the converted assets are generated by the new method? Try moving `assets/converted` directory somewhere else (removing would also work, but is irreversible).

**Comment by TheJJ** [comment]
@tusharpm created a diff between two verbose outputs of `mpv` playing the old and new files:

```
T:\GitRepo\openage\build\converted_new>diff -ur mpv_5123.txt mpv_5123_new.txt
--- mpv_5123.txt        2018-02-11 03:22:03.717311100 +0530
+++ mpv_5123_new.txt    2018-02-11 03:21:29.319336100 +0530
@@ -27,8 +27,7 @@
 [file] Opening 5123.opus
 [demux] Trying demuxers for level=normal.
 [lavf] Found 'ogg' at score=100 size=2048.
-[ffmpeg/demuxer] ogg: 669 bytes of comment header remain
-[lavf] avformat_find_stream_info() finished after 3659 bytes.
+[lavf] avformat_find_stream_info() finished after 2080 bytes.
 [demux] Detected file format: ogg (libavformat)
 [cplayer] Opening done: 5123.opus
 [find_files] Loading external files in .
```

**Comment by TheJJ** [comment]
![mediainfocapture](https://user-images.githubusercontent.com/673543/36080542-fa5eb25a-0f91-11e8-8104-521880344e86.PNG)

**Comment by castilma** [comment]
hmm, this has most likely to do with #814. the mpv output doesn't tell me much. but the output of openage looks more informative. i'd like to analyze the old a new opus files, but fear, that this won't be possible, since they're copyrighted... 

i will see, if i can reproduce. (this may take some days)

**Comment by heinezen** [comment]
There you go

[opus.zip](https://github.com/SFTtech/openage/files/1715077/opus.zip)

**Comment by castilma** [comment]
what happens if you replace the 2 mentioned files with good ones? does openage halt at a later point? or are those the only broken ones?

side note: openage should not halt, when it encounters a broken sound files.
