### ISSUE TITLE
Game version detection fails for clean AoE II: HD + Forgotten Empires

### ISSUE THREAD

**Issue by samuelgrigolato** [SFTtech/openage#987]
*The problem:* when I `./run` the game after a successful compilation I get this error:

```
Please select an Age of Kings installation directory.
Insert the index of one of the proposals, or any path:
(0) /d/msc/age2hd
> 0
converting from '/d/msc/age2hd'
WARN [py] You have installed incompatible game version(s):
WARN [py]  * Age of Empires 2: HD + Rise of the Rajas (Version 5.x)
WARN [py] You need at least one of:
WARN [py]  * Age of Empires 2: The Conquerors, Patch 1.0c
WARN [py]  * Age of Empires 2: Forgotten Empires
WARN [py]  * Age of Empires 2: HD Edition (Version 3.0+)
WARN [py]  * Age of Empires 2: HD + Forgotten Empires (Version 4.0+)
WARN [py]  * Age of Empires 2: HD + African Kingdoms (Version 4.7+)
 ERR [py] game asset conversion failed
```

Note that the version checker thinks that I have `Age of Empires 2: HD + Rise of the Rajas (Version 5.x)` but, in fact, I have only AoE 2: HD + Forgotten Empires, I do not currently own neither African Kingdoms nor Rise of the Rajas DLCs.

*Workaround:* there is a simple workaround, applying the following diff to `openage/convert/game_versions.py` "solves" the problem, forcing the module to identify my game as AoE 2: HD + FE.

> https://pastebin.com/QGz9dRZV

*Extra information:* the below pastebin is the output of a `find .` on the directory `$STEAM_HOME/resources/_packages/african-kingdoms`, maybe a possible solution is to execute the same command on a full installation and try to compare them? I'd happily do that if someone could provide this info.

> https://pastebin.com/25jigfVx

**Comment by samuelgrigolato** [comment]
Just a thought: if we fix #788 maybe we will fix this one too, and could condense some options in `game_versions.py` as `AoE 2: HD + any DLC combination`, as it seems that owning at least FE gives you the data for all other DLCs, simplifying the data conversion procedure.

**Comment by goto-bus-stop** [comment]
The difference between those entries is actually the asset version (v4.7 → v5.0). It's just that v5 was the release that also added Rise of the Rajas. So you're right about #788 being the core issue. If you have the Steam application installed you can switch to an older version using the Betas tab in the game's properties dialog. (4.3 works, not sure if they have any other versions listed.)

**Comment by samuelgrigolato** [comment]
For future reference, there is some related work done in #989.

**Comment by gasinvein** [comment]
Any progress on this?

**Comment by heinezen** [comment]
The new version detection should have solved this by now.
